### ISSUE TITLE
Any Electron app running on Win 10 16299.19 are not rendered

### ISSUE THREAD

**Issue by ruslanfedoseenko** [electron/electron#10863]
* Electron version: Dont know which electron version is used by apps. I tiried latest Slack, Discord(Including PTB and Canary versions) and Mattermost
* Operating system: Windows 10 16299.19 - latest update

### Expected behavior
App UI should be displayed

### Actual behavior
Apps are displayed as black or white rectangle. To fix it I can run app with --disable-gpu option.
I have a laptop with i5-2410m and nvidia 540M GPU - Asus K53SV
### How to reproduce
Just launch any of the above apps on Windows 10 16299.19 and simular hardware.

**Comment by ruslanfedoseenko** [comment]
Here is how electron-quick-start app looks like on my pc.
![image](https://user-images.githubusercontent.com/4517707/31820486-3aeea484-b5aa-11e7-822a-6c9727f1ea4c.png)
After toggling developer tools:
![image](https://user-images.githubusercontent.com/4517707/31820549-69fab2f4-b5aa-11e7-9c4d-155c194dccc0.png)

**Comment by robinwassen** [comment]
Windows 10 build 16299.19 is the update called Fall Creators Update with version number 1709 that started to roll out 3 days ago: https://blogs.windows.com/windowsexperience/2017/10/17/get-windows-10-fall-creators-update/

@ruslanfedoseenko What NVIDIA driver version are you using?

**Comment by ruslanfedoseenko** [comment]
387.92

**Comment by robinwassen** [comment]
I just updated to Version 1709 (OS Build 16299.19) to see if I could reproduce this, Slack, Visual Studio Code and the HEAD version of electron/master still runs fine.

So this seems to be related to something else than just the OS version. 

**My computer configuration:**
- Windows 10, x64, Version 1709 (OS Build 16299.19), Fall Creators Update 
- NVIDIA driver version 387.92
- CPU: i7-2600k, GFX: GeForce GTX 970

**Comment by GregorBiswanger** [comment]
Works on my Windows 10 16299.19 too. But no Notification API..

**Comment by ruslanfedoseenko** [comment]
OK found more details. As I'm a laptop user I have an Nvidia Optimus Tech. So if I select Nvidia as a default GPU the rendering glich is reproduced. And if I select Auto or Integrated adapter than everything works well.

**Comment by robinwassen** [comment]
@ruslanfedoseenko It would be interesting to see if you have the same issue with Chrome, in Chrome flags (chrome://flags/#ignore-gpu-blacklist) there is a setting for Override software rendering list.

I think if you enable it you force GPU acceleration, the bad part is that you might break your Chrome.

But it would be interesting to see if Chrome manage to detect if it should run with GPU acceleration or not better than Electron.

**Comment by ruslanfedoseenko** [comment]
After enabling this flag chrome works fine

**Comment by felixrieseberg** [comment]
Chances are _very_ high that we'll just inherit a bug fix from Chromium. If anyone has this issue, I'd love to know if you can repro with Electron 1.8.

**Comment by ruslanfedoseenko** [comment]
I've tried a electron-quick-start. Edited a package.json:
```
"devDependencies": {
    "electron": "~1.8"
}
```
After that I've run ```npm install && npm run``` and issue is still reproducable

**Comment by skllcrn** [comment]
Duplicate of #4380 and/or related to #10736?

**Comment by Matt-17** [comment]
With Win10x64 Fall Creators Update I ran into the same issues with electron apps (vscode, whatsapp, discord). This does happen only on my laptop with Intel HD3000/nvidia Quadro 2000M and since the update. When I restart the computer sometimes it works for a while. Haven't invested more time yet. 
With OS update I did not (manually) update my display drivers. I could not find any other programs having issues (including Chrome).

**Comment by skllcrn** [comment]
Out of curiosity @Matt-17, can you try downloading the latest Chrome Canary (Version 64.0.3258.0  or later) and see if you get flickering issues on http://webglsamples.org/multiple-views/multiple-views.html and fails on https://www.khronos.org/registry/webgl/sdk/tests/conformance/canvas/drawingbuffer-static-canvas-test.html. Additionally, are you using the latest NVIDIA drivers? If not, can you try on your current ones first, and then test again once you've updated?

**Comment by jacobq** [comment]
@felixrieseberg I am experiencing this problem with all electron apps, including one I made. Per your suggestion, I tried upgrading electron (-prebuilt-compile) from v1.7.9 to v1.8.2-beta.2. It doesn't seem to have had any effect (main window still appears all white; dev tools window still appears all black). No problems with Chrome (61.0.3163.100).

Windows 10.0.16299.19 64-bit running on Lenovo W520 laptop ("NVIDIA Quadro 1000M" and "Intel(R) HD 3000" listed for display adapters in device manager. The date shown for each of these drivers is over a year old.)

**Comment by fantasydr** [comment]
I'm using electron for game development which using WebGL as renderer API.
Recently I released the game and lots of users reported 'Black Screen' issue.
They also confirmed that Chrome works fine with the same WebGL content.

The '**--disable-gpu**' param is a valid workaround. But the WebGL feature will be disabled and I have to use Canvas as software renderer.

**Comment by robinwassen** [comment]
Odd note on the subject, if the path to the Electron app contains a Left-to-right mark the application will not render.

https://en.wikipedia.org/wiki/Left-to-right_mark

**Comment by obrys** [comment]
I'm experiencing the same problem. It's NVidia Optimus:
- NVIDIA Quadro M1000, driver version 21.21.13.7674 (23.1.2017)
- Intel HD Draphics 3000, driver version 9.17.10.4459 (19.05.2016)

All display drivers are the most recent ones from Lenovo manufacturer's site but the problem was there even before driver update. The problem triggered Creator Fall's update of Windows 10 this month. Before the update everything worked well so the driver version might not be the root cause.

**Comment by jacobq** [comment]
@obrys It sounds like your symptoms and graphics hardware are identical to mine. I had this problem and got it to stop by (re-)installing NVIDIA's graphics driver. (You mentioned that your driver is the "most recent" but not whether or not you reinstalled them.) My driver versions are:
* M1000: 21.21.13.4201 (downloaded from NVIDIA's website and reinstalled -- problem went away after that)
* HD3000: 9.17.10.4459 (didn't touch this one)

**Comment by obrys** [comment]
@jacobq Thanks for your advice! I have downgraded NVIDIA driver and all apps I need started working (Visual Studio Code and Microsoft Teams).

But it's strange. You are right. We have the same hardware. Lenovo W520 type 4284. After Windows update to 10.0.16299.64 I started having problems. I upgraded to the newest drivers from Lenovo's site but it didn't help. It's strange that older version directly from NVIDIA helped.

**Comment by Cleod9** [comment]
Curious, has anyone had success here running their app as an Administrator? We've had multiple users of our Electron project having a blank screen issue with Win 10 CU, and the problem was resolved after they right clicked the exe and chose "Run as Administrator".

**Comment by caipirginka** [comment]
I confirm there seems to be the same problem on my new laptop, both with the Slack App and with Visual Studio Code.
Running the latter with the "--disable-gpu" flag seemed to resolve it.
Hardware is an ASUS ZenBook Pro UX550VD with INtel HD Graphics 630 with Intel driver 22.20.16.4749.
Additional graphics is NVIDIA GeForce GTX 1050 with driver 376.20.
OS is Windows 10 Pro 10.0.15063.

Both Intel and NVIDIA drivers are the most recent.
Windows is not, but it doesn't find any updates, nor the Fall Creators Update, so it's still on the previous version.

I tried running both Apps as Administrator and by forcing the use of the integrated graphics card or the NVIDIA one, but to no avail, only the "--disable-gpu" flag was successful.

**Comment by Matt-17** [comment]
Sorry for late reply. I'm disabling the NVIDIA GPU in device manager when I need an electron app. It's not a useful workaround, if you need an electron app AND good GPU performance at the same time. But since I don't even need to restart, it seems to work for me right now.

**Comment by bpasero** [comment]
Are people seeing this also with VS Code that runs on Electron 2.0.0-beta.5? Download from [here](https://az764295.vo.msecnd.net/exploration/add3c6a1564943fe34e8a0b172dc9262bf7b6972/VSCode-win32-x64-1.22.0-exploration.zip).

**Comment by xiegeo** [comment]
@bpasero It does not fix the problem on my laptop. However if I open two instances of that program, if the first one was start with `--disable-gpu`, then second will display correctly without that option; if the first one was start without it, then the second window will not display contents even with `--disable-gpu`.

I have been using this work around on VS Code for a while, and just encountered it too on gitkraken. If I remember correctly, I had first tried to reinstall VS Code to try to fix the bug, which worked until I restarted my computer. Gitkraken also worked on first install, which happened more recently, but broke when I tried to used it again today.

I have a very old graphics card, GT 540M. If I switch the preferred graphics processor to the default option of auto-select, which chooses the integrated graphics processor for electron apps, then the problem also goes away.

**Comment by caimen** [comment]
--disable-gpu fixes this problem for me in GitHub desktop.  I have the same issue with Visual Studio Installer/Update application.  Been having this issue randomly off and on in various electron apps on my HP Zbook 15u G2 for about 6 months now.  My computer has an AMD Firepro M4170 and an HD Graphics 5500 integrated graphics.

**Comment by gimre** [comment]
We are seeing the same issue here with an Nvidia Quadro 1000M GPU, Chrome works with the same content. Using `--ignore-gpu-blacklist` fixes the problem.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by barnarddale** [comment]
> The '**--disable-gpu**' param is a valid workaround. But the WebGL feature will be disabled and I have to use Canvas as software renderer.

fantasydr just made my life a lot easier thanks to the --disable-gpu comment. Thanks!

**Comment by Inateno** [comment]
Hello,

I leave a comment here that could help someone.
One of our players got this issue of blackscreen.

We are using PIXI under the hood and Electron to ship on Steam.

What "fixed" this issue is to set a "tint" by default to every images.
CF: https://pixijs.download/dev/docs/PIXI.Sprite.html#tint

So for those who do not use PIXI but plain WebGL, maybe trying to implement this and set the default value as 0xFFFFFF.

Good luck.
