### ISSUE TITLE
Crash on notification in Windows 7

### ISSUE THREAD

**Issue by walltex** [electron/electron#10968]
Electron crashes on notification handling under Window 7
Here is stack trace from minidump file.

[desktop_notification_controller_issue.txt](https://github.com/electron/electron/files/1427754/desktop_notification_controller_issue.txt)

* Electron version: 1.6.15
* Operating system: Window 7 (6.1.7601 Service Pack 1)

### Expected behavior

no crash

### Actual behavior

crash

### How to reproduce

N/A

**Comment by felixrieseberg** [comment]
Thanks for the report! For reference, the crash happened [here](https://github.com/electron/electron/blob/1d25d58c2682061d1f075d7d6680abd75caeab17/brightray/browser/win/win32_desktop_notifications/desktop_notification_controller.cc#L326-L336), with `EXCEPTION_ACCESS_VIOLATION_READ`, but I can't really see what could be wrong.

@alespergl any ideas?

**Comment by felixrieseberg** [comment]
@walltex In general, I'd also recommend upgrading to the latest version - 1.7 for the battle-tested one, 1.8 for the latest features.

**Comment by walltex** [comment]
@felixrieseberg thanks. I usually upgrade to the latest stable version, but the issue now is that I can't update to Electron 1.7 due to one of the Chromium bugs in it. And 1.8 is not stable.
Looking forward to use stable 1.8.

**Comment by alespergl** [comment]
This is likely the crash which I fixed here: https://github.com/electron/electron/pull/10516
We never backported it, but I suppose we still could.

**Comment by Anrock** [comment]
@alespergl would be really nice to backport it to 1.7. Can't use 1.8 because of other major bugs there.

**Comment by MarshallOfSound** [comment]
@anrock What bugs are blocking you using 1.8?

**Comment by Anrock** [comment]
@MarshallOfSound mainly it was spellchecker not working in iframes (probably [this](https://github.com/electron/electron/issues/11147)). I see it's merged, but not mentioned in changelogs and last time i checked (1.8.3 afair) it wasn't working.

**Comment by Anrock** [comment]
@MarshallOfSound yup. Spellchecker still don't work for my app for some reason: spellcheck method of SpellCheckProvider just not being called. And i don't have time right now to debug it :(

**Comment by MarshallOfSound** [comment]
@Anrock Can you try `2.0.0-beta.6` it should contain the fix in the PR you linked 👍

**Comment by Anrock** [comment]
@MarshallOfSound tried it in the first place. Site embedded in my app won't load at all.
