### ISSUE TITLE
Terminal colors are not supported through electron in Windows

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#11488]
* Electron version: 1.7.10
* Operating system: Windows

### Expected behavior

When running in regular node (not electron) colors are supported and output correctly

```shell
node index.js
```

![screen shot 2017-12-20 at 1 25 26 pm](https://user-images.githubusercontent.com/1268976/34222382-6377e1b8-e589-11e7-95e9-e8a05698251c.png)

When running in electron colors are not supported and do not output correctly

```shell
.\node_modules\.bin\electron .
```

![screen shot 2017-12-20 at 1 25 43 pm](https://user-images.githubusercontent.com/1268976/34222398-71067074-e589-11e7-96d3-543e8c5d5c13.png)

### How to reproduce

My code...

```js
//index.js
console.log(process.versions)
console.log(require('chalk').red('hi there'))
console.log(require('supports-color'))
```

**Comment by brian-mann** [comment]
Oh I believe the issue covered all of these things - especially the steps to reproduce the issue.

Electron: 1.7.10
OS: Windows

**Comment by groundwater** [comment]
Hi @brian-mann. The issue format is important and should not be disregarded. Folks triaging and attending to these issues are dealing with a large volume of issues, and pull-requests. Having information in a standard place not only helps reviewers, but it's respectful of their time.

The template is small, and we feel it's quite fair to reporters. Thus I would recommend you update the original post to conform to the template.

**Comment by brian-mann** [comment]
done

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by cuixiping** [comment]
Electron v4.1.3 + Windows 7/10, still has this issue.

**Comment by Floffah** [comment]
This still happens on Electron v5.0.2 Windows 10. Makes the depug package not work as expected.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by idanwork** [comment]
Hi 
I'm having the same issue with electron **8.0.1**
And windows 10.


To recreate - create a new project with electron / chalk - using these:

package.json
```json
{
  "name": "electron-colors",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "electron index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chalk": "^3.0.0",
    "electron": "^8.0.1"
  }
}
```

index.js
```javascript
const chalk = require("chalk");

console.log("Chalk supported?", chalk.supportsColor, "\n",
 "Electron version", chalk.green(process.versions.electron), "\n",
    "OS Version",  chalk.blue(process.getSystemVersion()));

console.log("\x1b[36m%s\x1b[0m", "This will work on npm run though!");  
```

Then run either with _npm_ or directly calling _electron.exe_ you'll see the issue on both cases.
However,  when running with _npm_ the console does indeed support color if specified directly.

Using _npm_
```cmd
C:\Users\idanwork\Projects\electron-colors>npm run start

> electron-colors@1.0.0 start C:\Users\idanwork\Projects\electron-colors
> electron index.js


Chalk supported? false
 Electron version 8.0.1
 OS Version 10.0.17134
This will work on npm run though!
```
![image](https://user-images.githubusercontent.com/37815652/74962291-4d3ccd00-5418-11ea-96d1-cc477db9f152.png)


Using _electron.exe_
```cmd
C:\Users\idanwork\Projects\electron-colors>node_modules\.bin\electron .

Chalk supported? false
 Electron version 8.0.1
 OS Version 10.0.17134
?[36mThis will work on npm run though!?[0m
```
![image](https://user-images.githubusercontent.com/37815652/74962322-588ff880-5418-11ea-8c21-61ae93facab8.png)


This is the expected result, using _npm_ with macOS Catalina
```zsh
idanwork electron-colors % npm run start

> electron-colors@1.0.0 start /Users/idanwork/Projects/electron-colors
> electron index.js

Chalk supported? { level: 3, hasBasic: true, has256: true, has16m: true } 
 Electron version 8.0.1 
 OS Version 10.15.3
This will work on npm run though!
```

![image](https://user-images.githubusercontent.com/37815652/74962763-377bd780-5419-11ea-8955-7d8ea34a5ea5.png)

**Comment by petertorelli** [comment]
Why is this "blocked/need-info"? The example is concise and reproduceable is it not? I'm seeing the same issue, as I offer a command line version of my ElectronJS GUI for automation. I'm using electron v8.2.1.

**Comment by ahallicks** [comment]
![image](https://user-images.githubusercontent.com/717299/78766501-3ed35200-7981-11ea-99ae-fd8d95c89704.png)

It's not block/need-info. That was removed on the 26th Feb.

**Comment by giladnavot** [comment]
Issue still exists in Electron v10.1.1 
Windows 10 pro
OS build 19041.508

**Comment by Roaders** [comment]
Still an issue on
 Electron version 7.1.2
 OS Version 10.0.17763
(obtained using script above)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
