### ISSUE TITLE
session.clearStorageData cannot clear localstorage in file protocol without origin option

### ISSUE THREAD

**Issue by ekoneko** [electron/electron#12322]
* Electron version: 1.8.3 , 2.0.0-beta.2
* Operating system: osx 10.11.6

### Expected behavior

Exectue these code on `file://index.html`

````
const { session } = require('electron').remote
session.defaultSession.clearStorageData({
  // without set origin options
  storages: ['localstorage', 'caches', 'indexdb']
})
````

All local data should be removed.

### Actual behavior

Local storage data still exists. But cookies and indexdb were removed successfully.

If I set origin: `file://`, it works only for `file://` origin.

### How to reproduce

https://github.com/ekoneko/electron-clear-localstorage-bugreport

**Comment by felixrieseberg** [comment]
That's currently [explicit in the code](https://github.com/electron/electron/blob/53229e3d6c544c68137497ed09a074250c1af0fc/atom/browser/api/atom_api_session.cc#L148-L154). I'm wondering how much we can do about that, but I'll give it a solid try.

At the very least, we might want to clear it for other origins too (like `file`, `https`, and `http`)

**Comment by deepak1556** [comment]
@ekoneko I am unable to recreate the issue on MacOS with the specified versions. Are you making to sure to verify that the data is cleared after the `clearStorageData` operation completes. The clear task is async, you can pass a callback to the api to get notified. Let me know if you are still experiencing the bug, Thanks!

```
const { session } = require('electron').remote
session.defaultSession.clearStorageData({
  // without set origin options
  storages: ['localstorage', 'caches', 'indexdb']
}, () => {
  // verify if storages got cleared.
})
```

**Comment by deepak1556** [comment]
Currently the completion callback is called without the knowledge of whether `localStorage` was cleared. It is fixed in upstream with this CL https://chromium-review.googlesource.com/c/chromium/src/+/852234 , which should be in chromium v66.

**Comment by ekoneko** [comment]
Sorry for my late.

So it will be resolved when electron use chromium v66.

But this code work fine to me

````ts
session.defaultSession.clearStorageData({
  origin: 'file://myOrigin',
  storages: ['localstorage']
}, () => {
  session.defaultSession.clearStorageData({
    storages: ['cookies', 'indexdb']
  }, () => {
    nextWork()
  })
````

Anyway, it's not an electron bug, the issue should be closed.

**Comment by ekoneko** [comment]
@deepak1556  Sorry, but the chromium CL seems not the same thing to my issue :(

My problem is only happened in `file://xxx` window. Maybe you can clone my example and reproduction.

Yesterday I don't read the CL clearly (sorry for that), I think the issue still exists.

**Comment by ckerr** [comment]
@felixrieseberg is this something that still needs work?

**Comment by deepak1556** [comment]
@ekoneko the CL is related as it fixes the root cause of this issue, currently `session.clearStorageData` callback is not reliable signal for completion of localStorage data eviction. It should be fixed once https://github.com/electron/electron/pull/12477 lands. 

@ckerr there is nothing we can do on our side until the above PR lands.

**Comment by ekoneko** [comment]
Ok, I'll wait for that

**Comment by ekoneko** [comment]
It works fine in electron 3.0.4

**Comment by couranos** [comment]
> 
> 
>     * Electron version: 1.8.3 , 2.0.0-beta.2
> 
>     * Operating system: osx 10.11.6
> 
> 
> ### Expected behavior
> 
> Exectue these code on `file://index.html`
> 
> ```
> const { session } = require('electron').remote
> session.defaultSession.clearStorageData({
>   // without set origin options
>   storages: ['localstorage', 'caches', 'indexdb']
> })
> ```
> 
> All local data should be removed.
> ### Actual behavior
> 
> Local storage data still exists. But cookies and indexdb were removed successfully.
> 
> If I set origin: `file://`, it works only for `file://` origin.
> ### How to reproduce
> 
> https://github.com/ekoneko/electron-clear-localstorage-bugreport

I was looking for something like your code and ... I've found yours :)
