### ISSUE TITLE
No frame window inset taskbar when maximize twice

### ISSUE THREAD

**Issue by muxiaozi** [electron/electron#12971]
* Electron Version: 2.0.1
* Operating System (Platform and Version): Windows10 1803
* Last known working Electron version: 2.0.1

**Expected Behavior**
Maximized normal and restore normal when i click button in no frame window

**Actual behavior**
The first click is normal, but on the second click, there is a white edge on the window, and the window is also embedded under the taskbar.

**To Reproduce**
```sh
$ git clone https://github.com/muxiaozi/electron-quick-start.git
$ cd electron-quick-start
$ npm install
$ npm start || electron .
```
**Screenshots**
![image](https://user-images.githubusercontent.com/18480599/40154254-04d8592a-59c0-11e8-8864-acb12c1d26a7.png)

**Additional Information**
(┬＿┬)

**Comment by happypoulp** [comment]
Also reproduced on electron 1.7.15 and 1.8.7.

The blank edge can be seen more easily on this screenshot:

![issue 2 - top grey bar and inconsistent size](https://user-images.githubusercontent.com/100044/40227338-85a54ad0-5a8e-11e8-8373-42766dfa66b0.png)

The steps to reproduce are to click multiple times on maximize / restore button on a frameless window under windows build 1806 (specifically this build and not the previous ones).

**Comment by speedpacer** [comment]
I'm seeing this as well, in 1605 and 1803.  You can reproduce this by creating an electron-quick-start project, setting the frame to false and changing index.html

`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    **<style>
      body{margin:0;padding:0;background-color:red}
      #header{-webkit-app-region:drag;height:50px;width:100%;background-color:blue}
    </style>
    <div id="header"></div>**
    <h1>Hello World!</h1>
    <script>
      require('./renderer.js')
    </script>
  </body>
</html>
`
If you double-click the header once to maximize, it's fine, but the second time, there is a gap above the window, then a white space that pushes any elements you have at the top down, and every other time after that.  

Also, in both cases, when you unmaximize it, it jumps a little before it's fully restored.

**Comment by speedpacer** [comment]
Just realized this is happening with Spotify!

**Comment by ExtraCrafTX** [comment]
This has been bothering me about discord for more than a couple months now, and now that I started messing around with electron a bit, I have the same problem.

Any frameless window, when maximised, is fine the first time, then the second time you maximise it the position is off. Un-maximising and maximising again fixes the issue, but doing it again brings it back.
Effectively, the position is broken on every other maximise.

I thought I had a temporary workaround, and it did mostly work. What I did was every time I detected a maximise event, I simply un-maximised and maximised again through the code. I also kept a boolean so that the call wouldn't itself trigger the event. This worked fine, but then I noticed that when you minimize the window, the state flips. So after minimising and restoring, rather than being correct every time, it was off every time.
Except, if you minimise it before the first maximise, then it doesn't cause the issue. Working around this is fine as well, but it seems like there could be any number of other odd specifics that could cause it to reappear.

**Comment by speedpacer** [comment]
It seems the folks over at [hyper.js](https://github.com/zeit/hyper) have figured it out.

**Comment by ExtraCrafTX** [comment]
I just downloaded hyper.js and I have this problem with it too.

**Comment by ExtraCrafTX** [comment]
I have a temporary workaround for it. If you check the offset from the origin of the current display on maximise and the x and y aren't both the same and negative (I think its always -8 but not sure) then it mustn't have maximised correctly, so you can unmaximise and maximise through the code. This works but is obviously not ideal.

**Comment by speedpacer** [comment]
That's weird. I'm not seeing this behavior in Hyper.js.  

Thanks for the workaround. I'll give this a shot.

**Comment by ExtraCrafTX** [comment]
I know this may be obvious but I have to ask anyway, is your home computer using a multimonitor setup and your work computer using a single monitor? I have a feeling that it might be causing the issue (or at least part of it).

**Comment by Astrych** [comment]
I see that odd behaviour on my laptop (just one screen) so I think it isn't multi monitor related.

**Comment by speedpacer** [comment]
I have 3 monitors on both. The size of the monitors and the video cards are different. One has a GTX 1060 with 24" monitors and the other has an NVIDIA Quardro M5000 and 22" monitors.  All 1920x1080.

Sadly, the workaround from @Astrych above didn't work for me.

**Comment by Astrych** [comment]
@speedpacer Is issue occur every second maximization? What if you resize window by hand after you unmaximize it? Issue occures on next maximization?

**Comment by Astrych** [comment]
Now I noticed that window is not returning to the starting position after first unmaximization. After second maximization (leading to the issue with white bar on top) and unmaximization window returns to starting position. After applying my workaround window never returns to starting position. Multiple maximization and unmaximization cause window to slide down.

**Comment by ExtraCrafTX** [comment]
Indeed, the same happens to me when I use your workaround. However, the workaround that I posted seems to work well. The un-maximising and maximising again seems like it would cause some issues but it doesn't seem to do anything weird.

```js
mainWindow.on('maximize', () => {
    let disp = scr.getDisplayMatching(mainWindow.getBounds());
    let x = mainWindow.getBounds().x - disp.bounds.x;
    if(mainWindow.getBounds().y - disp.bounds.y > x){
        mainWindow.unmaximize();
        mainWindow.maximize();
    }
})
```

I'm not too experienced with electron so the way I'm getting the display and stuff might not be the best, but anyway.

**Comment by speedpacer** [comment]
Setting "transparent: true" seems to work:

```
const electron = require('electron');
const { app, BrowserWindow } = electron;

let win;
function createWindow() {
    win = new BrowserWindow(
        {
            transparent: true,
            frame: false,
            toolbar: false,
            show: false
        }
    );

    win.once('ready-to-show', () => {
        win.show();
        win.focus();
        win.maximize();
    })

    win.loadURL(`file://${__dirname}/index.html`);
}

app.on('ready', createWindow);
```

**Comment by TomSputz** [comment]
My demo for the dupe that just referenced this - https://github.com/TomSputz/electron-frameless-demo , it mostly, just demonstrates what has been found in this issue already, with the offset being measurable, and potentially used to detect the issue

**Comment by GrantGryczan** [comment]
Additionally, if you have more monitors to the left and/or the right, the window size will be extended onto each by exactly 1 pixel while maximized, unless it is maximized initially in the window's creation. (My environment is the same as theirs.)

**Comment by DExterDarkLord** [comment]
So when will this be fixed? Work around aren't that reliable from my testing.

According to my testing:
BUG doesn't occur if you focus out of the window and refocus to maximize it.

**Comment by Astrych** [comment]
@DExterDarkLord Are you sure? In my experience unfocusing and focusing does nothing. What platform do you use?

**Comment by Astrych** [comment]
My workaround was not perfect, caused window to move 17px down on every unmaximization.
@ExtraCrafTX workaround is not perfect as well: it cause window to move 17px down on first unmaximization. Second and next unmaximizations works properly.

@ExtraCrafTX You don't need to check that condition:
```javascript
if( this.window.getBounds().y - disp.bounds.y > x)
```
You can just check:
```javascript
if (this.window.getBounds().y > 0)
```

Screen bounds are constant and with proper values. Thing that change is window bounds object. Below you can see values form my computer.

On first maximisation:
window bounds = {x: -8, y: -8, width: 1936, height: 1056}
display bounds = {x: 0, y: 0, width: 1920, height: 1080}

On second maximisation:
window bounds = {x: -8, y: 9, width: 1936, height: 1073}
display bounds = {x: 0, y: 0, width: 1920, height: 1080}

As you can see window has strange bounds: extending on x and y out of the screen.
When we change x value on maximize event:

```javascript
mainWindow.on('maximize', () => {
    const bounds = window.getBounds();
    bounds.y += 8;
    window.setBounds(bounds);
});
```
we can see white title bar which should be hidden. What's strange after that correction unmaximization stop working at all. You have to resize window manually which cause this strange white title bar to disappear and window to loose maximization state.

So the real issue is that maximised frameless window is not truly frameless at all. It has visible white space representing title bar but hidden from users eyes by window shifting out of the screen. Because of that window bounds are wrong which cause that strange behaviour.

My new workaround is modified version of my previous one:

```javascript
if (process.platform === "win32") {
        window.on("unmaximize", () => {
        const bounds = window.getBounds();
        bounds.width += 1;
        bounds.y -= 17; // correct window's down shifting.
        window.setBounds(bounds);
        bounds.width -= 1;
        window.setBounds(bounds);
    });
}
```
Seems to work properly. At least for me.

**Comment by Astrych** [comment]
The issue must be related somehow to #5267 and #8728
Adding thickFrame: false to BorwserWindow options fix it but supposedly removes native animations and cause window.unmaximize() to stop working. But double clicking on a part of the window with
```
-webkit-app-region: drag
```
works.

Issues #5267 and #8728 was fixed by pull request #9167 but maybe it introduced this issue?

**Comment by timfish** [comment]
If you try all the previous release branches of Electron does this issue ever stop happening?

I assumed this issue was caused by the recent Windows 10 update as this started happening in Spotify around the same time and Spotify is not an Electron app!

**Comment by Astrych** [comment]
Not tried older versions yet. If the issue occurs for Spotify app it's not electron related but rather libchromiumcontent related.

**Comment by timfish** [comment]
I'm pretty sure Spotify doesn't use libchromiumcontent either. Last time Spotify spoke openly about their stack they said they were using use CEF uses 

It could always be a more general problem with frameless apps on Windows 10.

**Comment by ExtraCrafTX** [comment]
> It could always be a more general problem with frameless apps on Windows 10.
It could be, I might test some of that soon

> You can just check:
> 
> if (window.getBounds().y > 0)
No actually, if you have a multi-monitor setup this can fail as the origin of each monitor will be different, not necessarily 0.
I mentioned the 11 px discrepancy, which is what my workaround checks. I am not sure of the reason it is 11 px and this may change with display scaling, so I just check that the y is greater than x relative to the screen's origin.

**Comment by Astrych** [comment]
CEF is chromium, libchromiumcontent is just a renderer part of chromium. Almost the same ;)

**Comment by Astrych** [comment]
> No actually, if you have a multi-monitor setup this can fail as the origin of each monitor will be different, not necessarily 0.

@ExtraCrafTX I thought disp.bounds.y will always stay at 0 but never checked that. Ok then.

> I mentioned the 11 px discrepancy, which is what my workaround checks. I am not sure of the reason it is 11 px and this may change with display scaling, so I just check that the y is greater than x relative to the screen's origin.

You are right. I've checked it for different resolutions and for them is stay the same but it changes for different screen scaling. IT probably changes for different Windows versions too (Windows 7, 8.1, 10). It was the case in issues mentioned earlier.

So my workaround is working only for scaling 100%. :/ For others shift of 17px is to much. Your workaround is good but it still has the initial window down shift at first unmaximization. Do you have solution for that maybe?

**Comment by ExtraCrafTX** [comment]
> CEF is chromium, libchromiumcontent is just a renderer part of chromium. Almost the same ;)

It makes sense in that case

> So my workaround is working only for scaling 100%. :/ For others shift of 17px is to much. Your workaround is good but it still has the initial window down shift at first unmaximization. Do you have solution for that maybe?

Not as of now, I haven't really looked at fixing that yet, I will look at it now and if I can figure it out in 30 mins then that's good, otherwise it'll have to be after 2 weeks since I won't have a computer to be able to test it with during that period.

I am thinking something along the lines of you save the bounds just before a maximise, then you can check when restored. I am not sure if this is possible though since the `onMaximise` event runs after the bounds have been adjusted. In that case, you might have to save the bounds on every change (resize, move, etc.).

**Comment by Astrych** [comment]
@timfish  I've checked it with Godot game engine and framless window maximization works properly there so it must be chromium/electron related issue.

**Comment by timfish** [comment]
I found a test laptop which hasn't been turned on for a while and can confirm that this issue does not occur on Windows 10 1703 so it was definitely introduced by the 1803 update.

**Comment by speedpacer** [comment]
I was experiencing this before 1803.

**Comment by timfish** [comment]
Official releases are:
```
Version 1703 (Creators Update)
Version 1709 (Fall Creators Update)
Version 1803 (April 2018 Update)
```

So this could have been broken by 1709. All I know for sure is that I can't reproduce this on 1703.

**Comment by speedpacer** [comment]
I was experiencing it on 1605 on one computer and 1709 on another.  After upgrading to 1803 on one, it went away but upgrading to 1803 on the other made no difference.

**Comment by ExtraCrafTX** [comment]
That's odd, I can't seem to find a single computer that doesn't suffer this issue. All of my friends using Windows have this issue, and had the issue before 1803, although I am not sure if it occurred before 1709. Maybe we are looking at this the wrong way? Could it be graphics? The computers I have checked this on all run Nvidia graphics, although it does seem unlikely that this would cause the issue. It might be worth a shot though.

**Comment by Astrych** [comment]
I have amd and integrated intel graphics: issue is hardware independent (on my computers).

> I don't have anything to test on right now, but I am curious as to what happens if you just call maximise again on the already maximised window?

Tried it - nothing actually. There is probably conditional check in native code preventing redundant action to occur.

Someone knows WinAPI? Here is the code responsible for window behaviour handling:
1. https://github.com/electron/electron/blob/master/atom/browser/native_window_views.cc
2. https://github.com/electron/electron/blob/master/atom/browser/native_window_views_win.cc

**Comment by timfish** [comment]
For frameless on Windows, the window [is not actually maximised](https://github.com/electron/electron/blob/42d173b3435e2153c143dc007de83df86dacc42f/atom/browser/native_window_views.cc#L426), the window is resized to appear like it's maximised. 

Looks like the screen bounds are fetched via calls into Chromium code.

**Comment by Astrych** [comment]
@timfish No, it is maximised [unless you use](https://github.com/electron/electron/blob/42d173b3435e2153c143dc007de83df86dacc42f/atom/browser/native_window_views.cc#L423):
```
thickFrame: false
```
in BorwserWindow constructor. What's interesting with this option our issue is not occurring so Chromium returns correct bounds in this case.

**Comment by Astrych** [comment]
Ok, [this is a call to libchromiumcontent.](https://github.com/electron/electron/blob/master/atom/browser/native_window_views.cc#L434)
Not sure is it possible to patch it on Electron side but the issue come from Chromium lib.

**Comment by Astrych** [comment]
Hm, my original workaround was working only in renderer process. When implemented in main process it stopped working at all. But even more interesting thing is that following version implemented in main process is working almost perfectly fine:

```javascript
    mainWindow.on("unmaximize", () => {
        if (process.platform === "win32") {
            setTimeout(() => {
                const bounds = mainWindow.getBounds();
                bounds.width += 1;
                mainWindow.setBounds(bounds);
                bounds.width -= 1;
                mainWindow.setBounds(bounds);
                console.log("TEST!");
            });
        }
    });
```

Almost because it works 7-9 out of 10 times. It's more or less random.

**Comment by Astrych** [comment]
Ok, This is working quite well. No white bar on top on every second maximization, no window down shifting on unmaximization.

```javascript
mainWindow.once("ready-to-show", () => {
    mainWindow.on("unmaximize", () => {
        if (process.platform === "win32") {
            setTimeout(() => {
                const bounds = mainWindow.getBounds();
                bounds.width += 1;
                mainWindow.setBounds(bounds);
                bounds.width -= 1;
                mainWindow.setBounds(bounds);
            }, 5);
        }
    });
});
```

Not sure what time will be best and whether it has to be in ready-to-show event. Tried only on one machine, requires more testing but it's promising ;)

**Comment by sethlu** [comment]
I spent some time earlier tracing where `frame: false` is applied 🤔 nothing really stands out to be an issue. It is probably a regression from win update?

![start_from_here](https://user-images.githubusercontent.com/3168941/43668351-4f820472-9731-11e8-910d-a95e7853a6a4.png)

**Comment by kegato** [comment]
As @V-ed [has posted at vscode](https://github.com/Microsoft/vscode/issues/52265#issuecomment-410531924) this issue has been fixed by the newest windows update `KB4340917`.

**Comment by Astrych** [comment]
Yes, I can confirm. The issue was there before new patch and after installing it the issue is gone. Probably Microsoft realised that it's easier to patch Windows than Chromium itself, hehe ;)

But there is still an issue with window positioning after every second Unmaximisation. Every second time window position is a little bit higher/lower.

**Comment by muxiaozi** [comment]
Thank you very much!😀

**Comment by vigneshbabu801** [comment]
Uncaught TypeError: Cannot read property 'send' of undefined 

**ipcRenderer.send('custom-restore');**

Help me out

**Comment by ahkohd** [comment]
> Uncaught TypeError: Cannot read property 'send' of undefined
> 
> **ipcRenderer.send('custom-restore');**
> 
> Help me out

IpcRenderer only works in the render process, be sure you are using it there.
