### ISSUE TITLE
Cookie headers lost when using protocol.interceptStreamProtocol()

### ISSUE THREAD

**Issue by ondrej** [electron/electron#13228]
* Electron Version: 2.0.0
* Operating System (Platform and Version): macOS High Sierra 10.13.4
* Last known working Electron version: N/A

**Expected Behavior**
When using protocol.interceptStreamProtocol(), all HTTP headers, including Cookie and Set-Cookie, are provided to the intercept callback (when a request is being made), and accepted by the intercept callback's callback (when a response is being accepted). This works for all requests, including requests made by Electron's &lt;webview&gt;.

**Actual behavior**
When the HTTP/S protocol is being intercepted, and when a Set-Cookie header is included in the headers object passed back to the callback inside StreamProtocolResponse, the Set-Cookie header never makes it to the &lt;webview&gt; (the page never receives and sets the cookie, and the cookie doesn't appear in Chrome Dev Tools).

**To Reproduce**
A repro is available at https://github.com/ondrej/electron-quick-start/tree/cookie-bug. Clone, then run npm start. The page will load github.com in a &lt;webview&gt;. If you try to sign in, GitHub will error out with "Cookies must be enabled to use GitHub." This happens even though the intercept callback passes on  all the headers it receives back to Electron, including the Set-Cookie header. In Chrome Dev Tools, the request will appear with all its headers, except, for some reason, the Set-Cookie header.

```sh
$ git clone git@github.com:ondrej/electron-quick-start.git -b cookie-bug
$ npm install
$ npm start
```
Thanks for your help!

**Comment by pwnsdx** [comment]
Bump, still present in 4.x

**Comment by shynome** [comment]
Bump, still present in v5.0.6

**Comment by likai757** [comment]
I also have the same problem, Someone is solved?

**Comment by likai757** [comment]
> * Electron Version: 2.0.0
> * Operating System (Platform and Version): macOS High Sierra 10.13.4
> * Last known working Electron version: N/A
> 
> **Expected Behavior**
> When using protocol.interceptStreamProtocol(), all HTTP headers, including Cookie and Set-Cookie, are provided to the intercept callback (when a request is being made), and accepted by the intercept callback's callback (when a response is being accepted). This works for all requests, including requests made by Electron's <webview>.
> 
> **Actual behavior**
> When the HTTP/S protocol is being intercepted, and when a Set-Cookie header is included in the headers object passed back to the callback inside StreamProtocolResponse, the Set-Cookie header never makes it to the <webview> (the page never receives and sets the cookie, and the cookie doesn't appear in Chrome Dev Tools).
> 
> **To Reproduce**
> A repro is available at https://github.com/ondrej/electron-quick-start/tree/cookie-bug. Clone, then run npm start. The page will load github.com in a <webview>. If you try to sign in, GitHub will error out with "Cookies must be enabled to use GitHub." This happens even though the intercept callback passes on all the headers it receives back to Electron, including the Set-Cookie header. In Chrome Dev Tools, the request will appear with all its headers, except, for some reason, the Set-Cookie header.
> 
> ```shell
> $ git clone git@github.com:ondrej/electron-quick-start.git -b cookie-bug
> $ npm install
> $ npm start
> ```
> 
> Thanks for your help!

Hello，Did you solve this issue?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by the-cobbler** [comment]
Unless we all do something wrong, set-cookie still does not work **V16.0.4**

**Comment by amitmisratas** [comment]
Bug continues in the current version. No way to pass cookies and other headers in https://www.electronjs.org/docs/latest/api/protocol 

There should be a way to pass page-headers in the callback function of session.protocol.interceptBufferProtocol

**Comment by carrytao** [comment]
Bug continues...

**Comment by felipe-linares** [comment]
having the same issue when trying to `interceptBufferProtocol`...

any update? sending proper headers not only allows for set-cookie but also things like content-type when the data being returned is compressed using something like gzip...

**Comment by jonnytest1** [comment]
why is this issue closed ? i still have the same problem in 21.0.1

**Comment by jonnytest1** [comment]
PS: for those that still need this you can try this workaround: https://github.com/electron/electron/issues/30717#issuecomment-1272550907
