### ISSUE TITLE
Extreme Blur in Electron 2.0.4 on Windows 10

### ISSUE THREAD

**Issue by MeikTranel** [electron/electron#13646]
* Electron Version: v2.0.4
* Operating System (Platform and Version): Windows 10 Build 17711.1000
* Last known working Electron version: v1.7.12

**To Reproduce**
After countless reproduces in VSCode, Atom, etc. @bpasero told me it's best to reproduce this with https://github.com/electron/fiddle

I don't know for sure yet, but i have a strong sense that this has something do with dpi scaling. On the machine that i'm currently using i have a dual monitor setup, with one being 2560x1440@165hz(With GSync) and the other one 1680x1050@60hz. 
Because the issue goes away if i use disable-gpu (which is a vscode param but i'm pretty sure this is just an electron option, right?), i should also include that this PC has a GTX 1080 and 6700k.

I reproduced this in all dpi setting combinations i know of; meaning application, system, system enhanced and also the new "Let windows fix blurry apps..." setting.

I'm sure you people know this better than me, but for completeness' sake here the instructions i was given in the original issue:

```sh
$ git clone https://github.com/electron/fiddle.git
$ cd fiddle
$ npm install
$ npm start
```
**Screenshots**
![2018-07-12_14-54-54](https://user-images.githubusercontent.com/6466560/42638324-95c7d272-85ed-11e8-9b17-b4a48f740e96.gif)

**Additional Information**

* Others have pointed out to try a stable windows version, which i understand, but since i experienced the issue since 17686 which is a RS4 PreRelease Build, i want to avoid reinstalling everything (even if chocolatey and a decent amount of provisioning experience made me pretty fast in this process), when it most likely has nothing to do with the windows build itself.
* Originally this was discovered in https://github.com/Microsoft/vscode/issues/51789

**Comment by bpasero** [comment]
Linking the relevant VSCode issue here: https://github.com/Microsoft/vscode/issues/51789

@felixrieseberg I think you also see this with Slack

**Comment by MeikTranel** [comment]
@bpasero should we also link the two other peeps having this issue, maybe ask them if they can reproduce this with fiddle, so we're sure we're all talking about the same thing?

**Comment by bpasero** [comment]
@MeikTranel yeah feel free to ping them

**Comment by MeikTranel** [comment]
Hey @xLobito / @Mehgugs, sorry to blindside you guys here, but it'd be super cool if you could try something to reproduce this issue. Just follow these steps (assuming you have npm installed of course):

```sh
$ git clone https://github.com/electron/fiddle.git
$ cd fiddle
$ npm install
$ npm start
```

The app that's popping up is an electron 2.0 app which should theoretically be super blurred for your when hovering things and stuff (see GIF in issue description).  
Based on  your comments in https://github.com/Microsoft/vscode/issues/51789 you seem to have had the same issue as me, but we're having a hard time nailing down what specs are required to reproduce this.
Can you reproduce the blur following these steps?

**Comment by bpasero** [comment]
Could be same as https://github.com/atom/atom/issues/17621 for Atom.

**Comment by xLobito** [comment]
I'm sorry about my long absence in here. I was working on something and didn't pay attention to Code @MeikTranel.

Well, I just updated to latest Code Insiders with Electron 2.0.5 and the result remains the same. I even tested with Electron using the guidance above and took some screenshots to confirm it. 

![captura1](https://user-images.githubusercontent.com/16466974/43361341-17655f62-929a-11e8-8b52-b1dc172f47c9.JPG)
![captura2](https://user-images.githubusercontent.com/16466974/43361342-1785aa9c-929a-11e8-9692-b090be91598d.JPG)

These screenshots were made with a Windows 10 / Compilation 17134. 

I will be around here if there's anything which I can help to.

**Comment by MeikTranel** [comment]
@bpasero provided us with a electron 3.0-beta.4 exploration build of vscode. Given that the exact repro is kind of hard to pinpoint it seems fixed on my end

![image](https://user-images.githubusercontent.com/6466560/43993513-04148366-9d8f-11e8-842a-716d1b4889dd.png)

**Comment by MeikTranel** [comment]
would it be possible to push the https://github.com/electron/fiddle to electron 3.0 beta? meaning the base app? 
Because electron fiddle starts applications with a given electron version but the code of the started dummy application doesn't reproduce the error. 
What does reproduce is the Hub fiddle app that spawns those apps. Can we get a build of that base fiddle app using electron 3 to verify the issue was fixed?

*yo dawg, this was hard to articulate* 😄

**Comment by mirosa25** [comment]
I can confirm this is still an issue with the latest stable build of Atom running 1.29.

**Comment by andrueandersoncs** [comment]
Hey guys, not sure if this is helpful but I would like to confirm seeing this issue as well. VS Code latest version.

**Comment by ripvannwinkler** [comment]
Still seeing the issue here as well.

![image](https://user-images.githubusercontent.com/130069/44680272-db421e00-aa02-11e8-8266-cb695ada8ea0.png)

**Comment by mirosa25** [comment]
I found this to be an issue with a driver on my system. Downgrading to version 397.64 fixed the issue for me.

**Comment by djmisterjon** [comment]
it the FXAA from nvidia
https://github.com/Microsoft/vscode/issues/51789#issuecomment-416868789

**Comment by MeikTranel** [comment]
Over at https://github.com/Microsoft/vscode/issues/51789 we verified 2 options for temporarily resolving the issue:

1. Set compatibility to Vista - resolved the issue at hand but seems to be draining the performance
2. Disable FXAA for code - resolved it for me without visible performance issues:
  a. Make sure to quit all vscode/fiddle instances before checking if it works.

I specifically checked with fiddle to confirm the bug here:
![2018-08-30_19-53-23](https://user-images.githubusercontent.com/6466560/44869671-7569c680-ac8e-11e8-99c9-69a29809c9f9.gif)

This is same fiddle app minute apart with the FXAA fix applied
![2018-08-30_19-52-04](https://user-images.githubusercontent.com/6466560/44869652-6be05e80-ac8e-11e8-9f9d-0be2f86655b8.gif)

I think we can all agree that having to disable FXAA isn't a proper solution but i assume its helpful nonetheless. Especially considering electron 3.X seems to resolve the issue and we haven't quite figured out why.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Sv443** [comment]
I am still experiencing this on Electron 4.2.10, both in Visual Studio Code (Insiders) and Discord (PTB). A restart of the app seems to temporarily fix it but it is very annoying because the thing you need to do most in those apps is read and write text and it becomes near impossible with the blurriness.

**Comment by xLobito** [comment]
@Sv443 

Well, the last insiders review I have is based on Electron 6, and disabling Anisotropic Optimization and FXAA antialising works perfectly. Without blurring or anything related. 

This fix is working since Electron 3, at least with Nvidia GPU (970 in my case).

**Comment by Sv443** [comment]
@xLobito I set my NVIDIA settings to "let applications decide". I don't want to force FXAA and Anisotropic Filtering off because I am also gaming on my PC. Based on this, Electron should automatically choose to disable them. But either way, those settings don't fix the issue for me.

**Comment by blueglyph** [comment]
For me, _any_ Electron-based application has blurred text which makes reading very hard and straining for the eyes.

I had this problem on GTX980 (that I don't have anymore) and RTX3070 including the latest drivers, on Windows 10 x86_64, without display scaling ("Scale and layout" set to 100% in display settings). The resolution is 1080p, the native resolution of the monitor.

For example the latest version of Visual Studio Code, which uses Electron 19.0.17.

The work-around by disabling FXAA works, but it's very annoying for other applications. Or I have to set this individually for each app using Electron.

I don't see the problem in Chrome or other applications in general.

**Comment by Luk164** [comment]
I have the same issue with ALL electron apps, most extreme seems to be the Epic Games Store:
![image](https://github.com/electron/electron/assets/30559213/f13bacc1-f627-48cd-baab-331f709dbe0f)
I did not edit that screenshot, that is how blurry it is!
