### ISSUE TITLE
Bug: 2 tray icons. App crashes when you destroy 1 tray icon

### ISSUE THREAD

**Issue by pjebs** [electron/electron#14036]
* Electron Version: latest (non beta)
* Operating System (Platform and Version): mac high sierrra
* Last known working Electron version: n/a

**Expected Behavior**
I have 2 independent tray icons. When I destroy one icon sometimes application crashes with this error:
`Electron[6667:281388] -[__NSCFString isMenuOpen]: unrecognized selector sent to instance 0x7fc7f35c28d0`

**Actual behavior**
It should not crash

**Comment by pjebs** [comment]
It happens when you try and destroy one of them using `Destroy()`

**Comment by pjebs** [comment]
```
const {app, Menu, Tray, BrowserWindow } = require('electron')

let tray1 = null
let tray2 = null
app.on('ready', () => {
    tray1 = new Tray("/Users/X/Developer/X/img/tray/trayTemplate.png")
    const contextMenu = Menu.buildFromTemplate([
        {label: 'Item1', type: 'radio'},
        {label: 'Item2', type: 'radio'},
        {label: 'Item3', type: 'radio', checked: true},
        {label: 'Item4', type: 'radio'}
    ])

     tray1.on('click', () => {
    tray1.popUpContextMenu(contextMenu)
  })



      tray2 = new Tray("/Users/X/Developer/X/img/tray/tray_win_no_internetTemplate.png")
    const contextMenu2 = Menu.buildFromTemplate([
        {label: 'Item1', type: 'radio'},
        {label: 'Item3', type: 'radio', checked: true, click () { tray2.destroy() }} // Crashes application
    ])

    tray2.setContextMenu(contextMenu2)



    let win = new BrowserWindow();
    win.loadURL('https://www.youtube.com');

    setInterval(() => { console.log('test'); }, 1000);
})
```

**Comment by pjebs** [comment]
Destroying the second tray crashes the application. 99% no logs. no warnings nothing. 1% of the time `Electron[6667:281388] -[__NSCFString isMenuOpen]: unrecognized selector sent to instance 0x7fc7f35c28d0`

**Comment by pjebs** [comment]
@fantasticsid have you experienced this issue?

**Comment by pjebs** [comment]
I feel this may be a regression because I can't remember this happening 3 months ago.

**Comment by pjebs** [comment]
These look vaguely related:
https://github.com/electron/electron/issues/9982
https://github.com/electron/electron/issues/12862
https://github.com/electron/electron/issues/13556
https://github.com/antonio-ramadas/electron-tray-app-crash
https://github.com/electron/electron/issues/6956

Not 100% sure if they produce the same error message as mine.

**Comment by ckerr** [comment]
By 'latest nonbeta' can you confirm you mean the literal latest nonbeta version 2.0.7, rather than the latest stable version in the 1.7 or 1.8 branches?

**Comment by pjebs** [comment]
2.0.6

**Comment by pjebs** [comment]
https://github.com/electron/electron/issues/13556

**Comment by pjebs** [comment]
With: ELECTRON_ENABLE_STACK_DUMPING=true
```
Received signal 11 <unknown> 000000000000
 [0x000104be9fdc]
 [0x000104be9ed1]
 [0x7fff76488f5a]
 [0x000000000002]
 [0x000104a24059]
 [0x7fff4b9deeb7]
 [0x7fff4b9dedb2]
 [0x7fff4bfc246f]
 [0x0001049e7e9b]
 [0x7fff4b8228b5]
 [0x000104bc430e]
 [0x000104bc2d0c]
 [0x000104bd9183]
 [0x000104e4560f]
 [0x000104e45430]
 [0x000104e47ab2]
 [0x000104e4148c]
 [0x000104d8a660]
 [0x00010698a8b4]
 [0x000104d89474]
 [0x000104932e84]
 [0x000104928f26]
 [0x7fff7617a015]
[end of stack trace]
```
(not sure what you can learn from it)

**Comment by miniak** [comment]
Fixed by 
https://github.com/electron/electron/pull/14347

**Comment by miniak** [comment]
Will be available in 2.0.9 when it’s released
https://github.com/electron/electron/compare/v2.0.8...2-0-x

**Comment by pjebs** [comment]
@miniak This issue is not fixed.

**Comment by maxpavlov** [comment]
Still not fixed, if the main window is Maximized, Tray.destroy will simply throw an error.
