### ISSUE TITLE
Dialog box message not read out by screen reader

### ISSUE THREAD

**Issue by isidorn** [electron/electron#14234]
* Electron Version: 2.0.7 and 3.0.0-beta.6
* Operating System (Platform and Version): Mac OS High Sierra 10.13.6
* Last known working Electron version: none

**Expected Behavior**
Dialog box message should be read out by Voice Over

**Actual behavior**
Dialog box message is not  read out by Voice Over

**To Reproduce**
Turn on Voice Over and start this starter electron app. Notice how the message 'hello there' in the dialog box is not read out by voice over. 
https://gist.github.com/isidorn/326fd5a14ccb7eec19f7e5a820327143

Original issue in vscode https://github.com/Microsoft/vscode/issues/55585

**Comment by Loiyyacoub** [comment]
After reproducing the issue . I decided to post a work around for the issue as the documentation did not fully explain the voice over commands .  Using "**npm install say**" you are able to get the dialogue to speak by typing const say = require('say') at the beginning of the program and then typed say.speak('Hello there') after "setTimeout(() => dialog.showMessageBox(mainWindow, {message: 'hello there'}), 2000);"

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by isidorn** [comment]
I can reproduce this with Electron 4.2.7 and with Electron 6.0.0.

**Comment by christopherpross** [comment]
Hi,
I can also reproduce this issue in electron 6.0.

**Comment by christopherpross** [comment]
see also #12893

I think the problem is, that we don't notify voiceover, that the focus has changed. So, somewhere in the code, where the dialogs are rendered as child, we have to notify voiceover, that there is a change. I don't know which notification would be the best, but I think this cout the quickest and simpliest solution.
Hopefuly someone can implement this, I cannot objective-c, otherwise I would be try to do that.
When someone wants to implement, here you can read more about accessibilityNotifications:
[](https://developer.apple.com/documentation/appkit/nsaccessibilitynotificationname?language=objc)

This bug is anoing, so big thanks to the guy who to try to fix this.

**Comment by deepak1556** [comment]
@codebytere this is fixed in electron 9, need to track down the fix to backport to 7 and 8.

**Comment by isidorn** [comment]
@deepak1556 that would be fantastic.

**Comment by deepak1556** [comment]
The issue is present for sheet dialogs in all versions

**Comment by kastwey** [comment]
Hi, Any news on this? I just developed an application for MAC, and when I open a open folder dialog,  VO is unable to read the dialog content until I restart VO.
Any suggested solution?

Thanks!

Kind regards,

Juanjo.

**Comment by kastwey** [comment]
Sorry, guys, but with Electron version 9 I still have this problem with folder-opening dialogs. It's true that with the MessageBox dialogs VoiceOver does read the content, but when I open a folder choice dialog, the VoiceOver focus is still on the web, it doesn't detect the opening of the new window.
The behavior is very inconsistent, because if I move with the tab (system focus), VoiceOver reads parts of the dialog. However, if I use VO left arrow or right arrow (to move through the objects with the VoiceOver cursor), the screen reader reads only the website that opened the dialog, but it does not know that there is an open dialog.
If I restart VoiceOver while still in the application, then it does detect the dialog and reads it correctly.

**Comment by isidorn** [comment]
@kastwey thanks for letting us know.
Yeah we should ideally look into this if possible.

**Comment by kastwey** [comment]
Hi,

Any progress on this?

Thanks!

Kind regards,

Juanjo.

**Comment by kastwey** [comment]
Hi, guys. Is there an estimated date to investigate this issue? This bug is very serious on the Mac, since VoiceOver users cannot use the file and folder opening dialogs. Please, we need this fixed as soon as possible. I would help with this issue myself, but my knowledge of Electron is not good enough at all.

Thanks in advance.

Kind regards.

**Comment by kastwey** [comment]
Hi!
Please, any progress with this?

Thanks.

**Comment by kastwey** [comment]
Hello!
This is my fourth comment and there is no answer... And I still can't use the features to open files and folders on MAC with VoiceOver.

Can you please give me an update on this?

Thank you.

**Comment by isidorn** [comment]
I confirm this is indeed fixed in Electron 11.
