### ISSUE TITLE
BrowserView background loses alpha transparency (intermittent)

### ISSUE THREAD

**Issue by krisdages** [electron/electron#16212]
* Output of `node_modules/.bin/electron --version`: v3.0.13
* Operating System (Platform and Version): Ubuntu Linux (X11), mac OS (most recent versions)

**Expected Behavior**
Contents should be always be visible behind a BrowserView with a partially transparent background color.

**Actual behavior**
Occasionally, when showing a BrowserView, the transparency will be lost and the BrowserView's background will be opaque.  Destroying and recreating the BrowserView restores the proper alpha.

**To Reproduce**
*Create a BrowserView, use setBackgroundColor() with a partially transparent color.  
Repeat until the issue occurs:
* Set the bounds of the BrowserView to the area of the window below and show it.
* Hide the BrowserView

I'll try and create a repo for reproducing this more easily. Just wanted to post it first and see if this is a known problem.

**Comment by Timothee** [comment]
FWIW, I see this issue with Electron 4.2.0 on macOS.

**Comment by Timothee** [comment]
I created this test app that reproduces the issue: https://github.com/Timothee/electron-16212

For me, it happens as soon as the web content in the `BrowserView` is reloaded. Once it is, the only way to fix the transparency seems to be to recreate the `BrowserView` altogether.

The test app uses Electron v5.0.1 but it also happens with 4.2.0.

**Comment by Timothee** [comment]
It seems to affect not just reloading the page, but interacting with `window.location`. E.g., running `window.location = window.location.href` in the console triggers the issue.

**Comment by krisdages** [comment]
Thanks, @Timothee!  I was at a loss as to why the demo app I made to try to repro the issue never produced the same behavior I was seeing in my production app.

**Comment by miaowing** [comment]
I try to set `transparent: true` and `backgroundColor: '#00FFFFFF'`，the alpha is always available.

**Comment by Timothee** [comment]
@miaowing interesting. This doesn't work for me. (tried in the test app I linked to, above)

**Comment by lincolnthree** [comment]
I'm also having this issue. Tried versions 4.0.5, 5.0.7, and 6.x and all have various issues either never displaying transparency, failing to load html (it gets rendered in a pre-tag instead) or in the case of 6.x, the last window created always hangs with 100% CPU usage, though transparency seemed to have worked a little more reliably there.

**Comment by ChALkeR** [comment]
_Closing_ devtools on a BrowserView seems to trigger transparency loss.
Opening devtools is fine, but closing breaks it.
Reopening devtools, or removing-readding browserview to the parent window, _does not_ help.

**Comment by hovancik** [comment]
I am on Linux and Electron 12 and with `transparent: true` and some `backgroundColor` and I never see transparency working.

**Comment by mckravchyk** [comment]
It used to be that closing dev tools triggered transparency loss. After upgrading from Electron 13 to Electron 15, it seems like the transparency loss is permanent, at least on Linux and it completely breaks my app.

I will do some more tests and follow up or open a new issue.

**Comment by ChALkeR** [comment]
Add `transparent: true` to `webPreferences` too, not just to the window options to make transparency work.
That is an undocumented API change from https://github.com/electron/electron/pull/30777/files#diff-261075c0abf5bfd33be70313bcd3699da9b1222b6f27df0e8294fc63789f160bR1389-R1391

**Comment by ChALkeR** [comment]
> It used to be that closing dev tools triggered transparency loss in a BrowserView

That is apparently fixed now btw!

**Comment by mckravchyk** [comment]
> Add transparent: true to webPreferences too, not just to the window options to make transparency work.

In earlier versions, I did not set any transparency options on BrowserView. It just worked that the background of content (body element) was made transparent with CSS.

Anyway, I went and applied those options you mentioned in webPreferences and BrowserView options (against TypeScript suggestions) and it did not really work. To be clear, I did set it on BrowserView and not BrowserWindow

I will do some more tests and research.

By the way, there seem to be many recent issues about setBackgroundColor, perhaps this is all related. https://github.com/electron/electron/issues?q=setBackgroundColor

**Comment by mckravchyk** [comment]
@ChALkeR It does indeed work, thank you. I made a silly mistake and applied those options on the wrong BrowserView. I only had to add `transparent: true` to webPreferences, other options were not required (it was enough that the background of the HTML document inside the view was made transparent with CSS).

**Comment by theolivenbaum** [comment]
Not sure if related, but on 15 and 16, calling setBackgroundColor on a transparent window with vibrancy enabled on macOS would disable the transparency and render a white background instead.

**Comment by theolivenbaum** [comment]
Actually not even that. Still having the intermittent loss of transparency without further calls to window.setBackgroundaColor

**Comment by hovancik** [comment]
Mentioned fix with adding `transparent` to `webPreferences` on electron 16 does not help me on KDE Debian.

**Comment by hovancik** [comment]
SO maybe this helps somebody: with upgrade of electron, I hade to change the format of hex color. I used to have #AARRGGBB but I now need #RRGGBBAA. 

Here's how create the value: `ORIGINAL_HEX + Math.round(OPACITY * 255).toString(16)`

**Comment by hovancik** [comment]
still affects me

**Comment by DanielMcAssey** [comment]
Getting this on 21.3.3 as well

**Comment by hovancik** [comment]
Yep, still getting this on `   "electron": "^22.2.0",`

**Comment by hovancik** [comment]
Still have this intermittently on 25.

**Comment by waterbang** [comment]
I lost the background when the BrowserView was set too small

**Comment by spamshaker** [comment]
will it be fixed?

**Comment by fzdwx** [comment]
bump

**Comment by fzdwx** [comment]
In my experiment today, the transparency was lost in the development environment, but after packaging and running, the transparent function can be used normally.

**Comment by hovancik** [comment]
bump

**Comment by lincolnthree** [comment]
bump

**Comment by hovancik** [comment]
man I would ban those bots :)
