### ISSUE TITLE
Switching between menus in the menu bar causes flickering if dark theme (Ambiance) is selected

### ISSUE THREAD

**Issue by katiamoklokova** [electron/electron#18184]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.1.3, 5.0.0-beta6
   
* **Operating System:** Ubuntu 18.04 x64/Gnome; Ambiance theme
   
* **Last Known Working Electron version:**: 3.1.7
   

### Expected Behavior

Switching between menus in the menu bar shouldn't cause flickering.

### Actual Behavior

Menus flicker when switching between them with dark theme selected.

### To Reproduce

1. Install an Electron application with menu bar
2. Make sure dark theme (Ambiance, which is 18.04 default theme) is selected
3. Switch between menus in the menu bar

### Screenshots

![flickering](https://user-images.githubusercontent.com/20443967/57246377-f7ff0e80-6ff1-11e9-9480-33a9ca004bf7.gif)

**Comment by nornagon** [comment]
I'm able to reproduce this in a Ubuntu 18.04 VM (Parallels). It seems to also happen with context menus, though the effect is less obvious. I don't see the same behaviour in the Chromium 73.0.3683.103 snap.

**Comment by nornagon** [comment]
I also see this occurring on 3.1.9, but with a transparent background on the menus rather than a white background:

![Electron 3.1.9 reproduction video](https://user-images.githubusercontent.com/172800/57250105-84fa9580-6ffb-11e9-85c7-2ae044f31d0f.gif)

**Comment by nornagon** [comment]
The the menu flickers with a transparent background in 3.1.9 and earlier, and with a white or grey background in versions after 4.0.0-beta.1.

**Comment by electron-triage** [comment]
@katiamoklokova is this still an issue on electron version 6 or later?

**Comment by katiamoklokova** [comment]
Yes, still happens in Electron 8.

**Comment by charbelnicolas** [comment]
This happens on the latest VS Code too...

**Comment by GitFiend** [comment]
This is fixed for me in GitFiend after updating it to use electron 8.1.1. Still had the issue in 8.0. Tested on Ubuntu 18.04 with a dark theme and dark menus.

**Comment by marvkal** [comment]
Doesn't seem to be Ubuntu specific, I have the same issue on Arch with XFCE and any skin (dark skin just makes it much more obvious it's happening).
![VSCode ](https://user-images.githubusercontent.com/49322655/79304746-8b6ae000-7ee1-11ea-8057-ec86182ce016.gif)

**Comment by charbelnicolas** [comment]
This is already fixed on VS Code Exploration builds, give it a spin. All we have to do is wait....

**Comment by kakawait** [comment]
> This is already fixed on VS Code Exploration builds, give it a spin. All we have to do is wait....

Could you please link where can I download the exploration build, since there is many I'd like to be sure using correct one

**Comment by charbelnicolas** [comment]
> > This is already fixed on VS Code Exploration builds, give it a spin. All we have to do is wait....
> 
> Could you please link where can I download the exploration build, since there is many I'd like to be sure using correct one

https://github.com/microsoft/vscode/issues/94074#issuecomment-607079209

**Comment by twitharshil** [comment]
Not able to reproduce this issue on electron v8.5.0

**Comment by karevn** [comment]
This issue still exists on latest Manjaro / VSCode July 2020 installed from AUR

**Comment by madasebrof** [comment]
This is still an issue. 

Just did a fresh install of 20.04. Both VS Code and Atom have menu blinking (e.g. background flashes white for a split second when you hover over a menu item or right-click for a context menu). Very distracting! Totally doesn't happen on OS X.

Also, I downloaded all the exploration builds, etc. Still has menu blinking. Have VS Code & Atom just not updated to a more recent version of Electron?

- Running Ubuntu 20.04
- Proprietary Nvidia Drivers
- RTX-2060 card

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by abnerlee** [comment]
still happens on v9.4.4 (https://github.com/typora/typora-issues/issues/4289)

**Comment by bjorn** [comment]
This still happens on Electron 11.3.0. Probably this bug reappeared at some point?

https://user-images.githubusercontent.com/531764/116678929-3691ee80-a9aa-11eb-9ed5-b992b0b11f57.mp4
```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-50-generic snap
```
