### ISSUE TITLE
Notification "click" event handler is not executed on Windows

### ISSUE THREAD

**Issue by olessavluk** [electron/electron#18746]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10 (1809) 
* **Last Known Working Electron version:**
  * v0.36.9 according to https://github.com/electron/electron/issues/4766

### Expected Behavior

Notification "click" event callback will be executed for the following snippet
```js
const n = new Notification('Title', {
    body: 'Lorem Ipsum Dolor Sit Amet'
  });

  // this is never executed on Windows 10
  n.on("click", () => {
    console.log('Notification clicked')
    app.quit();
  });

  n.show();
```

### Actual Behavior

Nothing happens

### To Reproduce
Example repo - https://github.com/olessavluk/notification-issue
1. `git clone git@github.com:olessavluk/notification-issue.git`
2. `yarn`
3. `yarn make`
4. go to `out\make\squirrel.windows\x64\` and run `notification-issue-1.0.0 Setup.exe`
5. wait 5 sec, and click on notification when you see it
6. After clicking on Notification app should close itself

### Additional Information
Same issue when using HTML5 Notification API from renderer process
Works fine on OS X

**Comment by codebytere** [comment]
This is using the HTML5 notification syntax in the main process. This should be working correctly with correct syntax and build instructions on Windows.

**Comment by olessavluk** [comment]
Hi @codebytere, thanks for the reply!

Syntax is correct, because it works perfectly fine on OS X (and [Notification module can be used from the main process](https://electronjs.org/docs/api/notification)). I have also tried using HTML5 Notification API from renderer process using `.onclick` syntax - issue is still there, handler never got called.

Build instructions for windows is fine because notifications are displayed, but **onclick handler is never executed**.

So looks like this is electron issue. If so, could you please reopen this issue?

**Comment by MarshallOfSound** [comment]
@olessavluk have you set your app use model is correctly on your application?  Do you have a shortcut to your app in the start menu? Does that shortcut have the right app user model id?

My notifications work locally when the app is configured right, you have to jump through hoops to make Windows happy.  This, as far as I currently understand, is not a big in electron

**Comment by olessavluk** [comment]
Hi @MarshallOfSound,
yes, I believe shortcuts are configured properly because notifications are shown, the **only issue is that "click" event handler is not executed on Windows** (however it works fine on OS X)

There is example repo attached, you can build and run it (it's based on awesome electron-forge)

**Comment by olessavluk** [comment]
This issue is caused by https://github.com/electron/windows-installer/issues/296
Downgrading to `electron-winstaller@2.7` helped

**Comment by ragauskl** [comment]
In my case issue was solved by keeping reference to notification object (EventEmitter) outside of function scope as ["registering an event listener all by itself does not keep it from being garbage collected"](https://stackoverflow.com/questions/38449262/in-node-js-does-listening-to-an-eventemitter-create-a-reference-to-it)

**Comment by U-OK** [comment]
Hi all! I also encountered this problem and it frayed a lot of nerves. The click handler worked in dev mode, but did not work after building in prod.
But I found the solution. Maybe it will be helpfull for you.
The problem is that missing between your appId, so notification and click on it don't have connection with your application.

How to resolve this isuue: 
In your `forge.config.js` find your appBundleId or set it:
```
packagerConfig: {
    appBundleId: 'my.app.id',
    ...
}
```

And then in main process you should write:
```
app.on('ready', () => {
    if (process.platform === 'win32') {
      app.setAppUserModelId('my.app.id');
    }
    createWindow();
    createNotification();
  });
```

After that, your notify click listner will be work not only in dev, but in prod! 
I hope my solution was useful to you.
