### ISSUE TITLE
webSecurity won't disable same origin

### ISSUE THREAD

**Issue by danbulant** [electron/electron#18940]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.4
* **Operating System:** Windows 10 Latest official build x64, Linux 5.8 (Manjaro)

### Expected Behavior
By disabling webSecurity allowing js to edit iframe's variables
### Actual Behavior
Console saying 'Blocked cross-origin request to frame'
### To Reproduce
in main.js disabled webSecurity
`  win = new BrowserWindow({
    width: 800,
    height: 600,
    frame: true,
    webPreferences: {
      nodeIntegration: true,
      nodeIntegrationInWorker: true,
      webSecurity: false
    }
  })`
try to edit variables in iframe with id 'frame'
`document.getElementById("frame").contentWindow.settingMenuItemValues[0] = arg;`
(editing variable inside frame works.)

### Console (chrome DevTools)
Uncaught DOMException: Blocked a frame with origin "file://" from accessing a cross-origin frame.

**edit:**
Tested on Manjaro linux. As per comments, this looks like it's affecting all platforms ([peteringram0 has it on OSX & Linux](https://github.com/electron/electron/issues/18940#issuecomment-512734798).

**Comment by Joshua-Smith** [comment]
Is there a workaround? This is a blocking issue for me (in my case, the IFRAME cannot access window.parent, even though they are both coming from the same file:// root), but it sounds like the same underlying defect.

**Comment by hunterbdm** [comment]
> I found a workaround for this in another bug report, which appears to be the same issue.
> 
> app.commandLine.appendSwitch('disable-site-isolation-trials')
> 
> Solved the issue for me.

Thanks, this also fixed an issue I had that caused content in iframes to be loaded incredibly slow.

**Comment by peteringram0** [comment]
Also getting this issue! Can you adjust your labels please this is also happening on OSX & Linux.

**Comment by peteringram0** [comment]
Tested and this seems to have been fixed on 6.0.0

**Comment by mceIdo** [comment]
@peteringram0  just had this issue with 6.1.7.
Only thing that solved it was @Joshua-Smith solution - adding `app.commandLine.appendSwitch('disable-site-isolation-trials')`

**Comment by matteoturini** [comment]
I can confirm this bug also happens on mac.

**Comment by shuiRong** [comment]
reproduce on mac too. 
```
~ » electron -v 
v10.1.5
```

the workaround above is useful and saves my day.

**Comment by m4heshd** [comment]
This is still an issue on `electron v12.0.0`.

> `app.commandLine.appendSwitch('disable-site-isolation-trials')`

This works but unfortunately it somehow makes the PDF viewer completely non-functional. That in my case is a deal-breaker. Any other solutions?

**Comment by m4heshd** [comment]
Keep repeatedly running into this issue. Even with `app.commandLine.appendSwitch('disable-site-isolation-trials')`.

![image](https://user-images.githubusercontent.com/6711514/123601997-eef6da00-d815-11eb-88cc-e35dd32f1ed9.png)

Having to write an application around bugs is really tiresome. Still no update regarding this? Can anybody confirm if this issue still present in v13 too?

**Comment by nornagon** [comment]
`disable-site-isolation-trials` makes this work in all currently-supported versions of Electron, as far as I can tell.

Here's an automated test Fiddle: https://gist.github.com/ff2f8ab8d1ef1ddcc394de1e892015ad

**Comment by m4heshd** [comment]
@nornagon It definitely is still there. Just upgraded to Electron v13 and tested with `app.commandLine.appendSwitch('disable-site-isolation-trials')`. Same result.

![image](https://user-images.githubusercontent.com/6711514/123921829-0dd7a680-d9a5-11eb-9d3c-2ca82f908743.png)

So I found out that it happens if one source is `http://` protocol and the other is `file://`. But it shouldn't behave like that right? Read a lot about it but it's not clear about this matter. If it's the default behavior that really beats the purpose of Electron being a "desktop" framework (when web security is turned off) at least from my experience. Because I might need one source from a locally running server and one source from a file.

Here's a [minimal repro](https://github.com/m4heshd/electron-cors-issue) if you need. It was difficult to do with a fiddle. I tried to make it as close as possible with my scenario. You'll probably suggest me to use the web server in this case too but the real scenario is a bit complicated than that. Let's just say I want the exact functionality written in there to work. Run `electron:serve` and you'll get the error. If you build with `electron:build` it'll work perfectly fine since both sources will be `file://`.

It's really sad because even if `app.commandLine.appendSwitch('disable-site-isolation-trials')` worked properly, it won't solve my issue since it completely breaks the PDF plugin which my application heavily relies on. I'm moving on from this issue and going to invest my time on an alternative logic for my application. Just wanted to let you know that this is an issue. At least for me it is.

**Comment by nornagon** [comment]
@m4heshd there's no way that a repro with a 1.2MB package-lock.json is "minimal" 😭

but I hear you that this seems particular to `http:` <-> `file:` interop, I'll see if I can tweak the fiddle I produced to exercise that case.

**Comment by m4heshd** [comment]
> @m4heshd there's no way that a repro with a 1.2MB package-lock.json is "minimal" 😭

Haha I agree. Tried to mirror the flow from my production app, then got lazy and ended up using pretty much all the deps from the original app. I'll try to build a different repro with an actual "minimal" condition.

**Comment by nornagon** [comment]
Hm, I still can't reproduce this with a Fiddle. The [first fiddle](https://gist.github.com/ff2f8ab8d1ef1ddcc394de1e892015ad) I posted loads an `https:` iframe from a `file:` parent page, and the parent is successfully able to access the child. Here's [another fiddle](https://gist.github.com/56eda346441363c5bc340b8f575cdbc3) which goes the other way; it loads a `file:` iframe from an `http:` parent, and the parent is still successfully able to access the child. Here's a [third fiddle](https://gist.github.com/04556f62ea60ad9f69022f609ee6f630) that loads one `http:` page from another `http:` page, and that works too.

Oh, I just see that your example is using `window.open` not `iframe`?

**Comment by m4heshd** [comment]
> Oh, I just see that your example is using `window.open` not `iframe`?

Yup. I meant to point it out on your original fiddle but completely forgot. I did try a few fiddles with `window.open()` combined with `http://` and `file://` mix but those never quite produced the same result. So that's why I finally had to settle with that humongous "minimal" repro. 😁

**Comment by nornagon** [comment]
Gotcha. Thanks for the clarification, looking forward to seeing a smaller repro if you can manage it! Appreciate your cooperation 💕

**Comment by m4heshd** [comment]
@nornagon [Here you go](https://github.com/m4heshd/electron-cors-repro). Hope this'll do the trick. Electron is the only dep. `start:file` works and `start:http` fails.

**Comment by nornagon** [comment]
Gotcha. Here's an even smaller fiddle which reproduces the issue, + is also automatically testable (i.e. exits with `1` if the test fails, `0` if it passes): https://gist.github.com/10465071dd6fcd731eabfcc4608ff87a

I've opened a new issue to track this: https://github.com/electron/electron/issues/29970

**Comment by m4heshd** [comment]
Perfect. Hoping for the PDF plugin issue to be resolved in the same timeline as well. 😏🤞🏽

**Comment by SantiiRepair** [comment]
The previous answers do not work now, what happened?
