### ISSUE TITLE
systemPreferences.isDarkMode always returns false on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by alicerunsonfedora** [electron/electron#19009]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * macOS 10.15 Developer Beta 2 (19A487l)
* **Last Known Working Electron version:**
  * 5.0.x (worked before Catalina)

### Expected Behavior
`systemPreferences.isDarkMode` on macOS 10.15 Catalina should report whether it's in dark mode or not, even when set to Auto Mode (based on time of day). Electron 5.0.6 fixed some of the issues from #18913 , but isn't working correctly.

### Actual Behavior
`systemPreferences.isDarkMode` is always reporting to be false.

### To Reproduce
Repository: https://github.com/hyperspacedev/hyperspace

```sh
$ git clone https://github.com/hyperspacedev/hyperspace -b catalina-vibrancy
$ npm install
$ npm run electrify
```

### Screenshots
<img width="1440" alt="Screen Shot 2019-06-27 at 08 23 18" src="https://user-images.githubusercontent.com/13445064/60265918-e7ae3600-98b4-11e9-8519-6a114ff52790.png">
Dark mode reports to be `false` here and is expected because it's in light mode.

<img width="1440" alt="Screen Shot 2019-06-27 at 08 23 33" src="https://user-images.githubusercontent.com/13445064/60265936-f5fc5200-98b4-11e9-98f7-caba828f9e2a.png">
Dark mode reports to be `false` here as well since, at the time of Auto Mode, it shouldn't be in dark mode.

<img width="1440" alt="Screen Shot 2019-06-27 at 08 23 25" src="https://user-images.githubusercontent.com/13445064/60265976-0b717c00-98b5-11e9-8d5a-6a7b7ee50c58.png">
However, dark mode reports to be `false` here, even though that isn't true.

### Additional Information
I speculate that the name of the dark appearance might have changed.

**Comment by MarshallOfSound** [comment]
@codebytere is working on a fix for a related issue which I believe is fundamentally the same cause 👍

**Comment by DeerMichel** [comment]
#19013 didn't seem to fix the issue. I can still reproduce it on Catalina under v6-beta.12 where it got merged. However on master it's working - which backport is missing?

**Comment by MarshallOfSound** [comment]
@DeerMichel it's not a question of which backport is missing.  It's a question of the target SDK.  You'll be building master locally against 10.14 and we release against 10.13.

This results in difference of behavior around macOS's dark mode apis. The linked PR changes it to not affect Mojave, in this case the only way to make this work is to either target 10.14 or to opt in to dark mode with NSRequiresAquaSystemAppearance=false

This probably requires a wider discussion before Catalina hits stable, I've also raised a TSI with apple to see if theirs a way to get this info with opting in to OS dark mode settings

**Comment by fabiospampinato** [comment]
I can reproduce this on Mojave as well, I believe it was working properly on Electron v5.0.5, but it broken on v5.0.6.

**Comment by MarshallOfSound** [comment]
@fabiospampinato It'll be fixed on Mojave in `5.0.7`

**Comment by whyboris** [comment]
Can confirm `systemPreferences.isDarkMode()` returns `false` on Mac OS Mojave `10.14.5` & Electron `5.0.6` 👌 
Thank you to developers on the _Electron_ team for the awesome work 🙇 
Thank you for the upcoming fix https://github.com/electron/electron/issues/19009#issuecomment-508900680

**Comment by whyboris** [comment]
`5.0.7` released 3 hours ago: https://github.com/electron/electron/releases/tag/v5.0.7
Waiting for the `npm` tags to be pushed 😅 🙇 🙏

**Comment by sofianguy** [comment]
fixed in https://github.com/electron/electron/pull/19013

**Comment by gaodeng** [comment]
this is still broken with electron 6.0.10

**Comment by alicerunsonfedora** [comment]
@gaodeng It appears the bug exists only when you're running from NPM, but after I build it, it still returns the correct values.

**Comment by dgmid** [comment]
still broken in 6.0.11. As confirmed by @alicerunsonfedora it's only when running from NPM, but still - very annoying when you need to see what the app looks like in both light & dark modes.

**Comment by s00500** [comment]
Form me it always returns false, no matter if build or serve, in electron 6.0.11, I am using webpack and electron builder for the build

**Comment by nathanlesage** [comment]
Still not working, using Electron 6.0.12 on Catalina.

**Comment by s00500** [comment]
This should fix it, although I have not tested it, can somebody check this? It is interesting that this patch has been done twice before but never made its way into master...

https://github.com/electron/electron/compare/master...s00500:patch-1

**Comment by gpalomar** [comment]
Same here! Using 6.0.12 in Catalina. Any news? Thanks!

**Comment by fcjr** [comment]
@s00500 
> Form me it always returns false, no matter if build or serve, in electron 6.0.11, I am using webpack and electron builder for the build

If you are using electron-builder to make it work on build you have to set the following settings in your electronbuilder config file:
```
 "mac" {
    ...
    "darkModeSupport": true,
    "extendInfo": {
        ...
        "NSRequiresAquaSystemAppearance": false,
    }
}
```
See: https://electronjs.org/docs/tutorial/mojave-dark-mode-guide#mojave-dark-mode

This however only solves it on build, still broken for me on run.

**Comment by fcjr** [comment]
> @fcjr This has nothing to do with build; it's during run time — the app itself compiles. Besides, Electron Builder automatically sets this value to false. Apparently, Apple changed the API to access that setting, so the API method returns false everytime on Catalina, but is probably still working on Mojave.

@nathanlesage Ah yes, I missed the setting of NSRequiresAquaSystemAppearance in Electron Builder so setting NSRequiresAquaSystemAppearance is redunant in that case. (I've updated my comment to reflect)  It is however a build issue as running via `electron .` (aka via command line) runs your ui through the electron .app stored in `node_modules/electron/dist/Electron.app` which does not have NSRequiresAquaSystemAppearance set.  This is why it will work when you build but not when you run as @alicerunsonfedora and I have run into.  setting this value in `node_modules/electron/dist/Electron.app/Contents/Info.plist` would resolve this issue.  Maybe this should be set by default?

**Comment by nathanlesage** [comment]
…do you mean once we set "darkModeSupport" to true the dark mode works? If that's the case, a documentation update on Electron would be necessary. But I have no time to test it myself right now … can you confirm?

**Comment by fcjr** [comment]
@nathanlesage by setting darkModeSupport in your Electron Builder config, it adds
```
<key> NSRequiresAquaSystemAppearance</key>
<false/>
```
to your apps Info.plist which enables SystemPreferences.isDarkMode() to return the proper value even on Catalina.  The issue that I am having (and I believe @alicerunsonfedora is having as well) is that when running via `electon .` electron is ran via the `Electron.app` in your projects `node_modules/dist` folder.  This `.apps` plist does not have `NSRequiresAquaSystemAppearance` set to `false` so SystemPreferences.isDarkMode() always returns false.

**Comment by nathanlesage** [comment]
I can confirm that this very key is set to "false" in my application's built plist-file, and it still doesn't work.

**Comment by s00500** [comment]
@fcjr Cool, yes setting the entry in electron builder solved id for me on the build. Still the main executable needs the key as well to work for development

**Comment by p4rse** [comment]
After I upgraded from Mojave to Catalina, ` systemPreferences.isDarkMode()` was returning false in dark mode.

I fixed it by adding/setting ` NSRequiresAquaSystemAppearance` to false in Electron.app's info.plist file.

```
<key>NSRequiresAquaSystemAppearance</key>
<false/>
```
Go to `/path/to/your/electron/app/node_modules/electron/dist/Electron.app` then right click, and click on "Show Package Contents":
<img width="830" alt="Pasted_Image_28_10_2019_22_56" src="https://user-images.githubusercontent.com/32100313/67717527-8c14c600-f9d6-11e9-8cee-ebe637ef6e12.png">

Afterwards, open Contents folder and you will see info.plist file:
<img width="426" alt="Contents" src="https://user-images.githubusercontent.com/32100313/67717925-57553e80-f9d7-11e9-982d-17ad921576f0.png">

Short way with CLI:
`nano /path/to/your/electron/app/node_modules/electron/dist/Electron.app/Contents/Info.plist`

Then add that code above:
<img width="465" alt="Screenshot at Oct 28 23-05-58" src="https://user-images.githubusercontent.com/32100313/67718038-9edbca80-f9d7-11e9-854e-3cd704d192b5.png">

**Comment by nathanlesage** [comment]
After like almost a year of being in the dark (no pun intended) I finally found out what had caused it at least for me: As most macOS users tended to use NightOwl prior to Apple shipping the dark mode feature natively, I suspect that at some point the app accidentally wrote a global default which would prevent Electron apps from going dark. In this case it's `NSRequiresAquaSystemAppearance` in the global defaults.

This means: No matter what your `plist` says: If the global `NSRequiresAquaSystemAppearance` is set to True, your app will receive the notification, but isDarkMode will always return false, even up until Electron 9, because this has nothing to do with Electron, as I figured out.

I recommend you completely unset the default globally (so that single apps may set/unset this as they wish):

`defaults delete -g NSRequiresAquaSystemAppearance`

But you can also force all apps to support both dark and light mode (albeit not recommended, as, for instance Zotero will lose all context menu labels if the following is run):

`defaults write -g NSRequiresAquaSystemAppearance -bool No`
