### ISSUE TITLE
electron v7: CORS requests don't work for custom protocols

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#20730]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.0.0
* **Operating System:** Linux
* **Last Known Working Electron version:** 6.1.1
### Expected Behavior
CORS requests should work for custom protocols as it worked with previous Electron versions.

### Actual Behavior
CORS requests don't work for custom protocols with Electron v7. No `Origin` header set ...

### To Reproduce
https://github.com/vladimiry-playground/electron-quick-start-custom-prtocol-cors-issue
- `npm start`
- then open the "network tab" in dev tools and click the "send xhr request" button

### Screenshots

Just one incorrect request but should be two (OPTIONS/preflight and POST then, see `electron@6.1.1-related` headers dumps below):

![123](https://user-images.githubusercontent.com/1560781/67524646-c40bc880-f6b9-11e9-9622-3cec65a171b2.png)

### Additional Information

See some headers dumps:

**FAILED** ========== electron@7.0.0: `Origin` header is not set

initial request includes headers:
```
Accept: application/vnd.protonmail.v1+json
Content-Type: application/json;charset=UTF-8
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36
x-pm-apiversion: 3
x-pm-appversion: Web_3.16.6
```

No further requests executed as CORS request was not propery initialized.

**OK** ========== electron@6.1.1 `Origin` header is set in request, `access-control-*` set in response, etc

OPTIONS request includes headers:
```
Access-Control-Request-Headers: content-type,x-pm-apiversion,x-pm-appversion
Access-Control-Request-Method: POST
Origin: scheme123://index.html
Sec-Fetch-Mode: no-cors
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/76.0.3809.146 Electron/6.1.1 Safari/537.36
```

OPTIONS response includes headers:
```
access-control-allow-credentials: true
access-control-allow-headers: content-type,x-pm-apiversion,x-pm-appversion, cache-control, Date, authorization, x-pm-uid, x-eo-uid, x-pm-appversion, x-pm-apiversion
access-control-allow-methods: POST
access-control-allow-origin: scheme123://index.html
access-control-expose-headers: Date, Retry-After
```

POST request includes headers:
```
Accept: application/vnd.protonmail.v1+json
Content-Type: application/json;charset=UTF-8
Origin: scheme123://index.html
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/76.0.3809.146 Electron/6.1.1 Safari/537.36
x-pm-apiversion: 3
x-pm-appversion: Web_3.16.6
```

POST response includes headers:
```
access: application/vnd.protonmail.api+json;apiversion=3
access-control-allow-credentials: true
access-control-allow-origin: scheme123://index.html
access-control-expose-headers: Date, Retry-After
```

**Comment by vladimiry** [comment]
CC @nornagon / @MarshallOfSound

**Comment by vladimiry** [comment]
By the way electron@8.0.0-beta.1 is not affected, so only v7 is broken.

**Comment by vladimiry** [comment]
I did more testing and realized the electron@8.0.0-beta.1 is also affected but differently: electron v8 sets the headers but `onBeforeSendHeaders / onHeadersReceived` handlers don't actually modify the headers (the browser ignores the modification).

**Comment by vladimiry** [comment]
@nornagon is it because #19602 is not completely resolved yet? Although I see "webRequest API (@zcbenz)" is checked there. So far it looks like `webRequest` handlers really work differently/wrongly since electron v7.

**Comment by issacgerges** [comment]
I believe this may be caused by `OutOfBlinkCors`. I was working with someone in the electron chat on a similar issue and noticed that his issue (the origin header no longer being present in this request) stopped working at `v7.0.0-beta.4` (which included a Chromium upgrade). In his case, we could validate that the issue was resolved in that same version with 

```
app.commandLine.appendSwitch('disable-features','OutOfBlinkCors');
```

Here's a gist I made that replicates his issue, which does the following
* Registers a privileged custom buffer protocol
* Serves the initially `loadUrl` off that protocol
* Once loaded does a `fetch` to that custom protocol that will echo the headers received

You'll notice that un-commenting the switch that disables `OutOfBlinkCors` will fix his issue

https://gist.github.com/207e72ba922f132960cd115a179de9e0

**Comment by vladimiry** [comment]
Just tried v7.0.1 and it doesn't require adding `app.commandLine.appendSwitch('disable-features','OutOfBlinkCors');` anymore for CORS requests to start working. But headers modification implemented in `onHeadersReceived` still doesn't take an effect.

**Comment by vladimiry** [comment]
Closing this issue as the CORS scenario is, in general, got working since v7.0.1 but also opening another issue here https://github.com/electron/electron/issues/20923.
