### ISSUE TITLE
titleBarStyle: 'customButtonsOnHover' -- Results in a loss of rounded corners in BrowserWindow

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#21739]
### Issue Details

* **Electron Version:**
  * `7.1.8`
* **Operating System:**
  * `macOS 10.13.6`
* **Last Known Working Electron version:**
  * `N/A`

### Expected Behavior
`titleBarStyle: 'customButtonsOnHover'` should only affect the buttons and not change the shape of the window to be a rectangle

### Actual Behavior
The buttons are rendered properly, but the window loses its rounded corners

**Here's a sample of the upper-right corner of a window with each mode:**

![image](https://user-images.githubusercontent.com/6835891/72211672-55126480-349d-11ea-989c-c67cce6e5bee.png)

**Left** - `'hidden'`
**Right** - `'customButtonsOnHover'`

### To Reproduce
Create a `BrowserWindow` with `titleBarStyle: 'customButtonsOnHover'` and observe the lack of rounded borders

### Additional Information
`customButtonsOnHover` didn't work at all in `4.1.5`, so it's really awesome to see it working so close to perfectly!

----

![image](https://user-images.githubusercontent.com/6835891/72211700-b9352880-349d-11ea-8f55-de9edc272121.png)

**All glory to the Electron Team**

**Comment by codebytere** [comment]
@Slapbox should be fixed by https://github.com/electron/electron/pull/20360, which was just recently merged :)

**Comment by codebytere** [comment]
Closing in light of the above but @Slapbox if you find anything amiss with this in the new & ostensibly fixed version please ping again and i'll follow up :D

**Comment by Slapbox** [comment]
@codebytere - sadly, still rectangles here. 

![image](https://user-images.githubusercontent.com/6835891/72574014-98057b00-3895-11ea-9bf5-86d70c6453f9.png)

Bottom-Left - 'customButtonsOnHover'
Top-Right - `hidden`

**Comment by Slapbox** [comment]
@codebytere - still an issue in `7.1.10` unfortunately. Any thoughts?

**Comment by Slapbox** [comment]
Whenever possible, could someone please re-open this issue? It really breaks the native-feel of an app.

**Comment by Slapbox** [comment]
@natew @codebytere @zcbenz Anyone have any thoughts on this issue? It seems like the expectation was that #20360 would fix it, but unfortunately not.

Sorry, I don't mean to be a pain, but we're bumping up against our intended release date now so I figured I'd ask everyone involved with that PR for input.

**Comment by Slapbox** [comment]
@codebytere could we re-open this issue? This issue continues to persist in `8.2.3`.

**Comment by Slapbox** [comment]
-_-

**Comment by codebytere** [comment]
@Slapbox we have over a thousand issues and are doing our best - comments like that aren't helpful. I'll try to take another look at this when i can.

**Comment by Slapbox** [comment]
Much love to all of you - I really appreciate all that you all do. 

At some point it starts to feel foolish to keep asking for an update, you know? Like maybe there's a good reason you're not getting a response beyond simply sheer numbers?

Sorry - I meant no offense.

Last time I tested and had the issue was `Electron@8.2.3` on High Sierra (`10.13.6`).

If it can't be reproduced on your end then it can't be fixed and I understand ¯\_(ツ)_/¯

 I just wanted an update and I want you to know that I really appreciate your reply.

**Comment by seanr3** [comment]
Also occurs in Electron 10.1.3 and 9.3.2 when combined with `frame: false` on macOS 10.15.6. However, each alone does not cause rectangle.

**Comment by zcbenz** [comment]
This is a duplicate of https://github.com/electron/electron/issues/10424.

**Comment by zcbenz** [comment]
This is a duplicate of #10424.
