### ISSUE TITLE
No compatibility with speech to text

### ISSUE THREAD

**Issue by DevanshuGoyal8** [electron/electron#23813]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by DevanshuGoyal8** [comment]
I tried different packages but nothing is compatible with electron

**Comment by ahallicks** [comment]
I've just got this working in Electron v9.0.0. It wasn't working in v8.x.x but something has changed and it does appear to be working now.

**Comment by DevanshuGoyal8** [comment]
> I've just got this working in Electron v9.0.0. It wasn't working in v8.x.x but something has changed and it does appear to be working now.

can you please explain it in detail as I tried it in v9.0.0 as well but nothing worked. 
Which package you have used ?

**Comment by ahallicks** [comment]
A simplified version of what I use. This is in the renderer process. I know for Chrome browser this can only be done after an action or event on the page. Not sure about Electron (I have a context menu that shows the option to start talking).

```
/**
 * Adds support for speech-to-text
 */
class Speech {

	constructor()
	{

		this.recognition = new webkitSpeechRecognition();
		this.recognition.lang = 'en-GB';

	}

	/**
	 * Instantiation of the class, checks for the voice list change event
	 */
	init()
	{

		// Trigger the listen call on an event
		this.listen().then(strTxt => console.log(strTxt)).catch(e => console.log(e));

	}

	/**
	 * Listen for input and convert to text
	 *
	 * @return {Promise} Promise that is fulfilled with the synthesised text
	 */
	listen()
	{

		return new Promise((resolve, reject) => {

			this.recognition.start();
			this.recognition.onresult = e => {

				this.recognition.stop();
				resolve(e.results[0][0].transcript);

			};

			this.recognition.onerror = e => {

				this.recognition.stop();
				reject(e);

			};

		});

	}

}
const clsSpeech = new Speech();
clsSpeech.init();
```

**Comment by sofianguy** [comment]
reported as fixed in v9

**Comment by Tobias-Keller** [comment]
getting the same error with version 9.0.4 as with 8.x. .... error: network

**Comment by neryash** [comment]
How do you fix this?

**Comment by ahallicks** [comment]
@sofianguy This is still an issue in v11.x.x. 9 stopped working and now it doesn't work in any version that I can tell. It does still work in the browser, however.

**Comment by neryash** [comment]
@ahallicks will this be fixed, and if not is there any other way to implement free live stt?

**Comment by alectrocute** [comment]
This is a limitation imposed by Google’s server-side. Unfortunately, it’s looking like Electron developers will need to provide their own API key/tokens to access this API. While it makes me sad, it makes sense.

**Comment by CodyBontecou** [comment]
> This is a limitation imposed by Google’s server-side. Unfortunately, it’s looking like Electron developers will need to provide their own API key/tokens to access this API. While it makes me sad, it makes sense.

Is it possible for me to supply my own API key?

**Comment by OscarJVD** [comment]
Hola, estoy tratando de usar artyom.js con electron, pero no reconoce mi voz, agradecería su colaboración

**Comment by CodyBontecou** [comment]
I was able to get Speech to Text to work using [https://github.com/googleapis/nodejs-speech](https://github.com/googleapis/nodejs-speech).

@OscarJVD Pude hacer funcionar la voz a texto usando https://github.com/googleapis/nodejs-speech. No creo que Artyom.js o cualquier speechSynthesis / webkitSpeechRecognition funcione con Electron

**Comment by TrofinSorin** [comment]
@CodyBontecou can you provide a simple implementation example please?

**Comment by OscarJVD** [comment]
@CodyBontecou May you provide a simple implementation example please?

**Comment by CodyBontecou** [comment]
Sure @TrofinSorin @OscarJVD, the code can be seen [here](https://github.com/CodyBontecou/Vocate).

I set up the Google Speech to Text to activate when a [keybind was pressed](https://github.com/CodyBontecou/Vocate/blob/main/src/index.ts#L31) - but you should be able to use the `main` function wherever you need it.

The Google code is [here](https://github.com/CodyBontecou/Vocate/blob/main/src/MicrophoneStream.ts). This was extracted from their [example](https://github.com/googleapis/nodejs-speech/blob/main/samples/MicrophoneStream.js). I used an [EventEmitter](https://github.com/CodyBontecou/Vocate/blob/main/src/Notifier.ts) to get the async results out of the speech to text.
