### ISSUE TITLE
Mac App Store Reject with Electron 7.1.13 Version

### ISSUE THREAD

**Issue by vijayamin83** [electron/electron#24379]
We have developed the electron + react desktop application, and DMG file and EXE file works well. 

But when I have uploaded MAS application to Mac App Store, It's rejected with following reasons:

********************************************************************************************************************
Your app includes a version of an SDK from Electron that violates the App Store Review Guidelines. The version of the Electron SDK you are using in your app attempts to hide the use of private APIs. This is a violation Section 2.5.1 of the App Store Review Guidelines.

Classes: CAContext, CALayerHost

Guideline 2.5.1: Apps may only use public APIs.
********************************************************************************************************************

I have made research on this, but did not find the proper solution. Can any one help here?

**Comment by alicerunsonfedora** [comment]
I believe newer versions of Electron like Electron v9.0.x have this rejection issue resolved.

**Comment by vijayamin83** [comment]
I have read the release notes of Electron latest version, I did not find this issue is fixed.

**Comment by alicerunsonfedora** [comment]
Latest as in 9.0.x, or latest as in v7.1.x? The latest API rejection that was resolved (that I'm aware of) is https://github.com/electron/electron/issues/24247

**Comment by vijayamin83** [comment]
Right now, we are using 7.1.x, And getting the issue.

**Comment by bouncyball02** [comment]
I'm not a Mac user myself, but I would recommend upgrading Electron to the latest version as this might solve the issue.
According to [docs.npmjs.com](https://docs.npmjs.com/updating-packages-downloaded-from-the-registry#updating-local-packages), you can run `npm update` to do this.

**Comment by vijayamin83** [comment]
I have already updated to latest version, but it still have the issue.

**Comment by alicerunsonfedora** [comment]
Does `npm install electron@9.0.5; npm update` change anything for you?

**Comment by vijayamin83** [comment]
No, it did not worked for me

**Comment by bouncyball02** [comment]
I think this is a problem on Apple's side.

**Comment by alicerunsonfedora** [comment]
That's a bit odd; I was able to release my app to the Mac App Store with no issues as of yesterday using Electron v9.0.5. Does your app report that it's using the latest Electron version, or are you using a cached version of an older Electron install?

**Comment by vijayamin83** [comment]
That's strange. 

BTW, Can you let me know how I can install the electron through external url with electron-builder?

**Comment by alicerunsonfedora** [comment]
I believe the Electron version is read in your package.json file. I have the following in my dependencies:

```json
"devDependencies": {
    "electron": "^9.0.5",
    "electron-builder": "^22.7.0",
}
```

**Comment by vijayamin83** [comment]
https://github.com/electron/electron/issues/24262

Here also I find that with 9.0.5, Apple is rejecting app

**Comment by alicerunsonfedora** [comment]
That issue was resolved as the APIs in question were public and it was a mistake on Apple's end. I submitted with the same version (9.0.5) with success.

**Comment by vijayamin83** [comment]
Yes, 

> I believe the Electron version is read in your package.json file. I have the following in my dependencies:
> 
> ```json
> "devDependencies": {
>     "electron": "^9.0.5",
>     "electron-builder": "^22.7.0",
> }
> ```

Yes, I am using this

**Comment by alicerunsonfedora** [comment]
Have you compiled with the latest Electron version and submitted it to the App Store for review? You should be fine since the CALayerHost and CSContext API rejections were resolved, if I'm not mistaken.

**Comment by vijayamin83** [comment]
I wil try that again with some more design level changes and will let you know.

Can you run this command and give me output of 
otool -ov  xxx.app/Contents/Frameworks/Electron\ Framework.framework/Versions/A/Electron\ Framework > /tmp/temp.txt

**Comment by bouncyball02** [comment]
> The ones you are citing are from older versions of Electron

Have you tried `npm clean-install`?

**Comment by alicerunsonfedora** [comment]
I'm not sure why I need to run `otool` since I was able to submit just fine, but here...

[f.txt](https://github.com/electron/electron/files/4871338/f.txt)

**Comment by vijayamin83** [comment]
After updating the electron version to 9.0.5, When I submit to MAC Store, I am getting the below error now:

Specifically, App still launches to no UI; user is unable to use the app.
Note: No main window appears on launch, menu and icon on Dock only.

Although, my code is working in the development mode properly.

**Comment by alicerunsonfedora** [comment]
It's most likely a code-signing entitlements conflict as I ran into that same issue (#20560). You may want to continue there or file a separate issue as it appears it's not related to 7.1.13.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
