### ISSUE TITLE
jQuery isn't set globally because "module" is defined

### ISSUE THREAD

**Issue by luto** [electron/electron#254]
jQuery contains something along this lines:

``` javascript
if ( typeof module === "object" && typeof module.exports === "object" ) {
  // set jQuery in `module`
} else {
  // set jQuery in `window`
}
```

module is defined, even in the browser-side scripts. This causes jQuery to ignore the `window` object and use `module`, so the other scripts won't find `$` nor `jQuery` in global scope..

I am not sure if this is a jQuery or atom-shell bug, but I wanted to put this on the web, so others won't search as long as I did.

**Comment by kabalage** [comment]
If your app does not need node-integration, add `"node-integration": false` to your BrowserWindow options. In this case `module.exports` is not available, jQuery works like expected.

**Comment by miguelmota** [comment]
@kabalage worked wonderfully, thanks!

**Comment by vrunoa** [comment]
:+1:

**Comment by RamonGebben** [comment]
Walked up to the same issue. Install jQuery via NPM then required it and it worked.

**Comment by skandasoft** [comment]
what if node integeration and jquery without the require is needed...

**Comment by dleroux** [comment]
I'm trying to make sense of this since it appears to be something I could use. However I wonder when can you be sure you can safely use $. Logging $ right after this line will result would be require and not jquery since require is asynchronus?

window.$ = window.jQuery = require('/path/to/jquery');
console.log($) // logs 'require' not 'jQuery'

**Comment by RamonGebben** [comment]
@dieroux try installing it via npm:
```
npm install jquery
``` 
This worked for me while trying the same. Then you don't need to give a path, you just say:

```javascript
window.$ = window.jQuery = require('jquery');
console.log( [$, jQuery ]);
```

**Comment by vikbez** [comment]
What if we need node-integration, and we can't use require('something') ?
Currently it works by doing "delete module;" before loading problematic-stuff.
What's the impact of doing this ?

**Comment by ahazelwood** [comment]
I'm having similar issues where jquery can be loaded correctly the first time I need it in a preload script on a webview.  However the second time jquery is referenced from an external page, the line to assign it via:

  try {
		module.exports = null;
		if (typeof require === 'function') {
		  alert('window: ' + window);
		  alert('jquery: ' + window.jQuery);
		  alert('export: ' + module.exports);
		  if ( !window.jQuery ) {
		    alert('before load');
			window.jQuery = require('./node_modules/jquery/dist/jquery.js');
			alert('after load');
			window.$ = window.jQuery;
			alert('after assignment');
		 }
		  alert('jquery: ' + window.jQuery);
		}
    } catch(e) {
	    alert('failed load.');
		console.log(e);
	}

throws a Cannot read property createElement of undefined in the console at the assignment to window.jQuery from require, resulting in jQuery not getting loaded.  

Error message on the console is:
Guest page logged a message:  TypeError: Cannot read property 'createElement' of undefined line: 40

Any additional thoughts on how to successfully load jquery on subsequent pages?

Thanks.

**Comment by vai** [comment]
This was the first thing I tripped over when running through the electron quickstart and tried to wrap a local app - something working in chrome suddenly doesn't in election. Having the error buried in failed angular module loads doesn't help of course, so I assumed there was an issue with script load order, which is how I found this thread. Perhaps the keywords will help others.

@kabalage 's solution above worked perfectly.

**Comment by neeln4j** [comment]
Hello all ,I just want add some info with this issue , If i paste the jquery library code in electron console $ and jQuery is added as a function in window object. i could able to run jquery.

**Comment by diimdeep** [comment]
Referenced jQuery with <script> tag, same error. Have to "node-integration": false in BrowserWindow()

**Comment by WolfieWerewolf** [comment]
Hi guys... I'm not sure why this issue is closed, there is definitely still an issue here, let me explain.  If I install jQuery locally via NPM and load a local html file then using:

mainWindow.$ = require('jQuery');
mainWindow.jQuery = require('jQuery');

then it works as expected.  If, however, I do mainWindow.loadUrl('http://external.site.com");

I get the errors mentioned where $ and jQuery are not defined.  Disabling node integration is really not an acceptable answer; it's the reason I'm using Electron in the first place, I need it.  

I'd be keen to get into the source and troubleshoot this myself but thought I would see if anyone had any additional information on this to point me in the right direction before I go down there.  Has anyone been able to get this to work _with_ node integration, against external sites?

Thanks... and great work BTW.  Everything new and beautiful, like this, is going to start with a few wrinkles.

Kind Regards

/W

**Comment by diimdeep** [comment]
I made it work with node-integration. 

1. Install it with npm, so it is defined in package.json 
2. Use require with module name `<script>window.$ = window.jQuery = require('jquery');</script>`
4. Don't use path in require parameter.
4. Don't install trough bower, it will make you to use path in require parameter.
5. If you use bootstrap you need to load jQuery first.

All of above supported only by my experience.

**Comment by WolfieWerewolf** [comment]
Hi dilmdeep, thanks for the quick response.  Does your solution depend on having control over the external site?  I'm trying to load a site that I don't have source access to.  What you said about packages.json is interesting though.  I did install jQuery through npm (and used the documented rebuild for electron) and, like I said, I can use jQuery with a local HTML file, but jQuery is not defined in my package.json.....

**Comment by WolfieWerewolf** [comment]
I just wanted to update this in case someone else gets into the same trouble.  The way I worked around this (after downloading 10GB of Electron source) was actually in the documentation to begin with.  Instead of calling the url of the external site I loaded a local HTML file and used a webview from that html file to load the external site.  It loads perfectly with node-integration enabled.  Just look in the docs for webview, it's pretty straight forward.  Also my thanks to Paul in the chatroom for helping me get started with the source.  If anyone's wondering they use Atom (of course) to code Electron, WinDbg on windows to debug and Ninja to compile.  FYI compiling the sources was dead easy and surprisingly fast, it compiled first go using their scripts and the provided documentation.  Again, great work guys!

**Comment by Shufeng01** [comment]
@WolfieWerewolf Bravo! have to say the example is bit misleading if security is considered.

**Comment by WolfieWerewolf** [comment]
@Shufeng01 Cheers mate, I'm coming at this cold from .Net land so feeling like a complete n00b.  You're right that security was an issue however using the disablewebsecurity flag on the webview itself resolved most of it.  I think security, in general, is the biggest challenge for bringing the web to the desktop... but well worth the effort.  Electron rocks.

**Comment by psulek** [comment]
@diimdeep thanks, you solution works for me (not what @WolfieWerewolf wants!)

**Comment by bgSosh** [comment]
This is a bit of a problem for us.  We bundle jquery with our app js, and this concatenated JS is then used in build for both the web and desktop versions (we have been using NWJS).  NPM install may be an option for us, but it's not ideal in our situation for a couple of reasons.

Is there no theoretical way of getting it to work using script tags?

**Comment by etiktin** [comment]
@bgSosh, why not disable node integration (read about the `node-integration` key [here](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions))? If you do that, script tags should work correctly. If you need some node related stuff you could do that in a `preload` script (they always have node integration).

**Comment by matthiasg** [comment]
@etiktin can you please elaborate how to do this in preload ? i am new to electron and havnt managed to get a preload script to execute (at least it appears not to execute, console.log not working, changing window.myExposedIPC = require('ipc') for example is not available later etc.

**Comment by matthiasg** [comment]
i have got it working in case anybody has the same issue: https://github.com/atom/electron/issues/1753#issuecomment-157409572

**Comment by etiktin** [comment]
@matthiasg glad you got it working. I added some comments to your example.

When node integration is disabled and you want to do some node stuff in your preload script, it's important to hold a reference to what ever node global you need. You need to do this, because on the next tick the global references are deleted (this is how disabling node integration is implemented), so if you didn't hold a reference and you then try to require something on a function call or a timer, it would fail.

**Comment by matthiasg** [comment]
@etiktin thanks. Of course that was part of it, but what i was missing is the documentation for `process.once('loaded', ... )` once that was in place i can actually expose the apis i wanted.

**Comment by forman** [comment]
Hi guys,

Since none of the above worked for me (using w2ui and JQuery both with electron and independent HTML page, let also w2ui use jQuery), I felt the need to post my working solution here:

```html
<html>
<head>
    <title>MyApp</title>
    <link rel="stylesheet" type="text/css" href="./lib/w2ui-1.4.3.css"/>
    <script type="text/javascript" src="./lib/require.js"></script>
    <script type="text/javascript" src="./lib/jquery-2.1.4.js" onload="$ = jQuery = module.exports;"></script>
    <script type="text/javascript" src="./lib/w2ui-1.4.3.js"></script>
</head>
<body>
<script type="text/javascript">
    // use global $ and w2ui here... 
    ...
```
I'm a newbie to JS and performing a technology study and now a bit worried about this obscure module loading stuff. It may be a silly question but why does electron load JS modules so differently from usual browsers when loading an HTML page?

**Comment by etiktin** [comment]
@forman did you disable node integration and use a preload script for node interaction? See the comments above by me and @matthiasg. If you do that, jquery and the rest will work exactly like they do in the browser.

**Comment by capricornlee** [comment]
Will work



    requirejs(['require', '../require.config'], function (requirejs, config) {
            //fixed jQuery isn't set globally
            requirejs(['jquery'],function(jquery){
                window.$ = window.jQuery =jquery;
            });
            // update global require config
            window.requirejs.config(config);
            // load app
            requirejs(['main'],function(main){
            });
        });

**Comment by hugohil** [comment]
@forman Thank you !! None of the above worked excepted your solution. (using electron-prebuilt 0.35.5)
@etiktin This worked for me without having to change anything on the mainProcess side

**Comment by adamlj** [comment]
Thought I should add our problem and solution to this thread for future reference.

We're loading an external url in a webview and need to execute our own Javascript that can use electron/Node. Enabling nodeintegration on the webview isn't an option since this will break jQuery that is being used by the external url. 

What we ended up doing was adding a preload script to the webview where we put the modules we need in the global scope. This makes them accessible later on when we execute our Javascript.

preload.js:
```
global.ipcRenderer = require('electron').ipcRenderer;
```

And then we can access the ipcRenderer like:
```
webview.executeJavaScript("ipcRenderer.sendToHost('hello');");
```

**Comment by ramezrafla** [comment]
@adamlj, Thanks for posting your solution. Can you please elaborate on how your preload.js would work on the webview when you have nodeintegration off? You are calling ```require`` in it which would need node. As well, once you load a new page in that webview, wouldn't you lose your settings?

**Comment by Sigmanor** [comment]
`Uncaught Error: Cannot find module 'jquery'` and nothing helps from this thread =/

**Comment by tomkel** [comment]
I wanted to have my webpage work both in the browser and in electron.
As explained in this thread, electron exposes a global `module` when `nodeIntegration: true`, which jQuery then sees and reacts accordingly:
```javascript
if ( typeof module === "object" && typeof module.exports === "object" ) {
    // bind to module
} else {
    // bind to window
}
```
I was able to get jQuery to bind to the `window` object and use `nodeIntegration: true` by doing the following in my html file:
```html
<script>window.module = module; module = undefined;</script>
<script src=//code.jquery.com/jquery-1.12.0.min.js></script>
<script>module = window.module;</script>
```
Hope this helps someone.

**Comment by dkfiresky** [comment]
@tomkel here is another solution:
```html
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script>window.jQuery = window.$ = module.exports;</script>
```

But, jQuery object is still exported into module.

**Comment by aaaaahaaaaa** [comment]
In my case, I need to be able to both launch my application as a website and a Electron application. Here is my solution:

```html
<!-- Launched with Electron -->
<script>
	if ('require' in window) {
		window.$ = window.jQuery = require('jquery');
	}
</script>

<!-- From CDN, Bower, etc... -->
<script src="https://code.jquery.com/jquery-2.2.0.js"></script>
```

**Comment by tomkel** [comment]
@dkfiresky Yes, that seems to work as well. However I'm using Highcharts in conjunction with jQuery. Highcharts does a similar thing, placing itself on `module` if it exists. For whatever reason I was unable to get 
```html
<script>window.Highcharts = module.exports;</script>
```
to work.

**Comment by palavrov** [comment]
@tomkel your solution with the temporal hiding of `module` works very well for me. My problem was during migration from nw.js with ngDialog assuming that it is in CommonJS environment failing to `require('angular')` and to register itself as angular module.

**Comment by gnail** [comment]
In Electron 0.36.7 I find that I cannot do a simple `window.$ = require('jquery');` as it'd fail to find the module. I have to do `window.$ = require('electron').remote.require('jquery');' to do it in the main process. The renderer doesn't seem to have the same module resolution path as the main process

**Comment by paulcbetts** [comment]
> And require('jquery') didn't work for me because I'm serving the page through HTTP like #4243.

If you are allowing remote content to access node.js, your app is very very insecure, you need to disable node integration when running remote content.

**Comment by gnail** [comment]
Even if the "remote content" is localhost? I'm using node to build and serve me the page instead of reading from a local file, that is all

**Comment by dspint** [comment]
Expanding on @dkfiresky, you might get a `Uncaught ReferenceError: module is not defined` in the browser version.

If so, try this:

    <script src="./bower_components/jquery/dist/jquery.min.js"></script>
    <script>window.jQuery = window.$ = typeof module === 'object' ? module.exports : jQuery</script>

**Comment by dkfiresky** [comment]
@dspint `module` will be undefined only in case of node integration disabled in `BrowserWindow`, so you probably should use my example only with node integration enabled.

**Comment by justindujardin** [comment]
If you are using `window.open`, you can pass `nodeIntegration=0` with your window options.

```javascript
window.open('https://your.cool/url', 'title', 'nodeIntegration=0');
```

**Comment by RRorg** [comment]
I'm doing:

```
<script>
  var saveModule = module;
  delete module;
</script>
  <script src="jquery.js"></script>
  <script src="jquery-ui.js"></script>
<script>
  module = saveModule;
</script>
```

**Comment by kareljan** [comment]
I had the same problem as @gnail. I had a node server running a angular project. His code fixed it for me. 

```
require('electron').remote.process.mainModule.paths.forEach(function(path) {
  require('module').globalPaths.push(path);
});
```

**Comment by mayke5421** [comment]
It's working for me 😄 

```html

<script>
    window['old_module'] = window['module'];
    delete window.module;
</script>

<script src="any_lib_like_jquery.js">

<script>
    window['module'] = window['old_module'];
    delete window.old_module;
</script>

```

**Comment by PauloGaldo** [comment]
I'm having this issue, i've already tried all of this thread. but nothing works, im stuck on the beggining
of all.
i'm using the electron-starter rep

**Comment by RRorg** [comment]
@PauloGaldo basically any solution in this thread should be working. Please post the relevant excerpt of your code and all error messages you encounter.

**Comment by Vishal1419** [comment]
@ChiperSoft  Can you please tell me where should I use your code?

**Comment by englishextra** [comment]
@tomkel Very nice!
I finally got Masonry to work within Electron!

**Comment by akashnimare** [comment]
For some reason I'm still not able to make jQuery work both in browser and in Electron app.
My web app works fine in browser whereas when I try to load the same url via electron app it throws -

![image](https://cloud.githubusercontent.com/assets/2263909/19090430/0689908a-8a9c-11e6-9a8f-785ee57ebc55.png)

Webapp - https://github.com/zulip/zulip
Electron app - https://github.com/zulip/zulip-electron

The webapp is using jquery 1.12.1 version.
I'm having hard time solving this 😞 . Does anyone know how to make it work?
cc @aaaaahaaaaa @maykefreitas @paulcbetts @tomkel @dkfiresky

**Comment by englishextra** [comment]
@akashnimare if you embed jQuery into your code, try this:

```
/*!
 * Temporal hiding of module
 * github.com/electron/electron/pull/3497
 * gist.github.com/englishextra/1bf72395f77c8cf25ddd900aa69a0d68
 */
var hideWindowModule=function(){"object"===typeof module&&(window.module=module,module=void 0);};
/*!
 * Temporal reveal of module
 * github.com/electron/electron/pull/3497
 * gist.github.com/englishextra/1bf72395f77c8cf25ddd900aa69a0d68
 */
var revealWindowModule=function(){window.module&&(module=window.module);};


hideWindowModule();
/*jQuery library code here*/
revealWindowModule();
```

**Comment by akashnimare** [comment]
@englishextra no luck. I tried to include your code into my app's [preload.js](https://github.com/zulip/zulip-electron/blob/master/app/main/preload.js) but getting same error.

**Comment by englishextra** [comment]
@akashnimare It shouldn't be in preload.js since you require jquery there
It can be if jQuery is embeded directly into app logic code. Something is wrong either with jquery version or paths

**Comment by akashnimare** [comment]
@englishextra No, I don't need jquery in my app. See the update code [here](github.com/zulip/zulip-electron). I can't include your code into my app logic since I'm using it only for loading the specified url see [this](https://github.com/zulip/zulip-electron/tree/master/app/renderer).

**Comment by cawoodm** [comment]
None of these fixes work for me for the simple reason that `window` is not defined:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
	</head>
<body>
</body>
<script>window</script>
</html>

```

Fails with:

```
App threw an error during load
ReferenceError: window is not defined
    at Object.<anonymous> (C:\blah\app.js:2:1)
    at Module._compile (module.js:556:32)
```

**Comment by lmj0011** [comment]
for those using the Aurelia framework:
https://github.com/aurelia/skeleton-navigation/pull/675/commits/6292e698dcb8f383afc748aa7c8a50e540dfbe2e

**Comment by Bronts** [comment]
I resolved this problem with this
```
<script type="text/javascript" src="js/jquery.min.js" onload="window.$ = window.jQuery;"></script>
```

and set

```
webPreferences: {
            nodeIntegration: false, 
        }
```

**Comment by drowlands** [comment]
I mean, it seems to be a bad problem, so why not include it in actual Electron?

**Comment by RRorg** [comment]
Chances are, if you are using jQuery in an Electron App, you are doing something very wrong or at least inefficient.

**Comment by amhoho** [comment]
`<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script>if (typeof module === 'object') {window.jQuery = window.$ = module.exports;};</script>`

**Comment by englishextra** [comment]
@drowlands Including 3party libs in Electron seems to be a bad idea.
@amhoho That's because  you need to `require` it, or modify the the init code at the top function - leaving only `factory( global );`

**Comment by anuxs** [comment]
mark

**Comment by karlhorky** [comment]
@kabalage I think the configuration in your post above is out of date. It looks like it should be like this now:

```json
const window = new BrowserWindow({
  webPreferences: {
    nodeIntegration: false, 
  },
});
```

**Comment by souzace** [comment]
On official docs:
https://electronjs.org/docs/faq#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron
```
<head>
  <script>
  window.nodeRequire = require;
  delete window.require;
  delete window.exports;
  delete window.module;
  </script>
  <script type="text/javascript" src="jquery.js"></script>
</head>

**Comment by alotex** [comment]
I'm getting 
`TypeError: Cannot read property 'createElement' of undefined`
in webview.

preload script is
```
const path = require('path');
const {ipcRenderer} = require('electron')
const fs = require('fs');
window.$ = window.jQuery = require(path.join(__dirname, '../jquery.min.js'))
```
