### ISSUE TITLE
Remove deprecated Gconf, migrate to Dconf

### ISSUE THREAD

**Issue by strelec** [electron/electron#2727]
GConf is a legacy configuration system. Migration is part of the intiative for GNOME 3.x. Many of the application have already made the switch, except for you and very few others:

https://wiki.gnome.org/Initiatives/GnomeGoals/GSettingsMigration

That thing is deprecated for 4 years now.

**Comment by paulcbetts** [comment]
Moving to new software on Linux platforms is basically impossible because people keep running weirdo configurations or refuse to adopt GNOME 3.0, etc etc. If Electron moved to a new library like this, I guarantee that a decent chunk of users will immediately be locked out of the app then take up pitchforks.

**Comment by zcbenz** [comment]
Lots of old and popular distributions are still using Gconf, and we need to make sure Electron works on them, so we will not do the migration until all supported distributions have migrated to Dconf, which might not happen in a few years.

I'm closing this since we are not going to do it in near future.

**Comment by strelec** [comment]
Like, which one? All that have gconf installed, have dconf too.

They have gconf installed, because not all apps have transitioned yet.

**Comment by etiktin** [comment]
@strelec, the link you provided suggests that Chromium still hasn't migrated to GSettings. If they use it under the content module, then it will be a part of `libchromiumcontent` which means we will still depend on it.

What is the benefit of migrating? Will a Linux version from 4 years ago still be able to use Electron?

**Comment by strelec** [comment]
Chromium has, to my knowledge, migrated to Gsettings (https://code.google.com/p/chromium/issues/detail?id=169663). Gconf is legacy software, it is not going to be supported for long. The same thing is the dependency of electron on gtk2, which is also deprecated.

As a consequence, you probably won't make it into the official fedora repositories and you will have to make change in a forseable future anyway. Moreover, it annoys people to need to have gconf installed just for one app.

**Comment by paulcbetts** [comment]
Doing some research into this, it looks as if DConf has been supported since at least Ubuntu 12.02, we could probably consider moving over.

**Comment by strelec** [comment]
Exactly. The bug should be reopened.

**Comment by zcbenz** [comment]
I'm reopening this in case someone is interested in working on it.

**Comment by eternal-sorrow** [comment]
As I can see, the hard dependency on gconf is only in brightray, chromium part is already ported to dconf.

**Comment by zcbenz** [comment]
@eternal-sorrow Chromium is still using gconf, you can track this Chromium issue for current status:
https://bugs.chromium.org/p/chromium/issues/detail?id=399316

**Comment by eternal-sorrow** [comment]
I have installed chromium, but do not have gconf on my system. Everything is working fine. What am I doing wrong?

**Comment by mattdangerw** [comment]
@mildred you can build a version of gconf that uses dbus instead of orbit, easier to build into a flatpak runtime. See
https://github.com/endlessm/electron-flatpak-base-app/blob/master/io.atom.electron.BaseApp.json#L52
https://mail.gnome.org/archives/desktop-devel-list/2011-June/msg00087.html

**Comment by nazar-pc** [comment]
My issue with gconf2 is also that it is only required by single Electron-based app I'm using.
Since I'm not working with Electron, can anyone quickly suggest if it is possible to somehow build an Electron-based app without gconf and without hacking with Electron's sources?
An app I'm talking about is [Cerebro](https://github.com/KELiON/cerebro)

**Comment by gapplef** [comment]
gconf is no longer installed by default in Ubuntu 17.04[[1]](https://wiki.ubuntu.com/ZestyZapus/ReleaseNotes). 
For the softwares I'm using, only Electron-based apps still require gconf2!
Why this problem still unfixed?

**Comment by mbiebl** [comment]
Related to that: https://bugs.debian.org/cgi-bin/pkgreport.cgi?users=pkg-gnome-maintainers@lists.alioth.debian.org;tag=gconf

A default Debian/Ubuntu installation as already mentioned no longer installs gconf by default. And from the above it looks like gconf2 might actually be removed from the Debian/Ubuntu archive in the near future.
This would make any electron based app like signal uninstallable.

**Comment by ckerr** [comment]
Removing `blocked' tag because the referenced Chromium issue is marked as fixed now

**Comment by ckerr** [comment]
Upstream marked this as closed on 2017-11-24, so AFAICT we should be able to drop Electron's dependency when we upgrade to libcc 63.0.3239	or higher

**Comment by ckerr** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=768027 is also relevant and closed on 2017-12-28, so perhaps 64.0.3282 instead...

**Comment by apetresc** [comment]
Just a ping on this – libcc 64 has come and gone, you appear to be on 66 now. The gconf dependency still appears to be there in all the packaged versions I can see (like [this one](https://www.archlinux.org/packages/community/x86_64/electron/)). Are we any closer to dropping it?

**Comment by GhostlyDark** [comment]
With Electron v3.0.0 my app works without installing gconf2. I assume that it is no longer a dependency. Note that v3.0.0 is still in beta.

**Comment by pronebird** [comment]
Can anyone confirm that Electron migrated to `dconf` and what dependency the one needs to run Electron based app?

**Comment by oregonisaac** [comment]
Looks like multiple projects I use are seeing user errors with Ubuntu 18.04 and finding this issue as root cause.
https://github.com/decred/decrediton/issues/1404
https://github.com/resin-io/etcher/issues/1305
