### ISSUE TITLE
No display_id provided under Linux for desktopCapturer API

### ISSUE THREAD

**Issue by DomiStyle** [electron/electron#27732]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * Ubuntu 20.04.2 x64 (with 5.10 kernel)

### Expected Behavior
The [DesktopCapturerSource object](https://www.electronjs.org/docs/api/structures/desktop-capturer-source) should contain a display_id to be able to link the display together with the corresponding screen from the [screen API](https://www.electronjs.org/docs/api/screen). This works on every platform but Linux.

### Actual Behavior
display_id is an empty string on Linux.

### To Reproduce
Fiddle: https://gist.github.com/b94a9df46b4020c1ca8aec22e4764065

### Additional Information
A comment was added by @ajmacd [here](https://github.com/electron/electron/blob/462de5f97a302987dc5fa5c222781ceed040f390/shell/browser/api/electron_api_desktop_capturer.cc#L186) with [this pull request](https://github.com/electron/electron/pull/14835) by @deepak1556 2 years ago, stating that Linux does not support single screen capture (yet). It's now possible to capture single desktops with Chrome on Linux.

**Comment by michalzaq12** [comment]
I confirm the issue - `display_id` property is `undefined` on Linux.

Electron version: 12 & 13
OS: Ubuntu 18.04

**Comment by nornagon** [comment]
See https://github.com/electron/electron/blob/914256374878da1e61adaf403c59ace22b47dec9/shell/browser/api/electron_api_desktop_capturer.cc#L189-L191

I don't think it makes sense to have a display_id on window sources as a single window can be displayed on multiple screens.

**Comment by nornagon** [comment]
cc @ajmacd

**Comment by ajmacd** [comment]
IIRC, Chromium has implemented support for individual screen capturing on Linux now, see e.g.
https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/modules/desktop_capture/linux/screen_capturer_x11.cc;l=272;drc=2aa935684aeb183c5ade32ffc5bd706cd1fc902c

It should be possible to support this in desktopCapturer now.

**Comment by madhuni** [comment]
We are using electron version of `4.0.8` and Ubuntu `16.04`. We are kind of getting the similar issue with the `getSources` API. In our case, we are getting the `display_id` in the response but it's coming as empty string.

@ajmacd , I even tried the same with the latest stable version of electron `13.7.1` with the demo app provided by you as part of [PR#12417](https://github.com/electron/electron/pull/12417) and there as well I am getting the property with empty string.

Any update when can we expect the support for this?

**Comment by cosoc** [comment]
不支持Linux,我问社区electro有什么优势，windows和max有的是ui库，而且经过市场检验的！你觉得这给产品拿什么给别的竞争？优先支持linux才是你们应该考虑的问题！

**Comment by berkon** [comment]
Any update on this? This would be very helpful for us too. Currently we can only guess which screen is which on Linux.

**Comment by JakeMakesStuff** [comment]
This probably isn't a good workaround for everyone but I am sharing it because it worked for me. For me, I am using the top-left corner to match screens and capture them with a C++ module I wrote:
https://gist.github.com/JakeMakesStuff/202a8924b2b06832380cbf2b9e1b09da
https://gist.github.com/JakeMakesStuff/b51ff63ce7e668e9d18e78ad812c3518

Feel free to use it if it's helpful, no credit needed :)

**Comment by SarathKmrM** [comment]
I am still facing this issue.
Electron 18.2.0
Ubuntu 20

Any solutions ?
Will updating to electron 20 fixes this issue ? 
Or can this be fixed in electron 18 ?

**Comment by DomiStyle** [comment]
@jamesnvc I just tested your PR https://github.com/electron/electron/pull/33861 but I can't seem to get the display_id to match?

```
    name: 'Screen 1',
    id: 'screen:370:0',
    thumbnail: NativeImage {
      toPNG: [Function: toPNG],
      toJPEG: [Function: toJPEG],
      toBitmap: [Function: toBitmap],
      getBitmap: [Function: getBitmap],
      getScaleFactors: [Function: getScaleFactors],
      getNativeHandle: [Function: getNativeHandle],
      toDataURL: [Function: toDataURL],
      isEmpty: [Function: isEmpty],
      getSize: [Function: getSize],
      setTemplateImage: [Function: setTemplateImage],
      isTemplateImage: [Function: isTemplateImage],
      isMacTemplateImage: [Getter/Setter],
      resize: [Function: resize],
      crop: [Function: crop],
      getAspectRatio: [Function: getAspectRatio],
      addRepresentation: [Function: addRepresentation]
    },
    display_id: '3436127573',
    appIcon: null
```

```
    id: 4692723358442837,
    bounds: { x: 2560, y: 0, width: 2560, height: 1440 },
    workArea: { x: 2560, y: 32, width: 2560, height: 1408 },
    accelerometerSupport: 'unknown',
    monochrome: false,
    colorDepth: 24,
    colorSpace: '{primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}',
    depthPerComponent: 8,
    size: { width: 2560, height: 1440 },
    displayFrequency: 164,
    workAreaSize: { width: 2560, height: 1408 },
    scaleFactor: 1,
    rotation: 0,
    internal: false,
    touchSupport: 'unknown'
```

Is there something else I have to do or should they match?

I'm using the following code to get them both:

```
const sources = await desktopCapturer.getSources({ types: ['screen'] });
const displays = screen.getAllDisplays();

console.log(sources);
console.log(displays);
```

**Comment by jamesnvc** [comment]
@DomiStyle Hm, no, the source `display_id` should match the display `id`. Not sure why that's not working for you...that PR does the same thing to determine the display id for the source that the display does to calculate the id. Very odd. Unfortunately, I don't have easy access to my Linux machine now, but I can try to take a look.

**Comment by DomiStyle** [comment]
No worries, I'm using a workaround for it for now so there's no rush.

**Comment by DomiStyle** [comment]
Issue still exists.

Running the sample fiddle from the original issue on Electron v23.0.0 yields incorrect `display_id` under X11 and no `display_id` (and just one display) on Wayland.

**Comment by esquerbatua** [comment]
Issue still exists under X11

**Comment by maymage** [comment]
.

**Comment by vpzomtrrfrt** [comment]
bump

**Comment by ArtemAvramenko** [comment]
One of the real cases is getting full-size screenshots. To do this, I use heuristics to get the physical size of the display,  taking into account the inaccuracies that scale can give. This all works fine on macOS and Windows.

But on Linux with two or more displays with different resolutions, this method fails because there is no reliable way to map displays from the different APIs - `screen.getAllDisplays` and `desktopCapturer.getSources`

**Comment by ArtemAvramenko** [comment]
I wonder if we can at least expect that the first in the getSources list will always be the primary display?

**Comment by ArtemAvramenko** [comment]
@jamesnvc, @DomiStyle , I noticed that in the example above the Ids match if only the lower four bytes of the identifier are considered:
```
3436127573       = 0x00000000CCCF2555
4692723358442837 = 0x0010AC01CCCF2555
```
I don't know how correct it is, but a workaround like this is possible:
```js
displays.find(d => (d.id & 0xffff).toString() === capturerSource.display_id);
```

**Comment by vlades7** [comment]
The problem is still relevant. Blocks some important features on our product. I hope that work is underway to solve the problem.

**Comment by vlades7** [comment]
bump

**Comment by ArtemAvramenko** [comment]
Looked at my reply above and realized that I hadn't accounted for the 32-bit nature of bitwise operations in JavaScript.

Here is the corrected version:
```js
const displayId = parseInt(capturerSource.display_id);
displays.find(d => ((d.id / 0x10) & 0xfffffff) * 0x10 + (d.id & 0xf) === displayId);
```

**Comment by maymage** [comment]
.

**Comment by ArtemAvramenko** [comment]
I don't quite understand the status of this issue. It seems to have been resolved in version 21, but in subsequent versions with PipeWire support, the problem has returned.

Switching back from Wayland to the X11 API helps:
`process.env.XDG_SESSION_TYPE = 'x11'`

Does anyone know what the consequences of this might be?

**Comment by Hahlh** [comment]
bump

**Comment by ShGKme** [comment]
bump, not PR with a fixed was assigned

**Comment by jasongodev** [comment]
It's March 2026 and this is still a problem across all Electron versions (31-40). I'm using Arch Linux. Both X11, XLibre, and Wayland have problems.

**Comment by jasongodev** [comment]
bump! Also, I will recheck if newer Electron versions are affected.
