### ISSUE TITLE
Windows: display-removed event not working

### ISSUE THREAD

**Issue by delvedor** [electron/electron#3075]
Hi all, I'm trying to use the *display-removed* event in my electron app, but while under OSX 10.10 all works correctly, under Windows 7 the event is not detected/emitted.

This is my code:
```javascript
let electronScreen = require('screen');
electronScreen.on('display-removed', () => {
  console.log('display removed');
});
```

The event *display-added* works correctly.

I'm using Electron 0.33.7.

**Comment by ervwalter** [comment]
I can confirm a similar problem that is probably related.  In my case, not only is the event not working, but the array returned by getAllDisplays() still contains the old entry after a display is removed.  Seems likely that the two symptoms are related.

**Comment by zcxp** [comment]
I have same issue as @delvedor and @ervwalter on windows, 0.29.2 and 0.34.1

**Comment by ervwalter** [comment]
Also, the reason this is important to me is that when you remote desktop into a windows machine that normally has multiple monitors, the displays change to a new virtual display (and then they switch back to the physical displays when you log in at the physical machine later).  During that remote desktop session, the display information returned by the screen module is wrong.

**Comment by raleksandar** [comment]
I can also confirm that only *display-added* event is fired on Windows (Windows 10 Pro Insider Preview build 10576 at least).

Both *display-removed* and *display-metrics-changed* are never emitted (I've tested by plugging in/out monitors and changing resolution).

Tested with 0.34.2 Electron build

**Comment by lbonnet** [comment]
Confirmed on windows 7, electron 0.29.2

**Comment by ieundhdyjfawbb** [comment]
Confirming this issue for windows 8.1 and windows 10. Tested on 0.36.3 and 0.34.2.

**Comment by mradionov** [comment]
The same on Ubuntu 14.04 , electron 0.36.9.

**Comment by atietje** [comment]
Will this issue be adressed in the near future? 

No offense, but it was reported six month ago, and I currently fight screen rotation issues on a Windows 10 Tablet…

**Comment by miniak** [comment]
Looks like the problem is that the ID is not persistent, the monitor is not found in the vector.

```
void Screen::OnDisplayRemoved(const gfx::Display& old_display) {
  auto iter = FindById(&displays_, old_display.id());
  if (iter == displays_.end())
    return;

  displays_.erase(iter);
  Emit("display-removed", old_display);
}
```

**Comment by miniak** [comment]
I think that also `display-metrics-changed` is not working properly due to this.

**Comment by delvedor** [comment]
This issue/bug is very strange.
In addition to events, if you do this:
```javascript
setInterval(() => {
  console.log(screen.getAllDisplays())
}, 1000)
```
And you try to change the monitor's resolution, you will see that the AllDisplays array will not change.  
As temporary workaround I've made [this](https://github.com/delvedor/electron-screen) module, but it gives only the AllDisplays array.

**Comment by miniak** [comment]
My PR should fix that too

**Comment by doot0** [comment]
These events still aren't fired on OSX Sierra, current electron version.

**Comment by VladimirMerk** [comment]
The problem still exists in the electron 2.0.3 on ubuntu 16

**Comment by oopses** [comment]
This problem still exists on  24.5.1，Monitor hot plug does not trigger
