### ISSUE TITLE
[Bug]: Mouse clicks on target="_blank" links inside webview don't seem to give an event

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#30886]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0-beta.3

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 34

### What arch are you using?

x64

### Last Known Working Electron version

14.x.x

### Expected Behavior

Clicking a link in a webview with the "_blank" attribute should result in any kind of event somewhere, but it doesn't seem to work since enabling "nativeWindowOpen".

### Actual Behavior

No event is triggered, not the `new-window` on the webview, nor the `setWindowOpenHandler` on it's webContents. Other link events and window.open do show up in the handler and the new-window event listener, so that's not it either.

### Additional Information

You can make it work again for now by disabling the unreliable "nativeWindowOpen" on both the BrowserWindow and it's containing webview.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Jelmerro** [comment]
Here we go, simple enough. https://gist.github.com/f0b5139abb8ca10b01f69a084a6d4667 There isn't any magic to this, just any basic webview and clicking on `target="_blank"` links will fail inside webviews if `nativeWindowOpen` is enabled.

If you middle click on the "new view" link in the webview you will see the event, if you click using the left mouse nothing happens.

**Comment by nornagon** [comment]
I can repro. Here's a slightly altered gist that fixes the usage of `once` in the above gist (not sure what the intention was there): https://gist.github.com/0bf4b9b806976ab31e428899dd93ce35

middle-clicking or cmd+clicking results in the window-open handler being called, but a plain click doesn't.

**Comment by Jelmerro** [comment]
Sorry, that shouldn't have been there, it's quite late here and also the reason I didn't bother with a gist in the original issue. Glad you figured it out, hope we can see this resolved soon so I no longer have to disable nativeWindowOpen :slightly_smiling_face:

**Comment by nornagon** [comment]
Looks like this is because the `<webview>` is lacking the `allowpopups` attribute, which seems to be intended behavior (added in #9568):

https://github.com/electron/electron/blob/eb955af459b560d633aad0f0e8b018a5aab32071/shell/browser/electron_browser_client.cc#L720-L723

Adding `allowpopups` to the webview causes left-click to work.

It seems debatable whether cmd+click / middle-click should work when `allowpopups` is disabled.

**Comment by nornagon** [comment]
the following table summarises the current behavior for various kinds of window-open events on both `nativeWindowOpen: false` (old behavior) and `nativeWindowOpen: true` (new behavior).

|nativeWindowOpen|allowpopups|type||new-window event?|window shown?|
|-|-|-|-|-|-|
|false|false|window.open()||:white_check_mark:|:x:|
|false|false|_blank click||:white_check_mark:|:x:|
|false|false|cmd+click||:white_check_mark:|:x:|
|false|true|window.open()||:white_check_mark:|:white_check_mark:|
|false|true|_blank click||:white_check_mark:|:white_check_mark:|
|false|true|cmd+click||:white_check_mark:|:white_check_mark:|
|true|false|window.open()||:x:|:x:|
|true|false|_blank click||:x:|:x:|
|true|false|cmd+click||:white_check_mark:|:x:|
|true|true|window.open()||:white_check_mark:|:white_check_mark:|
|true|true|_blank click||:white_check_mark:|:white_check_mark:|
|true|true|cmd+click||:white_check_mark:|:white_check_mark:|

**Comment by nornagon** [comment]
I think we should resolve this by emitting `new-window` in all cases, i.e. changing the `nativeWindowOpen: true` behavior to match the `nativeWindowOpen: false` behavior. We can do this by refactoring the check for `ShouldDisablePopups` to happen _after_ emitting the event.

**Comment by nornagon** [comment]
Thinking about this a little more, I think we should actually suppress the `new-window` event (and the call to the window-open handler) for cmd+click when `allowpopups` is false. It makes the most sense to have the `allowpopups=no` mean "this webview is never allowed to spawn a new window", and also to have `new-window` mean "we are about to create a new window".

In the non-nativeWindowOpen situation, "new-window" does not always indicate that a new window will be created, since if `allowpopups=no` is set, the window creation will be suppressed.

In the nativeWindowOpen situation, the above is true only for cmd+click events—for regular clicks on `_blank` links and for `window.open()` calls, there is no event emitted.

Roughly speaking, `allowpopups=no` should be equivalent to `setWindowOpenHandler(() => ({action: 'deny'}))`.

If your goal is to intercept the creation of new windows, the right way to go is to set `allowpopups` and install a window-open handler via `setWindowOpenHandler`. The `disposition` parameter in the event details can help to distinguish between various kinds of window open events.

The change we should make, then, is to stop emitting `new-window` / calling the window-open handler when cmd+clicking in a webview with `allowpopups=no`.

**Comment by Jelmerro** [comment]
I think this is still relevant, because `allowpopups` is discouraged (see screenshot), and it's currently the only way to get all the new window events in the first place. There seems to be no easy way to prevent all new windows, while still getting an event for them to do a custom action.
![image](https://user-images.githubusercontent.com/1696674/194012794-9ef39a58-3a11-4379-85dc-093f933098ed.png)

**Comment by Jelmerro** [comment]
Stillan issue.

**Comment by Jelmerro** [comment]
Still an issue.

**Comment by mactanner** [comment]
Still an issue. Especially because the WebContents new-window event was removed with version 22.

**Comment by brand-it** [comment]
Still, an issue with what that last guy said.

**Comment by surya-teja444** [comment]
> I can repro. Here's a slightly altered gist that fixes the usage of `once` in the above gist (not sure what the intention was there): https://gist.github.com/0bf4b9b806976ab31e428899dd93ce35
> 
> middle-clicking or cmd+clicking results in the window-open handler being called, but a plain click doesn't.

I really wanna thank you, i have been searching for this since a week, finally i got a solution from you. Really thank you.

**Comment by bytemain** [comment]
Meet the same situation, and cannot find a solution fot this..

**Comment by deeivihh** [comment]
Any news on this?

**Comment by surya-teja444** [comment]
yes somehow i got the solution:
these event below "did-attach-webview" will trigger when we click a link
with __blank
iam denying that action, and iam sending a new event to my index.html and
then using that event i will create a new tab manually
mainWindow.webContents.on("did-attach-webview", (_, contents) => {
        contents.setWindowOpenHandler((details) => {
            mainWindow.webContents.send('new-tab-url', details?.url)
            return { action: 'deny' }
        })
 })

**Comment by Veiintc** [comment]
> Meet the same situation, and find a solution for this:遇到同样的情况，并为此找到解决方案：
> 
> document.addEventListener('click', (e) => {
>   const target = e.target?.closest('a');
>   if (target && target.target === '_blank') {
>     e.preventDefault();
>     const { href } = target;
>     // replace current href
>     window.location.href = href;
>   }
> });

How to handle download href?

**Comment by GrenAnHao** [comment]
/webview/preload.js

if (!window.__clickInterceptorInstalled) {
  const handleClick = (e) => {
    const anchor = e.target?.closest?.('a[href]')
    if (!anchor) return

    if (anchor.target === '_self') {
      e.preventDefault()
      e.stopPropagation()
      window.location.href = anchor.href
    } else if (anchor.target === '_blank') {
      e.preventDefault()
      e.stopPropagation()
      ipcRenderer.send('new-window', anchor.href)
    }
  }
  document.addEventListener('click', handleClick, true)
  window.__clickInterceptorInstalled = true
}

**Comment by GrenAnHao** [comment]
ok 完整的解决方式我已经实现了  webview.webcontents.webPreferences.contextIsolation = false 

自行处理新开窗口



 app.on('web-contents-created', (_, contents) => {
    switch (contents.getType()) {
      case 'window': {
        contents.on('will-attach-webview', (_, webPreferences) => {
          const p = join(__dirname, '../preload/webview.js')
          webPreferences.preload = `${p}`
          webPreferences.sandbox = false
          webPreferences.nodeIntegration = false
          webPreferences.webSecurity = true
          webPreferences.contextIsolation = false
          webPreferences.allowRunningInsecureContent = false
        })
        break
      }
      case 'webview': {
        console.log('原生 WebView 创建请求', contents.id)
        break
      }
    }
  })



/webview/preload.ts
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// preload.js
import { contextBridge, ipcRenderer } from 'electron'
import { electronAPI } from '@electron-toolkit/preload'

if (!window.__clickInterceptorInstalled) {
  const handleClick = (e) => {
    const anchor = e.target?.closest?.('a[href]')
    if (!anchor) return

    if (anchor.target === '_self') {
      e.preventDefault()
      e.stopPropagation()
      window.location.href = anchor.href
    } else if (anchor.target === '_blank') {
      e.preventDefault()
      e.stopPropagation()
      ipcRenderer.send('new-window', anchor.href)
    }
  }
  document.addEventListener('click', handleClick, true)
  window.__clickInterceptorInstalled = true
}
window.addEventListener('load', () => {
  console.log('监听页面已完全加载！')
  try {
    Object.defineProperty(window, 'open', {
      value: function (url, target, windowFeatures) {
        console.log('open', url, target, windowFeatures)
        if (url) {
          ipcRenderer.send('new-window', url)
        }
        return null
      },
      writable: true,
      configurable: true
    })
  } catch (e) {
    console.warn('无法重新定义 window.open:', e)
  }
})

contextBridge.exposeInMainWorld('electron', electronAPI)
window.electron = electronAPI
console.log('preload.js loaded')

**Comment by GrenAnHao** [comment]
if (!window.__clickInterceptorInstalled) {
  const handleClick = (e) => {
    let anchor = e.target?.closest?.('a[href]')
    if (!anchor) {
      const path = e.composedPath ? e.composedPath() : [e.target]
      anchor = path.find((el) => el.nodeType === 1 && el.tagName === 'A' && el.hasAttribute('href'))
      if (!anchor) return
    }
    if (anchor.target === '_self') {
      e.preventDefault()
      window.location.href = anchor.href
    } else if (anchor.target === '_blank') {
      e.preventDefault()
      newWindow(anchor.href)
    }
  }
  document.addEventListener('click', handleClick, true)
  window.__clickInterceptorInstalled = true
}
window.addEventListener('load', () => {
  try {
    Object.defineProperty(window, 'open', {
      value: function (url, target, windowFeatures) {
        console.log('open', url, target, windowFeatures)
        if (url) {
          newWindow(url)
        }
        return null
      },
      writable: true,
      configurable: true
    })
  } catch (e) {
    console.warn('无法重新定义 window.open:', e)
  }
})
@nornagon

**Comment by Sytten** [comment]
This is still an issue 4 years later
