### ISSUE TITLE
[Bug]: Black Screen is captured in Ubuntu 21.04 x64 bit Wayland.

### ISSUE THREAD

**Issue by hdevelope** [electron/electron#31588]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04 Wayland

### What arch are you using?

x64

### Expected Behavior

Black Screen should not be captured.  The desktop screen should be captured instead of the Black Screen in Ubuntu 21.04 x64 bit Wayland.

### Actual Behavior

Instead of Desktop Screen, the Black Screen is captured in Ubuntu 21.04 x64 bit Wayland.

### Testcase Gist URL

https://github.com/hdevelope/wayland-blackscreen

### Additional Information

The Desktop screen is captured only in Ubuntu 21.04 X64 Xorg. 

Steps to reproduce

Download the repository, https://github.com/hdevelope/wayland-blackscreen
npm install 
npm start
Click on the capture button after the window is launched.
The image file of the captured screen is found in the root directory of the project.

**Comment by vchernin** [comment]
Ensure you're building with `rtc_use_pipewire=true`, and you pass `--enable-features=WebRTCPipeWireCapturer` at runtime.

**Comment by dbradleyfl** [comment]
@vchernin will this solution cause Ubuntu 20.04 users without pipewire to have issues?

**Comment by vchernin** [comment]
Ubuntu 20.04 does not include working PipeWire + portal screen sharing support, 21.04 was the first release to get that.

Regardless, these flags should not regress anything for Xorg users. So Ubuntu 20.04 will be unaffected since that uses Xorg.

**Comment by iMonZ** [comment]
> Ensure you're building with `rtc_use_pipewire=true`, and you pass `--enable-features=WebRTCPipeWireCapturer` at runtime.

Can the build options please be enabled by default?

**Comment by vchernin** [comment]
> Can the build options please be enabled by default?

`rtc_use_pipewire` [is enabled by default if using sysroot](https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/webrtc.gni;l=138?q=rtc_use_pipewire&ss=chromium). But some builds might explictly disable `rtc_use_pipewire`.

> `--enable-features=WebRTCPipeWireCapturer`

This is a runtime option, not a build option. A few apps on Flathub and elsewhere enable this by default at runtime anyway. It is not on by default yet in Chromium, probably since there are still bugs.

**Comment by Mushoz** [comment]
Sharing your screen under wayland via Pipewire is broken for xdg-desktop-portal  version 1.10 or higher. This was recently fixed in Chromium with the following MR: https://webrtc-review.googlesource.com/c/src/+/232329/

My question:
1. Is this fix already included in Electron as well?
2. Which electron versions have this included?

I am using a downstream project (Teams-for-linux: https://github.com/IsmaelMartinez/teams-for-linux) which is built on Electron, and from what I can see they are currently using Electron 15.3.0. I am currently experiencing the black screen issue there as well. They are also using the WebRTCPipeWireCapturer flag at runtime by default as you can see in the code here: https://github.com/IsmaelMartinez/teams-for-linux/search?q=WebRTCPipeWireCapturer

Would love to know if the upstream chromium patch is already included in Electron. Thanks!

**Comment by Mushoz** [comment]
To answer my own question: This fix is included in Chromium 96. From what I understand from Wikipedia, Electron v16+ is based on Chromium 96, which means that this issue should already be fixed in Electron, and downstream needs to update.

**Comment by SarathKmrM** [comment]
> Ensure you're building with `rtc_use_pipewire=true`, and you pass `--enable-features=WebRTCPipeWireCapturer` at runtime.

Can you please explain a bit more. Where should i use this ?
This is the command i am using for creating build.
ng build --prod --base-href ./ && electron-packager . \"appName\" --overwrite --asar --platform=linux --arch=x64 --prune=true --out=./dist/electron-build --executableName=appName

I tried passing "--enable-features=WebRTCPipeWireCapturer" in above command, but still getting issue.
I am using Electron 16.0.6 with Angular 12.

Can you provide a example command or code to fix this solution.
Thank you in advance .

**Comment by Mushoz** [comment]
@SarathKmrM passing `--enable-features=WebRTCPipeWireCapturer` at runtime means that you pass said switch when running the application that you have build. You do NOT use that switch when building the application.

**Comment by SarathKmrM** [comment]
> @SarathKmrM passing `--enable-features=WebRTCPipeWireCapturer` at runtime means that you pass said switch when running the application that you have built. You do NOT use that switch when building the application.

Thanks for reply @Mushoz 
app.commandLine.appendSwitch('enable-features', 'WebRTCPipeWireCapturer');
added this code in main.js. Now i am not getting black screenshot. However i am facing other issues.
I am able to take screenshot on ubuntu 18, ubuntu 20 and windows 10 with my app. But still its not working in Ubuntu 22 LTS.
![Screenshot from 2022-04-27 11-16-34](https://user-images.githubusercontent.com/95172957/165451192-9c7c0f9a-b533-4f3e-b54d-c41b84876f4f.png)

I am getting this popup every time i tried to take screenshot from my app. Even after granting permission it seems to be not working.
I think desktopCapturer is still not working for Ubuntu 22 ?

Let me know your thoughts. Thanks.
