### ISSUE TITLE
[Bug]: Can't Create BrowserWindow Larger Than Screen Width

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#32773]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Creating a `BrowserWindow` with width larger than the screen creates a window with the requested width.

### Actual Behavior

Creating a `BrowserWindow` with width larger than the screen creates a window where the width is clipped to the screen width.

### Testcase Gist URL

https://gist.github.com/dsanders11/dbeb5222566ebe7f01dc72b93884202f

### Additional Information

Setting the width to larger than the screen width after creating the window, using `BrowserWindow.setSize`, does work. It should either also work from the `BrowserWindow` constructor, or the documentation should mention that it doesn't.

**Comment by zcbenz** [comment]
Sometimes apps may calculate window bounds wrong and create a window that users can not close, so it is intentional that the window can not be larger than screen.

The `enableLargerThanScreen` option is intended to turn off this behavior, it is only implemented on macOS but we can surely implement it also on Windows.

**Comment by dsanders11** [comment]
@zcbenz, in my testing on macOS, `enableLargerThanScreen` only affects `BrowserWindow.setSize`, not the options given to the constructor.

For example:

```javascript
const mainWindow = new BrowserWindow({
  width: 1500,
  height: 600,
  x: 500,
  y: 200,
  enableLargerThanScreen: true,
  webPreferences: {
    preload: path.join(__dirname, 'preload.js')
  }
})
```

Results in a window with the following bounds on my MacBook Pro: `{ x: 0, y: 200, width: 1440, height: 600 }`

**Comment by zcbenz** [comment]
It is a bug that should be fixed then.

**Comment by dsanders11** [comment]
Do you want to put the behavior behind the `enableLargerThanScreen` option as you mentioned before? So fix it on all platforms, but only allow larger than screen with the width in the constructor options when `enableLargerThanScreen` is true?

**Comment by zcbenz** [comment]
I think from user's perspective, `enableLargerThanScreen: true` should be a clear sign that they want to be able to set the window to arbitrary size. So with `enableLargerThanScreen: true`,  setting size in constructor and calling `setSize` should both be able to set window size larger than screen.

**Comment by pushkin-** [comment]
repros in latest stable (21)

**Comment by pushkin-** [comment]
gist crashes for me in v21 and v22, but going to assume this wasn't fixed, so bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
bump

**Comment by pushkin-** [comment]
related to [this](https://github.com/electron/electron/issues/20351)?
