### ISSUE TITLE
[Bug]: Native File Drag and Drop icon missing when calling startDrag

### ISSUE THREAD

**Issue by vinceau** [electron/electron#33156]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.10

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2

### What arch are you using?

x64

### Last Known Working Electron version

13.x

### Expected Behavior

When using the native [file drag and drop](https://github.com/electron/electron/tree/main/docs/fiddles/features/drag-and-drop) functionality you have the option to pass in an `icon` to be rendered during the drag (using `event.sender.startDrag`). I would expect the icon to show up when dragging.

### Actual Behavior

Starting from version 14.x onwards the icon no longer shows up when dragging on Windows.

### Testcase Gist URL

https://gist.github.com/925a655be700c7b53ceca6fe56215675
(this gist is literally just taken from the example drag and drop fiddle)

### Additional Information

Using a `NativeImage` for example by calling `nativeImage.createFromPath` does not fix this and such icons are still not visible.

There are many other reports of this on StackOverflow without a fix. For example:
* https://stackoverflow.com/questions/69771882/electron-file-dag-image-not-visible (Posted Oct 29, 2021)
* https://stackoverflow.com/questions/69821469/default-electron-drag-project-not-working-as-intended (Posted Nov 3, 2021)

**Comment by NikhilNarayana** [comment]
This is fixed in 17.0.0 from my testing.

**Comment by Raguna163** [comment]
I'm not having an issue with it missing, but having the same issue as the second stack overflow answer you linked.
https://stackoverflow.com/questions/69821469/default-electron-drag-project-not-working-as-intended
The icon appears oversized and has a fades at the edges Tried it in Electron 19 and still happening after upgrading to 20.
