### ISSUE TITLE
[Bug]: empty URL in `IPCMainEvent.senderFrame.url`

### ISSUE THREAD

**Issue by bpasero** [electron/electron#33800]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.x

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The `IPCMainEvent.senderFrame.url` should never be the empty string.

### Actual Behavior

The `IPCMainEvent.senderFrame.url` is an empty string.

### Additional Information

Steps to reproduce:
* `git clone https://github.com/bpasero/playwright-electron.git`
* `yarn`
* `node index.js`

Notice how this line throws an error: https://github.com/bpasero/playwright-electron/blob/53d16919a89984f7d889102c69b30679495e337e/main.js#L41

This does not reproduce when not running with `playwright` so it is probably related.

//cc @deepak1556

**Comment by MarshallOfSound** [comment]
@bpasero I believe the empty URL actually means the page failed to load and is ending up at `chrome-error://chromewebdata/`.  Basically your custom protocol handler is returning a completely invalid file path and the page is failing to load.

For legacy reasons your preload script will still run on the chrome error page but the URL of that page to most APIs is the empty string.

I fixed up your custom protocol handler in this PR: https://github.com/bpasero/playwright-electron/pull/1

Not sure if your vscode protocol handler has similar issues or not, debugging playwright is kinda tricky I couldn't find an easy way to get main process logs 🤷

**Comment by bpasero** [comment]
Thanks for the prompt follow up, too bad I was unlucky in finding the issue we see in VSCode and the Windows paths are all wrong. 

In VSCode we still see this and it reproduces on macOS too and paths seems to be fine. So I still have to find a way to reproduce this in a minimal sample...

**Comment by bpasero** [comment]
Btw `playwright` prints very detailed logs when setting `export DEBUG=pw:browser`.

**Comment by MarshallOfSound** [comment]
I'd look for a similar cause, maybe listen to the `did-fail-load` event and log out any relevant information.
