### ISSUE TITLE
[Bug]: Border radius doesn't make the window edges rounded

### ISSUE THREAD

**Issue by Toxic48** [electron/electron#35870]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The window should have rounded edges because I made it transparent, removed the frame and added the border radius to the body element of the index.html file.

### Actual Behavior

The corners that should cut off the body element when I use the border radius property actually become white (or whatever color the body background is) instead of transparent.

This issue is also referenced in #22243 but it wasn't solved (or it has appeared again in the new versions).

![Capture](https://user-images.githubusercontent.com/77108700/193347835-69b233fd-cc69-456c-8c23-95e6bac764ff.PNG)

The Electron Fiddle Gist is attached below.

### Testcase Gist URL

https://gist.github.com/989e5ae311fbe95b83ab34754ce8a0d9

**Comment by Zoomhawk** [comment]
I want a to work in this issue

**Comment by Zoomhawk** [comment]
I want a to work on this issue

**Comment by Toxic48** [comment]
> I want a to work on this issue

??

**Comment by radzhiv25** [comment]
Is the issue still open or not

**Comment by Toxic48** [comment]
> Is the issue still open or not

yes, it is still an issue

**Comment by adityachache** [comment]
I tried running your code and yes the border radius doesn't work as expected. But an alternate solution to this can be to wrap your content in a div tag and apply the styles on it

**Comment by Toxic48** [comment]
> I tried running your code and yes the border radius doesn't work as expected. But an alternate solution to this can be to wrap your content in a div tag and apply the styles on it

Yes I already solved my problem by doing exactly that and sonehow worked it around. But this still is a problem, for example if you are showing a remote page on your window (window.loadURL("https://google.com)), and in that case you can edit the page by applying a border radius on the body element via a preload script (which I did in my case and it didn't work). So that's why this problem should be addressed in an update.

**Comment by uday03meh** [comment]
Can I work on this?

**Comment by radzhiv25** [comment]
> > Is the issue still open or not
> 
> yes, it is still an issue

Can I get to work on this issue 
and if just in case it gets resolved will it be counted in the Hacktoberfest PR ??

**Comment by baconbrad** [comment]
Can confirm it is still an issue. Anyone can work on it and submit a PR. Not up to me if it gets merged or not though.

**Comment by xmsz-stu** [comment]
any update?

**Comment by zmzimpl** [comment]
seems it still an issue.
