### ISSUE TITLE
[Bug]: Silent print was incorrect paper layout with webContents.print, but layout was correct when I use print dailog

### ISSUE THREAD

**Issue by tyhour** [electron/electron#39179]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.1

### What operating system are you using?

Windows

### Operating System Version

Window 10 Pro Version 10.0.19045 Build 19045

### What arch are you using?

x64

### Last Known Working Electron version

25.3.1

### Expected Behavior

This preview image I was use with dialog print. It shows exactly width and height that response from my URL. But I want to use with silent print.
![image](https://github.com/electron/electron/assets/21979709/f39bfc04-78bf-423e-822b-18969fbe3f53)

**Here is my code**
```
ipcMain.handle('printComponent', async (_, url, printer_name, copies) => {
    let win = new BrowserWindow({
      show: false,
    });
    win.loadURL(url);
    let _printer = printer_name;
    let list = await win.webContents.getPrintersAsync();
    let check = list.filter((r) => r.name === _printer);
    if (check.length === 0) {
      check = list.filter((r) => r.isDefault);
      if (check.length > 0) {
        _printer = check[0].name;
      }
    }

    win.webContents.on('did-finish-load', () => {
      const printOptions: WebContentsPrintOptions = {
        deviceName: _printer,
        silent: false,
        margins: {
          marginType: 'default',
        },
        landscape: false,
        pagesPerSheet: 1,
        collate: false,
        copies,
      };
      win.webContents.print(printOptions, (success, failureReason) => {
        console.log('Print Initiated in Main...');
        if (!success) console.log(failureReason);
        // win.close();
        mainWindow?.focus();
      });
    });
  });
```

### Actual Behavior

This preview image I was use with silent print. It shows too small that response from my URL.
![image](https://github.com/electron/electron/assets/21979709/d3aee600-ee9d-4d03-9b68-2b6b3e1ba55c)

**Here is my code**
```
ipcMain.handle('printComponent', async (_, url, printer_name, copies) => {
    let win = new BrowserWindow({
      show: false,
    });
    win.loadURL(url);
    let _printer = printer_name;
    let list = await win.webContents.getPrintersAsync();
    let check = list.filter((r) => r.name === _printer);
    if (check.length === 0) {
      check = list.filter((r) => r.isDefault);
      if (check.length > 0) {
        _printer = check[0].name;
      }
    }

    win.webContents.on('did-finish-load', () => {
      const printOptions: WebContentsPrintOptions = {
        deviceName: _printer,
        silent: true,
        margins: {
          marginType: 'default',
        },
        landscape: false,
        pagesPerSheet: 1,
        collate: false,
        copies,
      };
      win.webContents.print(printOptions, (success, failureReason) => {
        console.log('Print Initiated in Main...');
        if (!success) console.log(failureReason);
        // win.close();
        mainWindow?.focus();
      });
    });
  });
```

### Testcase Gist URL

https://gist.github.com/053de2471f74277e60fb908aaa3685ff

**Comment by tyhour** [comment]
Everything work fine with "electron": "^23.1.3" for layout paper printing but I want to upgrade with new version and now I stuck on that problem. Thanks for help

**Comment by tyhour** [comment]
Everything work fine with "electron": "^23.1.3" for layout paper printing but I want to upgrade with new version and now I stuck on that problem. Thanks for help

**Comment by Hedwig188** [comment]
@codebytere Is this broken by the fix #39095?

**Comment by mgalla10** [comment]
If it helps, you can use this gist to easily reproduce the issue: https://gist.github.com/053de2471f74277e60fb908aaa3685ff. Just click Print, save the PDF to any location, and then view it and see how tiny the printed contents are.

**Comment by firsttabz** [comment]
@tyhour i have the same issue with electron@24.6.4 in silent mode, did you know how to solve it?

**Comment by acutus** [comment]
Ran into this as well when trying to upgrade to 25.x (and 26.x). I was able to adjust the output size with the mentioned dpi-setting, but layout still differs from 24.x or non-silent printing. Had to downgrade back to 24.x because of this. E.g. 24.8.3 still works fine with silent printing.

**Comment by lmt20** [comment]
It seems this error still exists until the latest version `27.0.2`. 

The print function with option `{ silent: true }` still works well toward version `24.8.8`, and started having errors on version `25.0.0`, this function starts working again in version `25.3.1` after this fix  #39095 by @codebytere but make another error that causing prints to be very tiny.

 Has anyone solved this problem other than the trick above?

> Setting the dpi:{ horizontal: 600, vertical: 600 } on the printOptions can workaround the issue.

**Comment by testing4teks** [comment]
Is there any update on this?

I'm using Zebra Printer ZD 230 with 4inch X 6inch roll. 

How to calculate the dpi?

With silent: true in print option, is causing prints to be very tiny.

**Comment by Hedwig188** [comment]
My current workaround for windows is to utilize [PrinterResolution](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.printing.printerresolution?view=dotnet-plat-ext-7.0) class get the printer resolution and pass the dpi to the printer to print. I've noticed some printer drivers(Canon generic printer driver) could return dpi values <=0. You'd need to filter them out and only pass the positive one to webContent.print. Otherwise, you could encounter [this issue](https://github.com/electron/electron/issues/39108).

**Comment by Sebastien-Lampazona** [comment]
I have exactly the same issue, and the 300 dpi workaround not working for me.
I had try to use an HTML page and render an <img> with @page css options ... but not better ...

**Comment by aortmannm** [comment]
> My current workaround for windows is to utilize [PrinterResolution](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.printing.printerresolution?view=dotnet-plat-ext-7.0) class get the printer resolution and pass the dpi to the printer to print. I've noticed some printer drivers(Canon generic printer driver) could return dpi values <=0. You'd need to filter them out and only pass the positive one to webContent.print. Otherwise, you could encounter [this issue](https://github.com/electron/electron/issues/39108).

But then you need to switch to C# Code or?

The webContents.gerPrintersAsync() function didn't have the necessary DPI information right?

Have the same problem with 27.1.0

**Comment by Hedwig188** [comment]
> > My current workaround for windows is to utilize [PrinterResolution](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.printing.printerresolution?view=dotnet-plat-ext-7.0) class get the printer resolution and pass the dpi to the printer to print. I've noticed some printer drivers(Canon generic printer driver) could return dpi values <=0. You'd need to filter them out and only pass the positive one to webContent.print. Otherwise, you could encounter [this issue](https://github.com/electron/electron/issues/39108).
> 
> But then you need to switch to C# Code or?
> 
> The webContents.gerPrintersAsync() function didn't have the necessary DPI information right?
> 
> Have the same problem with 27.1.0

Yes, I switched to C# to get the printer resolution and sent back to Electron's webContents.print() function.

**Comment by conteit** [comment]
I have the same issue also on Electron 28.x. 

A thing I was able to discover is that, on Windows, pageSize is interpreted in the wrong way. To be able to print at full page I had to multiply by 10 the width and heights in microns, by means of the `pageSize` parameter.
Instead of doing `webContents.print({silent: true, pageSize: "A4"}, callback)`, I invoked `webContents.print({silent: true, pageSize: {width: 2100000, height: 2970000}}, callback)`.

By means of that, the content is still printed small, but moves to the top-left corner and the print is able to span to the full page. To get to a normal printing size I can set `dpi: {horizontal: 544, vertical: 544}` or, alternatively, apply a CSS `zoom: 750%` on the page content, but that is not the right thing to do. Apart from the insane magnitude of the parameters, AFAIK increasing dpi settings so much could cause the printer to refuse the job, and using zoom breaks the ability to print the same page from a browser.

I also verified that printing the page from Chrome or Chromium doesn't present the same issue, but I struggle to find where the problem is in the Electron code base. It seems like, by doing a `silent` print request, some parameter doesn't get initialized properly.

**Comment by Wexoo** [comment]
Having the same issue, I checked different versions today and can confirm the previous commenters.
Silent printing by version (built with electron-packager v17.1.2 on MacOS and run on Win11 ARM in Parallels Desktop):
25.3.1-29.0.0-alpha.3 -> working but shrunk content on PDF
25.0.0-25.3.0               -> not working at all
24.8.8                           -> working, correct size

Would be great to have this fixed, since 24.x is already end of life, but this forces me to stay on that version.

**Comment by mozainuddin** [comment]
> Having the same issue, I checked different versions today and can confirm the previous commenters. Silent printing by version (built with electron-packager v17.1.2 on MacOS and run on Win11 ARM in Parallels Desktop): 25.3.1-29.0.0-alpha.3 -> working but shrunk content on PDF 25.0.0-25.3.0 -> not working at all 24.8.8 -> working, correct size
> 
> Would be great to have this fixed, since 24.x is already end of life, but this forces me to stay on that version.

Thank you, I downgraded to 24.8.8 and it works perfectly

**Comment by RohitSaroj** [comment]
@codebytere Do we have a timeline or a specific Electron version targeted for fixing this issue?

**Comment by CavenRE** [comment]
I have tried SEVERAL versions and this is still very much an issue.
I have tried everything from Web Print, Image to PDF print, PDF print and NOTHING.
Nothing is working, I think this is not a tiny issue, this a MAJOR issue, to point that if I was aware of this before I started my project, I would of never used Electron, but now I'm locked in trying to solve a bug that shouldn't exist.
This needs way more attention than it is getting now.
Until then, I straight up refuse to use Electron till this is issue CONFIRMED to have been fixed.

I mean my current fix attempt on printing an image is;
`ipcMain.handle('print-image', async (_, imagePath) => {
  let imageWin = new BrowserWindow({ 
    show: false, 
    webPreferences: {
      images: true
    }
  });

  imageWin.loadFile(imagePath);

  return new Promise<void>((resolve, reject) => {
    imageWin.webContents.on('did-finish-load', () => {
      const options: Electron.WebContentsPrintOptions = {
        silent: true,
        landscape: true,
        pageSize: { width: 106000, height: 149000 },
        margins: {
          marginType: 'none' as const,
        },
        pagesPerSheet: 1,
        dpi: {
          horizontal: 300,
          vertical: 300,
        },
        collate: false,
        copies: 1,
      };
      
      imageWin.webContents.print(options, (success, failureReason) => {
        if (success) {
          resolve();
        } else {
          console.error(failureReason);
          reject(new Error(failureReason));
        }
        imageWin.close();
      });
    });
  });
});`

The thing is... I can somewhat get it working. But for some magical reason, everything is stuck at the A4 scale, regardless of what page size I attempt to use or however I try enforce my settings, this one of many and I mean many attempts.
But it simple seems to be impossible to resolve this. I have tried ever version that has said it has "fixed" this issue.

I'm just over it now.

**Comment by michel-smarticket** [comment]
@codebytere any news on this? 
We're stuck on 24.8.8 for quite a while now.

**Comment by nurik24** [comment]
I have the same issue, added 
`dpi: {
          horizontal: 600,
          vertical: 600,
        },`
its working for now, but would be great to have it fixed. I'm on version 26.2.2

**Comment by sridharpg** [comment]
This issue is actually not fixed. The pdf is generated fine but the prints are not triggered with proper layout in silent mode. #41928 explains it.

**Comment by EL-MEHDI-ESSAADI** [comment]
Yes, it's not fixed yet, there is still the same issue in 31.0.0-alpha.2

**Comment by sridharpg** [comment]
For now, I have resorted back to https://www.npmjs.com/package/pdf-to-printer. While its not perfect, it helps me with most of the cases. I faced an issue with orientation, and only for Windows, I had to provide an additional orientation setting in my app, which overcame this issue.

I think this ticket needs to be reopened till the printing issue is resolved.

**Comment by LukasZubal** [comment]
The patch does work for me on Windows 11. Electron 30.0.8 (with Quasar framework, vite). Both dev and prod are ok. Printer Brother HL-L2442DW connected throught USB (driver installed automatically by window)

**Comment by sridharpg** [comment]
The issue doesn't show up on all printers afaik. I found a different solution. If we pass the right page dimensions, prints came out right on the Zebra printers(tested on zd621 and zc10l).

```
pageSize: {
    height: dim.pageHeight*1000,
    width: dim.pageWidth*1000
}
```

**Comment by coverstart** [comment]
According to my tests, I found that the print slient is too small, which is may caused by  WebContentsPrintOptions.scaleFactor, WebContentsPrintOptions.scaleFactor = WebContentsPrintOptions.scaleFactor * 100, which can solve the problem of printing too small content

**Comment by cah-eric-waight01** [comment]
Bump to fix this

**Comment by alexkramer98** [comment]
This is still an issue in v33.

**Comment by EL-MEHDI-ESSAADI** [comment]
Hello everyone, the best solution that I found is showing a pdf preview of the document that I want to print, the preview will have a print button by default, that can print the document perfectly

### Here is how I show the pdf preview

```
/**
 * IPC handler for previewing a component/webpage as PDF
 * @param {PrintData} data - Configuration data for PDF preview
 * @param {string} data.url - The URL of the document (html url) to preview
 * @param {boolean} data.landscape - Whether to use landscape orientation
 * @param {string} data.pageSize - The page size for the PDF (e.g., 'A4', 'Letter')
 * @returns {Promise<string>} A promise that resolves with success/error message
 */
ipcMain.handle("printComponentToPDF", async (_, data: PrintData) => {
  // Create hidden browser window for PDF generation
  const win = new BrowserWindow({
    title: "Preview",
    show: false,
    autoHideMenuBar: true,
  });

  win.loadURL(data.url);

  const response = await new Promise((res, rej) => {
    // Wait for the page to load before generating PDF
    win.webContents.once("did-finish-load", async () => {
      try {
        // Generate PDF with specified settings
        const pdf = await win.webContents.printToPDF({
          printBackground: true,
          margins: {
            marginType: "printableArea",
          },
          landscape: data.landscape,
          pageSize: data.pageSize,
        });

        // Convert PDF to base64 for preview
        const buf = Buffer.from(pdf);
        const pdfData = buf.toString("base64");

        // Create data URL and show preview window
        const url = "data:application/pdf;base64," + pdfData;
        win.webContents.on("dom-ready", () => {
          win.show();
          win.setTitle("Preview");
        });
        win.loadURL(url);
        res("Print successful");
      } catch (error) {
        rej(error);
      }
    });
  });

  return response;
});
```

### Here is how I generate data.url 

```
function getElementContentUrl(target: HTMLElement): string | null {
    console.log("generating URL for element content...");

    const data = target.outerHTML;
    if (!data) return null;

    const fullHtml = `
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="utf-8">
                <title>Element Content</title>
            </head>
            <body>
                ${data}
            </body>
        </html>
    `;

    const blob = new Blob([fullHtml], { type: "text/html;charset=utf-8" });
    return URL.createObjectURL(blob);
}
```

**Comment by NoxFly** [comment]
Just had the same issue (v34).

I tested a lot of things.

The exact same parameters with silent: true or false was not working / working, even if window was hidden or not.

I fixed this with a setTimeout on 2 things :
- First, wait a bit before closing the window
- Secondly and most important for silent: true, was to wait a bit after the `did-finish-load` event.

I put a lot of seconds to be sure that would work, maybe that can vary between networks and printers : 

```ts
const win = new BrowserWindow({
  show: false,
});

const b64 = `data:application/pdf;base64,${pdf}`;
win.loadURL(b64);

win.webContents.on('did-finish-load', () => {
    setTimeout(() => {
        win.webContents.print({
            silent: true,
            color: true,
            copies: 1,
            pageSize: 'A4',
            printBackground: false,
            collate: true,
            margins: {
                marginType: 'default'
            },
            duplexMode: 'simplex',
            dpi: {
                horizontal: 600,
                vertical: 600
            },
            landscape: false,
            pagesPerSheet: 1,
        }, (success, failureReason) => {
            if(!success) {
                console.log(failureReason);
                win.close();
                return;
            }

            console.info('Document printed');

            setTimeout(() => {
                win.close();
            }, 5000); // maybe a fix (to be sure it does not close too fast)
        });
    }, 3000); // fix
});
```

I tried with different events to try to avoid using a `setTimeout` (`dom-ready`, `did-frame-finish-load`) but all were firing before `did-finish-load` event and printed blank sheet.

**Comment by sid-tmbill** [comment]
+1

**Comment by Seashell113** [comment]
bump
but also can't work in 24.8.8

**Comment by hiagodotme** [comment]
I have this problem, after updating my electron my flowers stopped...

**Comment by hiagodotme** [comment]
@Seashell113 Did you manage to get around it?

**Comment by VaporFan** [comment]
Any solution for this? This bring good web app become weird with "simple" print function not work as expected by noob users. 2025 and web based automatic printing still hurts.

**Comment by hiagodotme** [comment]
@VaporFan the only solution that worked for me unfortunately was downgrading the electron version.

**Comment by mozainuddin** [comment]
It is working fine for me on "electron": "^36.4.0"

```
const filteredPrinterConfig = {
  silent: true,
  printBackground: false,
  deviceName: "", 
  color: false,
  copies: 1
};

if (isThermalPrint) {
  filteredPrinterConfig.landscape = false;
  filteredPrinterConfig.margins = {
    marginType: "custom",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0
  };
  filteredPrinterConfig.dpi = { horizontal: 203, vertical: 203 };
  filteredPrinterConfig.pageSize = {
    width: 72100,
    height: 327600
  };
}

printWindow.webContents.print(filteredPrinterConfig, (success, errorType) => {
  if (!success) {
    console.warn("Print failed");
    event.reply("print:failed", {
      success: false,
      message: errorType || "Unknown print error",
    });
  } else {
    event.reply("print:success", { success: true });
  }
});
```
