### ISSUE TITLE
[Bug]: Electron 29. "Cannot Find Packages" when targeting ESM

### ISSUE THREAD

**Issue by johnlindquist** [electron/electron#41241]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.0-beta.5

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

28

### Expected Behavior

Packages should be found

## Reproduce

You can use this repo to reproduce (it just followed the steps below): https://github.com/johnlindquist/electron-29

- `npm create @quick-start/electron`
- Follow `esm` guide
- install `electron-log` and use it in main/index.ts: https://github.com/johnlindquist/electron-29/blob/main/src/main/index.ts#L5
- install Electron 29 `npm i electron@beta` (29.0.0-beta.5 as of today)

### `npm run dev`

Works fine

### `npm run build:mac`

- Successfully builds
- open `./dist/mac-arm64/foo.app`

Your run into a `Cannot find package`, "electron-log" error.

```
Uncaught Exception:
Error: Cannot find package '/Users/johnlindquist/dev/electron-29/dist/mac-arm64/electron-29.app/Contents/Resources/app.asar/node_modules/electron-log/package.json' imported from /Users/johnlindquist/dev/electron-29/dist/mac-arm64/electron-29.app/Contents/Resources/app.asar/out/main/index.mjs
Did you mean to import electron-log/src/index.js?
at legacyMainResolve (node:internal/modules/esm/resolve:189:26)
at packageResolve (node:internal/modules/esm/resolve:783:14)
at moduleResolve (node:internal/modules/esm/resolve:845:20)
at defaultResolve (node:internal/modules/esm/resolve:1050:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
at link (node:internal/modules/esm/module_job:84:36)
```
![CleanShot 2024-02-03 at 09 41 14](https://github.com/alex8088/electron-vite/assets/36073/aeebc0e3-f817-4391-99f3-5f9e23cb51ce)

## Fix
Downgrade to Electron 28, build works fine again.

### Electron-Vite Version

2.0.0

### Electron Version

29.0.0-beta.5

### Vite Version

5.0.11

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

### Additional Information

I originally reported this here: https://github.com/alex8088/electron-vite/issues/401

But this they told me this is an Electron issue

**Comment by codebytere** [comment]
hmm - i cloned your repo, installed deps, and ran `npm run build:mac` and I get:

```
electron-29 on git:main ❯ npm run build:mac                                   6:01PM

> electron-29@1.0.0 build:mac
> electron-vite build && electron-builder --mac --config

vite v5.0.12 building SSR bundle for production...
✓ 2 modules transformed.
out/main/index.mjs  1.71 kB
✓ built in 37ms
vite v5.0.12 building SSR bundle for production...
✓ 1 modules transformed.
out/preload/index.mjs  0.38 kB
✓ built in 5ms
vite v5.0.12 building for production...
✓ 32 modules transformed.
../../out/renderer/index.html                   0.52 kB
../../out/renderer/assets/icons-p39i8CQ2.svg    9.06 kB
../../out/renderer/assets/index-ME2HaU7H.css    2.88 kB
../../out/renderer/assets/index-ZHdq04n_.js   228.87 kB
✓ built in 388ms
  • electron-builder  version=24.9.1 os=23.2.0
  • loaded configuration  file=/Users/codebytere/Developer/repros/electron-29/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=arm64 electron=29.0.0-beta.5 appOutDir=dist/mac-arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v29.0.0-beta.5/electron-v29.0.0-beta.5-darwin-arm64.zip size=95 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v29.0.0-beta.5/electron-v29.0.0-beta.5-darwin-arm64.zip duration=27.574s
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, it could cause some undefined behaviour, e.g. macOS localized description not visible, see https://electron.build/code-signing allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found
  • building        target=macOS zip arch=arm64 file=dist/electron-29-1.0.0-arm64-mac.zip
  • building        target=DMG arch=arm64 file=dist/electron-29-1.0.0.dmg
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • building block map  blockMapFile=dist/electron-29-1.0.0.dmg.blockmap
  • building block map  blockMapFile=dist/electron-29-1.0.0-arm64-mac.zip.blockmap
  ```
  
  Are there any steps I might have missed?

**Comment by johnlindquist** [comment]
@codebytere The error doesn't show until after you attempt to open the packaged app:


![CleanShot 2024-02-05 at 10 48 22](https://github.com/electron/electron/assets/36073/b5068bad-c3a9-40be-a629-72099e0ff4ab)

**Comment by codebytere** [comment]
🤦🏻‍♀️  sorry, you're totally right. I see the issue and can repro it - this _may_ be solved in https://github.com/electron/electron/pull/41209 but i can follow up and check.

**Comment by johnlindquist** [comment]
@codebytere awesome, thanks. Let me know if there's anything else I can do to help.

**Comment by johnlindquist** [comment]
@codebytere I just tried on [v29.0.0-beta.6](https://releases.electronjs.org/release/v29.0.0-beta.6) which says it has the original-fs fix, but I'm getting the same error.

**Comment by codebytere** [comment]
I think i've tracked this to https://github.com/nodejs/node/pull/48325 via https://github.com/electron/electron/commit/9c94fd7afb4706c2d2228a455f0874a0370cfe1d - looking a bit more

**Comment by undergroundwires** [comment]
Thanks for the fix @codebytere, I can still reproduce this using latest electron (`29.1.4`), did this bug creep in again somehow?

**Comment by kylekirkby** [comment]
> Thanks for the fix @codebytere, I can still reproduce this using latest electron (`29.1.4`), did this bug creep in again somehow?

Yh, we're seeing this too in `29.1.4`

**Comment by undergroundwires** [comment]
I found out that I only get this when I import it using `/main` alias such as:
    
```mjs
import log from "electron-log/main";
```

Importing only from `electron-log` does not yield this error:
    
```mjs
import log from "electron-log";
```

**Comment by alex8088** [comment]
@codebytere Electron ESM loader cannot correctly resolve subpath modules.
