### ISSUE TITLE
[Bug]: In version 31.0.1 ReferenceError: Response is not defined

### ISSUE THREAD

**Issue by Xing1P** [electron/electron#42478]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows11

### What arch are you using?

x64

### Last Known Working Electron version

30.0.6

### Expected Behavior

The Response  can be used normally.

### Actual Behavior

![Screenshot (14)](https://github.com/electron/electron/assets/13740546/ada33213-676a-4f3d-9a8a-214649a66f34)
ReferenceError: Response is not defined

**Comment by gandhiomkar** [comment]
could you please provide the following additional information:

1.Code Snippet: It would be helpful if you could share the code snippet where Response is being declared and used within the downloadfile-worker.js file. This will allow us to understand how Response is being utilized in the context of the web worker.

2.Dependencies: Are you relying on any third-party libraries or dependencies within the web worker script? If so, please provide details about these dependencies, especially if they are related to handling HTTP requests or responses.

**Comment by codebytere** [comment]
Already fixed in https://github.com/electron/electron/pull/42419

**Comment by Xing1P** [comment]
.then(stream => {new Response(stream)})
in Renderer is working but not defined in Worker

**Comment by Xing1P** [comment]
> could you please provide the following additional information:
> 
> 1.Code Snippet: It would be helpful if you could share the code snippet where Response is being declared and used within the downloadfile-worker.js file. This will allow us to understand how Response is being utilized in the context of the web worker.
> 
> 2.Dependencies: Are you relying on any third-party libraries or dependencies within the web worker script? If so, please provide details about these dependencies, especially if they are related to handling HTTP requests or responses.

const fs = require('fs');
//const request = require('request');
self.onmessage = async(e)=>{

    let info = e.data;
    let isCancel = info.isCancel;
    if(isCancel){
        closeWorker();
        return;
    }
    let receivedLength = 0;
    let lastProgressSent = 0;
    fetch(info.url)
    .then(response => {
        const contentLength = + response.headers.get('Content-Length');
        const reader = response.body.getReader();
        return new ReadableStream({
          start(controller) {
            return pump();
            function pump() {
              return reader.read().then(({ done, value }) => {
                // When no more data needs to be consumed, close the stream
                if (done) {
                  controller.close();
                  return;
                }
                receivedLength += value.length;
                let progress = receivedLength / contentLength;
                let finishedPercentage = parseFloat((progress * 100).toFixed(2));
                if(finishedPercentage > lastProgressSent + 0.2){
                    lastProgressSent = finishedPercentage;
                    self.postMessage({progress: progress, isDone: false});
                }
                // Enqueue the next data chunk into our target stream
                controller.enqueue(value);
                return pump();
              });
            }
          }
        })
      })
      .then(stream => {new Response(stream)})
      .then(response => response.blob())
      .then(blob => {
        self.postMessage({progress: 0.99, isDone: true, blob: blob});
      })
      .catch(err=>{
        self.postMessage({progress: 0, isDone: false, error: err});
    });
};

**Comment by Xing1P** [comment]
> Already fixed in #42419

You sad fixed, but it still the same in version 31.0.1 , 31.0.2,
