### ISSUE TITLE
macOS: dialog.showOpenDialog fails to show custom macOS packages (LSTypeIsPackage) when filtered by extension in Electron 36.2.0+ (worked in 35.7.5; 36.0.0 showed all files)

### ISSUE THREAD

**Issue by jjeff** [electron/electron#48191]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

36.2.0+ (including latest)

### What operating system(s) are you using?

macOS

### Operating System Version

15.5 (Sequoia)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

35.7.5

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

When using dialog.showOpenDialog() with filters: [{ name: 'rich text files', extensions: ['rtf', 'rtfd'] }], the open panel should show and allow selection of custom macOS bundles registered by the an (e.g., .rtf registered by Text Edit) where the document type has LSTypeIsPackage = true.

### Actual Behavior

•	36.0.0: filters are ignored — all files are visible/selectable. (Matches issue #46883.)
•	36.2.0+ (36.2.0, 36.7.x): no files are selectable for custom bundles; the panel shows zero matching items for .rtf/.rtfd, even though these bundles exist in the folder and are recognized by Finder. Interestingly, .app bundles can be filtered/shown (likely due to the fix in PR #47825 for app → modern bundle UTType mapping).

### Testcase Gist URL

https://gist.github.com/3afd1a232bdd7c2595ddb2cc885dcc98

### Additional Information

You'll need to create a .rtf file using Text Edit. From the "Format" menu, select "Rich Text" and save the file.

**Comment by codebytere** [comment]
@jjeff yeah, I'd guess this is the same root issue as the one linked above - i can take a look when I have a chance.

**Comment by jjeff** [comment]
> [@jjeff](https://github.com/jjeff) yeah, I'd guess this is the same root issue as the one linked above - i can take a look when I have a chance.

Thanks! My app creates its own package folders (by creating its own [CFBundleDocumentTypes](https://developer.apple.com/documentation/bundleresources/information-property-list/cfbundledocumenttypes)), and this issue is blocking users from opening them. 🙏

**Comment by hopejr** [comment]
The fix in #47825 merely treated things differently for .app bundles, but didn't address the underlying issue of package types. In issue #47825 I suggested that maybe an additional parameter should be added to the filter for packages, so that the proper conformingToType can be used:
```
UTType* utt = [UTType typeWithFilenameExtension:@(ext.c_str())
                            conformingToType:UTTypePackage];
```
In my mind, this additional parameter would be the easiest and most straightforward solution to this problem, instead of the current if statement that only looks at .app extensions.

**Comment by codebytere** [comment]
@hopejr 
> In issue https://github.com/electron/electron/pull/47825 I suggested

this links to a PR without any comments from you - did you mean to link something else?

**Comment by hopejr** [comment]
Sorry, I didn't realise I pasted the PR number instead of the issue number (it's not supposed to be the same as the other number!). The issue number is #47815 (only a single digit different).

Edit: specific comment: https://github.com/electron/electron/issues/47815#issuecomment-3084355684

**Comment by codebytere** [comment]
@jjeff I think i'm missing something here. I:

1. Used TextEdit to save a new document `test.rtf` to my desktop
2. Ran the provided Fiddle Gist using 36.2.1 and several other new versions

However, I see:

<img width="859" height="639" alt="Image" src="https://github.com/user-attachments/assets/3c23fc25-1489-465a-943a-180d9c666530" />

it lets me open this just fine.

**Comment by jjeff** [comment]
> [@jjeff](https://github.com/jjeff) I think i'm missing something here. I:
> 
> 1. Used TextEdit to save a new document `test.rtf` to my desktop
> 2. Ran the provided Fiddle Gist using 36.2.1 and several other new versions

@codebytere Ah! Okay. I'm learning about the difference between Text Edit's .rtf files (which are flat) and .rtfd files (which are packages). We want to create .rtfd.

Easy ways to create a .rtfd file

1. Using TextEdit
	1.	Open TextEdit on your Mac.
	2.	Create a new Rich Text document (Format → Make Rich Text if it defaults to plain text).
	3.	Type something in the document.
	4.	Drag in an image (or other file). TextEdit will automatically convert it to an .rtfd package.
	5.	Save the file — choose File → Save, and make sure the format is Rich Text with Attachments (.rtfd).

You’ll now have a .rtfd package in Finder.

----

<img width="912" height="712" alt="Image" src="https://github.com/user-attachments/assets/85cdc6b7-aed1-46a0-accb-1d8be8372e06" />

**Comment by jjeff** [comment]
@codebytere Friendly nudge. 🙂 

This is really important to our Electron project.

Thanks for giving this PR a onceover: https://github.com/electron/electron/pull/48448

I'm happy to help move this forward any way I can.

**Comment by jjeff** [comment]
A little more clarification:

On macOS, a package (or bundle) is simply a directory that Finder treats as a single file because its extension and UTI are registered as a “package” type in an app’s Info.plist. Under the hood it’s just a normal folder containing structured resources (e.g., Contents/, Info.plist, assets), but macOS hides the internals for user convenience. This format is used for apps (.app), frameworks, plugins, and many project/document types, such as .pages, .band, .logicx, and any custom extension an app declares. This is the project file format for many Mac applications, including Xcode, Final Cut, Logic Pro, Keynote, OmniGraffle, Ableton Live, and Scrivener. 

We chose this format for the Mac versions of our application because it closely aligns with Apple's formatting. However, we can't update to an Electron version [compatible with macOS 26](https://github.com/electron/electron/issues/48311) until this bug is fixed.

**Comment by mhkeller** [comment]
I'm also running into this issue and would love to see a fix.

**Comment by Ikalus1988** [comment]
## Fix Available

I've submitted a fix in PR #51661 that addresses this regression.

**Root cause:** When migrating to the non-deprecated `allowedContentTypes` API in PR #46623, the UTType creation for file extensions did not specify package conformance. Custom macOS packages like .rtfd (which have `LSTypeIsPackage = true`) were not being recognized because the system didn't know these extensions correspond to package types.

**The fix:** Attempts to create UTTypes with `com.apple.package` conformance first, then falls back to the regular method if that fails.

**PR:** https://github.com/electron/electron/pull/51661

**Comment by Thapza888** [comment]
@jjeff — I'm looking at claiming the BountyHub bounty on this issue. I see #49444 reverted to the deprecated setAllowedFileTypes to close the bug, but the underlying problem (migrating to allowedContentTypes with proper UTType package conformance) isn't solved.

I have a fix ready that uses the modern API with the approach you suggested in this thread — creating UTTypes with com.apple.package conformance first, then falling back to regular UTType creation. It's essentially PR #48448 with the template/signing issues fixed.

Is the bounty still open for a proper allowedContentTypes-based fix that doesn't just revert to deprecated APIs? If so I'll submit the PR.

**Comment by jjeff** [comment]
> [@jjeff](https://github.com/jjeff) — I'm looking at claiming the BountyHub bounty on this issue. I see [#49444](https://github.com/electron/electron/pull/49444) reverted to the deprecated setAllowedFileTypes to close the bug, but the underlying problem (migrating to allowedContentTypes with proper UTType package conformance) isn't solved.
> 
> I have a fix ready that uses the modern API with the approach you suggested in this thread — creating UTTypes with com.apple.package conformance first, then falling back to regular UTType creation. It's essentially PR [#48448](https://github.com/electron/electron/pull/48448) with the template/signing issues fixed.
> 
> Is the bounty still open for a proper allowedContentTypes-based fix that doesn't just revert to deprecated APIs? If so I'll submit the PR.

@codebytere fixed this bug (and closed this issue) with https://github.com/electron/electron/pull/49444. She is welcome to the bounty, but has not claimed it.

**Comment by Thapza888** [comment]
@jjeff — I'm looking at claiming the BountyHub bounty on #48191. I see #49444 reverted to setAllowedFileTypes, and the modern-API fix from #51661 was auto-closed for unsigned commits and an incomplete template.

I have a fix ready that uses your suggested approach (UTType with com.apple.package conformance, fallback to regular UTType creation). It resolves both issues that blocked #51661 — commits are signed (git commit -S) and the PR template is fully filled out (checklist, description, release notes).

Is the bounty still open for a proper allowedContentTypes-based fix? If so I'll submit the PR.

@codebytere fixed the regression with #49444 but used the deprecated API. She hasn't claimed the bounty.

**Comment by isaaclins** [comment]
/opire try

Fix in [PR #51774](https://github.com/electron/electron/pull/51774): restores UTType-based macOS open-dialog filters and handles `LSTypeIsPackage` bundles (e.g. `.rtfd`) via `com.apple.package` conformance before extension lookup.

Repro gist linked in PR. Ready for review.

**Comment by midhunkvichu-hub** [comment]
I have investigated the regression in file_dialog_mac.mm caused by the migration to setAllowedContentTypes. I have developed a fix that correctly uses UTTypeItem conformance to ensure package types (like .rtfd and .app bundles) remain selectable.
    I have the patch ready. Would you like me to submit a Pull Request, or should I provide the diff here for review?"

**Comment by Ghostofcaldera** [comment]
test from ZeroAgent — ignore

**Comment by nikwen** [comment]
I'll lock this issue. It has been solved, and due to the open bounty, we've been getting too much spam here.
