### ISSUE TITLE
Event ready-to-show not triggering/inconsistent trigger on wayland

### ISSUE THREAD

**Issue by Sytten** [electron/electron#48859]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

38.6.0

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04

### What arch are you using?

x64

### Last Known Working Electron version

37.9.0

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

The event `ready-to-show` should trigger when the window is created with `show: false` and the window is ready to be shown no matter if running on x11 or wayland.

### Actual Behavior

Starting from Electron 38, the event `ready-to-show` is either not triggering or is inconsistent on wayland.
This worked fine on Electon 37 with wayland so I imagine it has something to do with Chromium ozone changes.

### Testcase Gist URL

https://gist.github.com/Sytten/75ace5d29b59d37e3f6ae382d1c89f3e

### Additional Information

If you run this gist on 37 you will see the window open, but all versions more recent will not show the window on wayland.

**Comment by Sytten** [comment]
If you cannot get to "fail" with the gist, you can try replacing the `index.html` load by a `.loadURL("https://google.com")`.

**Comment by nikwen** [comment]
Thanks for opening this issue and for the repro! CC @mitchchn.

**Comment by mitchchn** [comment]
@nikwen I have also experienced windows not firing `ready-to-show` and not appearing when the GPU is disabled, but only sporadically. I believe these are related to GPU timing/synchronization issues in Chromium and am filing the ones that I can repro there.

@Sytten do you use an NVIDIA GPU by any chance?

**Comment by Sytten** [comment]
This was tested in VMware fusion on an M3 MBP Pro with 3d acceleration enabled (so no?). We had a lot of users report the bug to us on many setups and I cant imagine all of them use nvidia. But I saw GPU related error logs so that might be related.

**Comment by mitchchn** [comment]
@Sytten yes, I’ve also reproed the lack of “ready-to-show” and similar issues in hardware accelerated VMs on a Mac (Parallels) as well as on bare metal with Nvidia GPUs. (But not with AMD or Intel which is why I was curious.)

I believe these bugs are likely related to upstream GPU sync issues in Chromium. The issues did seem to be more common in Electron 38 (and chromium 140) than more recent versions of each, and on 40.x betas I cannot repro them in my VM anymore. Not saying the problem is solved but do you see any difference with the newest pre-release versions?

**Comment by alexsch01** [comment]
Damn, just tried latest nightly (20251106) and electron window not showing up still occurs

**Comment by lukas2** [comment]
fyi albeit perhaps slightly off topic: We are using snapcraft, our workaround is to set
```
environment:
      XDG_SESSION_TYPE: x11
      ELECTRON_OZONE_PLATFORM_HINT: x11
```
in `snapcraft.yaml` in order to avoid an electron downgrade for now.

**Comment by alexsch01** [comment]
> ELECTRON_OZONE_PLATFORM_HINT: x11

not needed since electron 38 (and up) don't use this anymore

**Comment by xmedeko** [comment]
Same problem here on Ubuntu 22. Problem persist when when I've switched to Electron v40.0.0-beta.5. 

I confirm `export XDG_SESSION_TYPE=x11` is a workaround. Unfortunately, not for our users since we use direct installation, (not snapcraft).

BTW. is still ["ready-to-show" event](https://www.electronjs.org/docs/latest/api/browser-window#using-the-ready-to-show-event) necessary to avoid flickering? It seems our app does well without it (Linux, Windows). Note: some "flash" on window open was fixed in #42523

**Comment by Sytten** [comment]
As v37 is now EOL, I would like some guidance on this issue. This is blocking folks from updating (see that even bitwarden had to revert back to v37) @mitchchn @nikwen

**Comment by nikwen** [comment]
I don't think we have an update at the moment. We'd welcome PRs that fix the issue.

You could also implement a workaround like this one: https://github.com/FreeTubeApp/FreeTube/pull/8294

**Comment by alexsch01** [comment]
electron@40.0.0 - even this version I've seen the issue happen

```
npx electron@40 --disable-gpu
```

it's sporadic

**Comment by ell1e** [comment]
I see this problem on AMD hardware and even an ARM Mali GPU, so it's not Nvidia-specific.

**Comment by alexsch01** [comment]
https://github.com/electron/electron/blob/8a11d5afb1c2381670da72227d757c745c382afb/shell/renderer/electron_render_frame_observer.cc#L156:L165

`DidMeaningfulLayout` never gets called when I do `npx electron https://google.com --disable-gpu`

---

the bug is located somewhere in the chromium code or blink code

**Comment by alexsch01** [comment]
I made this chromium bug report, https://issues.chromium.org/issues/479458083

**Comment by ravicious** [comment]
bump

**Comment by zach20scott** [comment]
bump

**Comment by qeelei** [comment]
**Still reproducible on Electron 42.0.1.** Adding a data point since this seems GPU-dependent:

- **Electron version:** 42.0.1
- **OS:** Ubuntu 26.04 LTS, GNOME
- **Display server:** Wayland — **native Wayland**, not XWayland (verified via `xlsclients`: no entry for the app)
- **Arch:** x86_64
- **GPU:** NVIDIA GeForce RTX 3060 Ti (GA104) — this matches the NVIDIA correlation mentioned above; no AMD/Intel machine available to compare

Repro: `BrowserWindow` created with `show: false` + `once('ready-to-show', () => win.show())`. `ready-to-show` never fires on this setup — the main process stays alive, the renderer finishes loading, and `did-finish-load` fires (verified via logging), but the window stays hidden forever.

User-visible symptom: clicking the menu item appears to do nothing on the **first** click; the **second** click works, because the window was already created and the code path falls back to calling `window.show()` directly.

Workaround that fixed it for us: reveal the window on `did-finish-load` if `!win.isVisible()` (Linux-only, first-wins), same approach as FreeTubeApp/FreeTube#8294. Happy to test any patch or pre-release build that addresses this.

**Comment by jnsgruk** [comment]
This also just showed up in Signal Desktop on Linux - see https://github.com/snapcrafters/signal-desktop/issues/474

**Comment by ell1e** [comment]
No messenger needs GPUs, and most messengers use electron now. I always disable GPU access through flatpak since it's way more of a security risk than of any use, even on a phone (since even those devices are fast enough). It also seems like some people hit this even with GPUs.

Anyway, I wanted to point this out since I was hoping it will motivate more interest in a fix for the non-GPU case.
