### ISSUE TITLE
CSS cursor not honored when element in header with titleBarStyle="hidden"

### ISSUE THREAD

**Issue by markbrocato** [electron/electron#5723]
If you place an element with a css cursor style at the top of the page where the title bar would be with titleBarStyle="hidden", the cursor always displays as default.  A simple example would be a link.

**Comment by jlord** [comment]
I was able to reproduce this and @kevinsawicki and I looked into some today but aren't sure the best fix.

It's just a problem on OS X and how the hidden title bar is only sort-of-kind-of hidden. For instance hover events still work in this area but the cursor will change back to default. 

There are some different ways to remove/hide this title bar and maybe someone else has some pointers on which is the best route?

**Comment by poiru** [comment]
@kevinsawicki @jlord This can be fixed by getting rid of the title bar (and `NSToolbar` for `hidden-inset`) entirely and manually adding the standard window buttons to the window. In our Electron app, we use `frame: false` and pass `BrowserWindow.getNativeWindowHandle()` to a native module to do exactly that.

To make the button icons appear on hover, we would have to use the undocumented `_mouseInGroup` NSView method. This is also used by [Chromium](https://cs.chromium.org/chromium/src/chrome/browser/ui/cocoa/tabs/tab_strip_controller.mm?q=_mouseInGroup&sq=package:chromium&l=197) so it should be pretty safe. If you're fine OK with this, I'm happy to contribute a patch when I have some time.

As side-benefit...

* we could allow arbitrary positioning of the window buttons (instead of just two distinct positions with `hidden` and `hidden-inset`)
* we would fix the `hidden-inset` drag and drop issue (#7942)

#6725 is not relevant for our app so I haven't looked into it.

**Comment by kevinsawicki** [comment]
>  If you're fine OK with this, I'm happy to contribute a patch when I have some time.

Yeah, seems worth it, a patch would be appreciated 👍. Any downside to not using `NSToolbar`? Would anything break for existing apps using `hidden-inset`?

**Comment by poiru** [comment]
>Any downside to not using NSToolbar? Would anything break for existing apps using hidden-inset?

I can't think of anything, at least.

**Comment by mcc108** [comment]
When will the problem be solved?

**Comment by tonyganch** [comment]
I've spoken to @poiru and he says he'll get to this issue next week.

**Comment by jarek-foksa** [comment]
I can still reproduce this bug and related bug #7942 with Electron 1.7.3.

**Comment by MarshallOfSound** [comment]
@jarek-foksa Are you following the instructions here https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#custombuttonsonhover regarding how to solve this issue.  Check the PR that closed this issue for more context

**Comment by jarek-foksa** [comment]
@MarshallOfSound Ohh, I see. I think this solves the cursor problem, but bug #7942 is still reproducible, i.e. you tabs can't be dragged when `hidden-inset` titlebar style is set.

**Comment by MarshallOfSound** [comment]
@jarek-foksa If you don't want that issue use `customButtonsOnHover` not `hidden-inset`.

**Comment by jarek-foksa** [comment]
I wanted to keep the `hidden-inset` appearance while being able to drag the tabs. I think bug #7942 should be reopened as it does not seem to be fixed.

**Comment by poiru** [comment]
@jarek-foksa See [this comment](https://github.com/electron/electron/pull/9687#issuecomment-306642851).

**Comment by johnryan** [comment]
@poiru it seems like the only way to fix the cursor issue is to set a frameless window and `customButtonsOnHover`...but that hides the buttons unless you hover. As far as I can tell there's no way to keep the buttons visible on mac AND have the correct cursor behavior. Is that correct?

**Comment by poiru** [comment]
@johangp Yep. You will be able to do both when I get around to doing [this](https://github.com/electron/electron/pull/9687#issuecomment-306642851).

**Comment by johnryan** [comment]
@poiru awesome thanks for the clarification re: that solution.. Will it still require a frameless window? If so, would that cause issues on windows? Thanks!

**Comment by poiru** [comment]
@johnryan Not sure I understand. It will only work in frameless windows, but framed windows don't suffer from this issue anyway. It won't affect Windows at all.

**Comment by johnryan** [comment]
@poiru i am actually seeing this issue on a non-frameless window. By that i mean that i just have the the title bar hidden.

```
mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    titleBarStyle: 'hidden',
    minWidth: 750,
    minHeight: 450
  });
```

With this configuration the area where the titlebar *would* be doesn't properly show the cursor specified by the css underneath it (though it does receive click events). Please let me know if i can clarify.

**Comment by Polunom** [comment]
Any progress so far? I don't see an implementation of @poiru's suggestion and customButtonsOnHover simply isn't practical (not shown normally + no inset).

**Comment by aguynamedben** [comment]
Another case running into this...

For my app I want `frame: false` but I don't want `customButtonsOnHover: true` because I don't want macOS title bar buttons at all. I'm trying to (1) have no title bar or title bar buttons (2) put a link with `cursor: pointer` in the top left (a 'Back' link). If I put the 'Back' link where I want—top left of the frameless window—the customButtonsOnHover setting causes users to accidentally click minimize/maximize/close when they're trying to hit 'Back'.

Is there a way to just tell the minimize/maximize/close buttons to completely go away?

Thanks for your work on this project. For now I'm just working around with design, but I figured it might be helpful to chime in. Maybe there's just no reasonable way to tell the macOS buttons to go away.

**Comment by Skriptach** [comment]
I faced same issue. Option titleBarStyle: 'customButtonsOnHover' doesn't help.

"electron": "^3.0.0-beta.3",
Windows 7 x64

**Comment by gordomium** [comment]
At last!

**Comment by BloodShura** [comment]
Why has this been closed? It's not fixed yet @ 3.0.7 release.

Even with no `-webkit-app-region: drag` at all, some boundary regions of the window don't apply the correct `cursor` CSS property. Click events work properly.

**Comment by Jocs** [comment]
Any updates of this issue?

**Comment by jeremyspiegel** [comment]
I am able to reproduce this in 5.0.4 with a simple change to electron-quick-start using `titleBarStyle: 'hidden'` and a BrowserView (here is the [diff](https://github.com/electron/electron-quick-start/compare/master...jeremyspiegel:title-bar-cursor)).

The BrowserView has a text input element the should change the cursor type to text on hover. When the cursor moves through the top of the window, it doesn't change when moving over the text input. The cursor does change when moving over the input from inside the window.

Here is a demo: 
![Kapture 2019-06-18 at 22 26 18](https://user-images.githubusercontent.com/776117/59739358-72d65e80-9219-11e9-8ce8-b8be7188df4a.gif)

Using `titleBarStyle: 'customButtonsOnHover'` doesn't seem ideal since then the maximize button doesn't work. From the [comment](https://github.com/electron/electron/pull/9687#issuecomment-306642851) @poiru mentioned above, it sounds like there is a plan for a better fix. I can't find an open issue that tracks this though, should this one be reopened?

**Comment by ozsay** [comment]
Having a similar problem on a frameless window. there is a gap (~10px) at the top of the window where clicking has functionality but `cursor: pointer` css is not working.

any word on it? running electron@6.0.0

**Comment by castroCrea** [comment]
> `titleBarStyle: 'customButtonsOnHover'` seems to solve the cursor problem but what if i don't want any window buttons?

An update on this ??
the option : 
`titleBarStyle: 'customButtonsOnHover' and mainWindow.setWindowButtonVisibility(false)` is still not working

So for now we can't have any custom title bar that allow cursor pointer without window action button that appears in a place pre set that we can't customize

**Comment by philippkuehn** [comment]
please make it happen 🙏

**Comment by TundraFizz** [comment]
I'm experiencing the same problem that ozsay and castroCrea are having as well.

`titleBarStyle: "customButtonsOnHover"` is the only way I can get `cursor: pointer` to work, but unfortunately it visibly displays the window buttons which I don't want.

**Comment by ritz078** [comment]
This solved it for me:

```js
win = createWindow("main", {
    webPreferences: {
      nodeIntegration: true,
    },
    vibrancy: "under-window",
    frame: false,
    titleBarStyle: "hidden",
  });

  win.setTrafficLightPosition({
    x: 10,
    y: 30
  })
```

**Comment by jwoo0122** [comment]
Is this problem solved? When using `titleBarStyle: "hiddenInset"` you can reproduce the bug.

**Comment by syzhakov** [comment]
still no way to prevent it, any plans to work on it?

**Comment by noresources** [comment]
Hello
I'm just popping in the electron world and I am facing the same problem.
My goal is to have a multi-screen frameless/cursorless window. 

We had a very similar issue with our 3D engine code that was solved by calling
`[window setStyleMask:NSBorderlessWindowMask];`
`NSPoint point; point.x = 0; point.y = 0;`
`[window setFrameTopLeft: point]` 
after the view initialization.

Before this call, the `window.frame.origin.y` is -22, which is the height of the titlebar.

Unfortunately, I'm too short in time to check if this is the correct solution for electron 

[Official documentation](https://developer.apple.com/documentation/appkit/nswindow/1419658-setframetopleftpoint?language=objc)

**Comment by 0nn0** [comment]
The solutions offered above unfortunately do not solve it for us, and using titleBarStyle: 'customButtonsOnHover' is not an option as then the maximize button does not work. Running Electron version: 11.2.1

![Screen Recording 2021-04-22 at 13 04 23](https://user-images.githubusercontent.com/860132/115704449-af21fb00-a36b-11eb-903c-7291a5321793.gif)

@philippkuehn Did you manage to get it working?

**Comment by raphaelschaad** [comment]
Did this issue get closed prematurely? I can observe this behavior with latest Slack.app /cc @MarshallOfSound 
![CleanShot 2021-06-09 at 22 22 57](https://user-images.githubusercontent.com/439447/121424478-aadc8c00-c971-11eb-856d-22111106840e.gif)

**Comment by zcbenz** [comment]
For now, the only way I found that can fix this bug, is to remove the `NSWindowStyleMaskTitled` style from window, which removes the titlebar completely. It does not really matter what other styles we use.

However removing the `NSWindowStyleMaskTitled` style has a a few severe side effects:

1. the window's corners are not rounded;
2. the window can not be closed in normal ways;
3. the window can not enter fullscreen.

While the 1) and 2) can somehow be workarounded, I can't find any way to solve the last one.

So I think there are currently 2 ways to solve this:
1. Make Apple fix this bug.
2. Find some hidden method that can override the default cursor on titlebar.

**Comment by noresources** [comment]
Shouldn't be the correct look and feel of a `frameless`ed window ?

**Comment by franciscop** [comment]
I copy/paste here my bug report, since my wording was totally different and I missed this currently opened previous bug report:

### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

_No response_

### Expected Behavior

When the `frame: false` option is passed to the `new BrowserWindow()` options, all of the window is a canvas for HTML that is clickable.

### Actual Behavior

The top ~20 pixels of the frameless window is not clickable, and doesn't have events. It's as if the title bar was there, but invisible. This is the code:

```js
const { app, BrowserWindow } = require("electron");

app.on("ready", () => {
  const child = new BrowserWindow({ frame: false });
  child.loadURL("https://github.com");
  child.once("ready-to-show", () => {
    child.show();
  });
});
```

See a recording of the bug in action, expected the whole icon/button to be hoverable+clickable but seems like something is "covering" them:

https://user-images.githubusercontent.com/2801252/130335574-d3c9b9a4-e949-4af2-8150-6bde52196cf2.mp4

### Testcase Gist URL

https://gist.github.com/franciscop/20a6fbd380ad10678e512f14c76be125

### Additional Information

Something interesting is that, playing with the option `titleBarStyle` you can get one version where this particular issue is fixed (BUT it requires you to show the buttons on hover, which of course it's an impossible requirement in many cases, so it's still a bug):

```js
const { app, BrowserWindow } = require("electron");

app.on("ready", () => {
  const child = new BrowserWindow({
    frame: false,
    // We don't want the buttons, but at least this makes more real estate clickable?
    titleBarStyle: "customButtonsOnHover"
  });
  child.loadURL("https://github.com");
  child.once("ready-to-show", () => {
    child.show();
  });
});
```

See how now you can hover on all the elements, BUT it also displays the buttons on hover:

https://user-images.githubusercontent.com/2801252/130335667-7106286f-2203-417f-99c9-68e8a832abdc.mp4

I tried `hidden` and `hiddenInset` but they oddly enough do show the controls and they still have the previous issue as the commented here originally (or even worse in the case of `hiddenInset`).

Related bugs:
- [This bug in menubar](https://github.com/maxogden/menubar/issues/172) is definitely the same thing.
- I found [another slightly related](https://github.com/electron/electron/issues/26720) but probably different bug since it's in a different platform, so I believe it might be a different thing (the video linked is dead so cannot verify).

### Code dive-in

I'm way out of my depth here, but it seems [this line of code](https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L357) is the one making the title bar transparent when `frame: false`:

```c++
  if (transparent() || !has_frame()) {
    // Don't show title bar.
    [window_ setTitlebarAppearsTransparent:YES];
    [window_ setTitleVisibility:NSWindowTitleHidden];
```

And then (maybe?) [this conditional](https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L1479) makes it "visible" if it's not `customButtonsOnHover`? We might want to do an if (customButtons) { ... } else if (hidden || hiddenInset) { ... } else { ... } instead? (as I said, unfortunately I can report the bug but not sure if I follow the correct code for the bug here):

```
  if (title_bar_style_ == TitleBarStyle::kCustomButtonsOnHover)
    [buttons_proxy_ setVisible:visible];
  else
    InternalSetWindowButtonVisibility(visible);
```

**Comment by KevinHughes** [comment]
FYI in `BrowserWindow`s with `frame` set to `false` and `transparent` set to `true`, custom cursors are still not appearing in the invisible title bar area. Mouse events still appear to work in that area though. Electron 16.0.3, macOS Monterey 12.0.1, arm64.

**Comment by KevinHughes** [comment]
As noted [here](https://github.com/electron/electron/issues/5723#issuecomment-905334958_) five months ago, this is still preventing Chromium at a low level from changing cursors as well (Electron 16.0.4, macOS Monterey 12.0.1, arm64):

1. Create a `BrowserWindow` with `frame` set to `false` and `titleBarStyle` set to any allowed setting
2. Absolutely position an HTML text field to the top of the window
3. When hovering over and editing the text field at the top of the window, it is expected that the mouse cursor will change to a text cursor. Instead, the cursor retains its default arrow image at all times, even when selecting text

Given that macOS Monterey now routinely places text fields in the title bar area (such as the search field in Finder windows), this bug makes it impossible to accurately emulate the UI style of modern macOS applications.

Given that this issue is over four years old and is still causing developers pain, I humbly request that it be assessed again to see if this is an Apple issue and/or if it can be fixed within the Electron code.

**Comment by eyun-tv** [comment]
use this
```
    roundedCorners: false
    transparent: true
    shadow:false
    resizable: false
```
and in css
```
border-radius 8px 
```
see the image below
![image](https://user-images.githubusercontent.com/50322174/151140361-45b7466e-eeac-4a23-9bbc-79da468d6510.png)
![image](https://user-images.githubusercontent.com/50322174/151140408-749bcf86-2d56-4550-b014-2ebb7a342e3a.png)

**Comment by KevinHughes** [comment]
I'm not sure when or how this changed, but I can no longer duplicate this bug in Electron 16.0.7, macOS Monterey 12.1, arm64!

**Comment by raphaelschaad** [comment]
Sure nothing else changed? We can replicate it with Electron 16.0.7 just like we did before (also Monterey, Apple Silicon).

**Comment by franciscop** [comment]
I was really excited and spent 2+ hours upgrading. But unfortunately this is **not fixed** on Electron 16.0.7, I can still reproduce the exact same problem.

**Comment by KevinHughes** [comment]
Sorry, I spoke too soon! My app window uses `frame: false`, `roundedCorners: false`, and `titleBarStyle: 'hidden'` with no traffic lights in the title bar area. Previously CSS cursors would not work in this case, but they do now for some reason, leading me to believe this was fixed. Testing windows with `frame: true` still shows this bug (Electron 16.0.7, macOS 12.1).

Here's a test `index.js` file:

```
const { app, BrowserWindow } = require('electron')
app.whenReady().then(() => {
    const win = new BrowserWindow({
        width: 200,
        height: 200,
        titleBarStyle: 'hidden'
    })
    win.loadFile('index.html')
})
```

...and a test `index.html` file:

```
<html>
  <body style="border: 1px solid black;margin:0px">
    <div style="width:100%;height:198px">
        <div style="width:100px;height:100px;background:red;cursor:grab"/>
        <input type="text" style="position:absolute;right:10px;width:50px"/>
        <a href="https://google.com/" style="position:absolute;left:80px">test</a>
        <input type="text" style="position:absolute;top:30px;right:10px;width:50px"/>
        <a href="https://google.com/" style="position:absolute;top:30px;left:80px">test</a>
    </div>
  </body>
</html>
```

Hovering over the red area, link, and input in the title bar area still does not change the cursor. Hovering over the red area, link, and input below the title bar area works as expected.

So there is still no way to make the CSS cursors work while the traffic lights are showing. Setting `frame: false` and using `win.setTrafficLightPosition()` as mentioned earlier here does not work either. Sigh.

**Comment by franciscop** [comment]
I can confirm that @eyun-tv workaround works! If you follow this tutorial to the last bit, then you'll get a window without the top edge blocked. From my testing, it was the `roundedCorners: false` that actually triggered making the blocking invisible elements disappear, but you need all the bits to then manually recreate the border-radius yourself.

It's tricky because somehow you need the `body` to be `background: transparent`, and then you need the children to have the border radius and be smaller than the body (it doesn't behave 100% like normal CSS, if you do the radius in the body itself it won't work, it needs to be in a child of it). So it's a **really convoluted workaround to this bug**, and thus I think this should remain as an official bug until it's fixed.

**Comment by franciscop** [comment]
Sorry forgot to paste the link, here's the tutorial:

https://bobby-valenzuela.medium.com/electron-js-how-to-create-a-beautiful-frameless-window-8ee9ef9d1280

**Comment by marindedic** [comment]
For anyone still having this problem in electron 19+ (macOS):

To enable `cursor: pointer` in the upper portion of the window while having a frameless window (`frame: false`), you need to remove rounded corners: `roundedCorners: false`. Unfortunately, the resulting window has a non-native look to it with the rounded corners removed now.

**Comment by fabiospampinato** [comment]
Setting `roundedCorners: false` worked for me, but obviously that's not really a fix. Is not possible to just fix this?

**Comment by acnebs** [comment]
Bump

**Comment by fabiospampinato** [comment]
This issue is still a significant pain in the butt for me.

**Comment by albicasty** [comment]
same here, on Linux

**Comment by franciscop** [comment]
Bump (still happening, though I already moved to Tauri 🤷‍♂️)

**Comment by fabiospampinato** [comment]
This is possibly my biggest issue with Electron, it's extremely frustrating how the app is kind of visually broken like that.

**Comment by johnlindquist** [comment]
Confirmed bug in 24.1.2:

https://user-images.githubusercontent.com/36073/234012767-d353e7f7-d8d0-4fbc-9b42-52bccc619542.mp4

**Comment by sdellapina** [comment]
Still happening for me 24.1.2  

https://user-images.githubusercontent.com/1056646/234381424-066f43ef-3bb3-4fd1-9fe9-e71964502432.mov

**Comment by fabiospampinato** [comment]
Is it not possible to ping somebody that works on Chromium that knows that the fix would be here? Surely anybody working with Electron would be interested in seeing this fixed?

These issues with no passable workarounds that throw a wrench in your design are extremely frustrating.

**Comment by fabiospampinato** [comment]
Still an issue.

**Comment by fabiospampinato** [comment]
The only thing more annoying than this bug is the stale bot 🤣 Can't we add an "unstalable" tag for issues that are important enough that shouldn't be closed automatically by a bot?

**Comment by fabiospampinato** [comment]
no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale no stale

**Comment by TundraShark** [comment]
Soon enough it will be an entire decade that this issue has been open; still not stale! 😎

**Comment by TundraShark** [comment]
I just swam up 7 miles from the Mariana Trench to bump this ticket, because it still has not been resolved

**Comment by MiguelMike** [comment]
Still an issue on 33.2.0

**Comment by QC2168** [comment]
same issues

**Comment by raphaelschaad** [comment]
bump

**Comment by gravataLonga** [comment]
bump

**Comment by franciscop** [comment]
Bump

**Comment by sumimakito** [comment]
Bump

**Comment by franciscop** [comment]
When nobody answers in 3 months @electron-issue-triage just comes in to ask again, this issue is not going to be solved magically so not sure what this accomplishes 😅

**Comment by aljazdolenc** [comment]
bump

**Comment by nmggithub** [comment]
I'm willing to take a look at this if anyone can provide me a reproduction Gist for Fiddle that exhibits this behavior in any recent Electron version. I did some testing earlier myself and wasn't able to get it to reproduce in any Fiddle on my machine (macOS 26.3.1).

**Comment by franciscop** [comment]
It seems to be fixed! 🥳

https://github.com/user-attachments/assets/bc8bef29-b613-498f-a494-0bee269ed336
