### ISSUE TITLE
win.capturePage never calls back after calling `hide()` for a hidden window

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#6015]
- Electron version: 1.2.2
- Operating system: Linux

This is a problem only in linux. It works in OSX.

``` javascript
win.hide()
win.capturePage(function(img){
 // never called
})
```

**Comment by zcbenz** [comment]
I can't reproduce by simply capturing a page loaded from filesystem,  can you provide a minimal app that can reproduce this problem?

**Comment by brian-mann** [comment]
Okay was able to reproduce in a new example app. There are two things which cause this to happen.

1. The window must currently be hidden
2. You must call `capturePage` asynchronously

```javascript
var app = require('electron').app;
var BrowserWindow = require('electron').BrowserWindow;

var mainWindow = null;

app.on('ready', function() {
  var opts = {
    width: 1280,
    height: 720,
    show: false,
    frame: false,
    devTools: false
  }

  mainWindow = new BrowserWindow(opts);

  // hiding the window is key, if it is shown it will work
  mainWindow.hide()

  mainWindow.loadURL('file://' + __dirname + '/index.html');

  setTimeout(function(){
    mainWindow.capturePage(function(data){
        // this function is never called
        console.log("captured data", data)
    })
  }, 1000) // calling this async is key. if you reduce the setTimeout value it will work

});
```

**Comment by zcbenz** [comment]
I can reproduce with your example, calling `hide()` for a hidden window seems to cause problems.

**Comment by codebytere** [comment]
closing due to abandonment.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (124/100 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:45330 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1SQ-0018wQ-Np
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:48:17 -0500
Date: Tue, 26 Sep 2017 18:47:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476847;
	bh=tYmfE8mjrtaq97yIcI8laC7ZmLX8mmoAsnr3FRSy4cA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=i1hXkgzkMop8DpXdkUddlBdLotPU6fSI8/jDA4zFqe2zK73L0BtSHkcINL6ZSIpMR
	 XK2eBR8mZnrOhbC7AjD7QNroZUjmGT2qfoAd1hwPEn7R75fxZE/3Vukz7cEP7RFfN2
	 oB5Rf6QquaqstHBQTdazMT3QsEFYNBzQeoeUyeCY=

**Comment by astoilkov** [comment]
Why was this issue closed? I am experiencing the same problem. Should I create a new issue describing the same problem?

**Comment by codebytere** [comment]
It was closed since there had been no action on it for over a year, and it is not on our team's immediate radar. Since we try to treat the issues tab as the team's backlog, we try to close issues as needed to bring the project closer to its reality and roadmapping.

**Comment by astoilkov** [comment]
Great to hear an explanation @codebytere. Thanks!

However, this is an existent issue we are experiencing in our [app](https://caret.io). We have implemented great functionality for increasing the perception loading time of our app by calling `capturePage()` before quitting the app and then showing the generated image on startup. We are calling `hide()` before calling `capturePage()` so users don't notice a lag when closing the app. This approach doesn't work on Windows which is quite unfortunate. 

If this issue is fixed I could write a cool article for how to optimize Electron apps which will increase Electron's authority.

It would be awesome to reopen the issue. Thanks for considering.

**Comment by codebytere** [comment]
i can't promise anything but i'll try to take a look at this issue next week if i have time :) i'll re-open it in the meantime, and let you know if there's progress.

**Comment by astoilkov** [comment]
Great. Thanks!

**Comment by sns-sem** [comment]
This is still an issue on Windows years later: `captureWindow` is never resolved after calling `.hide()` on a `BrowserWindow`.

Sample to reproduce
```js
import { app, BrowserWindow } from "electron";

app.on("ready", async () => {
  const browserWindow = new BrowserWindow({
    width: 900,
    height: 600,
    show: true,
    webPreferences: {
      contextIsolation: false,
    },
  });

  await browserWindow.loadURL("https://youtube.com");

  // This call will resolve as expected
  const image = await browserWindow.capturePage();
  console.log("Screenshot size:", image.getSize());

  browserWindow.hide();

  // This call does not resolve
  const image2 = await browserWindow.capturePage();
  // This will never be logged as the previous capturePage never resolves
  console.log("Screenshot size", image2.getSize());
});
```

The second `capturePage` never resolves on Windows 10. If you initiate the BrowserWindow with `show: false`, `capturePage` does work. It is explicitly after calling hide. Likewise, if you call `.show()`, all the previously unresolved calls with resolve and the method will continue working as expected.

My app's use case requires taking screenshots of the window while it is hidden, and the window switching between shown and hidden.

* Electron versions: 11.3 (latest), 12.0.0-beta.28, 9.4.3, 10.3.2.
* OS: Windows 10 (It works on OSX. I have not tested Linux)
