### ISSUE TITLE
Some CSS hover/interaction works 1.2.6, but not on 1.4.1

### ISSUE THREAD

**Issue by spiraljacobs** [electron/electron#7410]
* Electron version: 1.4.1
* Operating system: Windows 10 x64 Anniversary Edition

Bizarrely, upgrading Electron to 1.4.1 caused hover and button interaction of custom buttons to stop working.  Downgrading to 1.2.6 fixed the issue.  Could be something else at play, but downgrading restored expected behavior.  

Simple CSS hover + simple JS button press based on code from here: http://mylifeforthecode.com/making-the-electron-shell-as-pretty-as-the-visual-studio-shell   

Change in frameless window behavior, possibly?

**Comment by spiraljacobs** [comment]
Verified via a simple application that the same hover CSS/button interaction code that works in 1.2.6 doesn't work at all in 1.4.1.
Very simple project at:
https://github.com/spiraljacobs/141test 

Ran electron 1.2.6 executable against main.js and hover and button interaction works.  
Ran electron 1.4.1 executable against main.js and hover and button interaction doesn't work.

Could be that this is the way things are intended, but if so, how do I make these kinds of things work in 1.4.1?

**Comment by ShepherdJerred** [comment]
Happening to me too

**Comment by zcbenz** [comment]
I can not reproduce with Windows 8.1, this is very likely a bug of the Anniversary update.

Can you also try whether this Chrome app have same problem on your machine?
https://chrome.google.com/webstore/detail/frameless-window-sample/hjjdaddngnaofnfjpajdcbdmkegiakec

**Comment by MarshallOfSound** [comment]
I can not reproduce on Windows 10 Post-Anniversary or Pre-Anniversary (I have both on different machines).

I've had this issue reported before when a user has TeamViewer installed (or something similar) as it injects it's own small UI button in the top bar of all running executables.  Might be worth checking your systems don't have something like that running

**Comment by spiraljacobs** [comment]
Interesting - the frameless Chrome window behaves as expected for me - looks fine here, whereas I can reproduce the issue in Electron.  
Very strange.  I do, in fact, have Team Viewer installed.  I'll uninstall it.

**Comment by dogboy21** [comment]
I tried it on Windows 8.1 (without Teamviewer), Windows 10 Anniversary (without Teamviewer) and Windows 10 Anniversary (with Teamviewer) and the problem existed on all machines. Downgrading to Electron 1.2.6 didn't help for me either.

**Comment by MarshallOfSound** [comment]
@dogboy21 Can you provide a screen cast of the issue you are seeing

**Comment by spiraljacobs** [comment]
I've since tried after uninstalling TeamViewer, and the problem still exists.  I've made a pretty crap video demonstrating it, running the code I posted above in 1.2.6 and 1.4.1.  Unfortunately, my internet connection is awful, but I'll post the link as soon as it's finished uploading.

**Comment by dogboy21** [comment]
https://ss.myftb.de/KQ3wYcl5.mp4 That's the problem I'm facing

**Comment by spiraljacobs** [comment]
I've shrunk the video so I could upload quicker.  Here's a demonstration of what happens in 1.2.6 vs. 1.4.1 with the same code:
https://www.youtube.com/watch?v=g2TSYN130vg

**Comment by MarshallOfSound** [comment]
@dogboy21 Your issue appears to be slightly different, if I had to guess it is due to how `--webkit-app-region: drag` absorbs all mouse events and there fore hover doesn't work.  It looks like you have applied that drag region style to the top left of that window.

@spiraljacobs Yeah, I tried doing exactly what you just did in that video and still can't reproduce :cry:

**Comment by spiraljacobs** [comment]
I've added the frame as per @dogboy21 , and confirmed the CSS interaction works when frame:true.  When I do frame:false, it behaves as it does in the video.

**Comment by dogboy21** [comment]
@MarshallOfSound Derp.. Yeah totally forgot about that xD

@spiraljacobs I tried your code and I can't reproduce it on Win10 or Win8.1 either

**Comment by spiraljacobs** [comment]
@dogboy21 @MarshallOfSound  I increased the size of the buttons to a larger size, and it works on 1.4.1.  Seems to be some kind of region issue with the borderless.  
If it is something on my machine and not Electron...I wonder why it would work normally in 1.2.6?  Strange.  I'll try on my home PC which is also Win10 x64 Anniversary later on.

**Comment by MarshallOfSound** [comment]
@spiraljacobs Do you have DPI scaling on your monitor?

**Comment by spiraljacobs** [comment]
@MarshallOfSound looks like I do/did.  I reduced it to 100%, and the problem was still there, but I haven't restarted which is likely necessary.  Will try it out as soon as I get a chance.  
Thanks for all the help here!

**Comment by dogboy21** [comment]
Even with DPI scaling set to 200% I can't reproduce the problem

**Comment by spiraljacobs** [comment]
I a) removed all DPI scaling, b) reinstalled nVidia drivers for the laptop videocard (I realized it was running incorrectly/incorrect drivers were installed/the video control panel wasn't accessible at all, and c) restarted.
I wish I had performed these in controlled steps, ie. a) then restart, b) then restart so I could determine what was the issue, but it's fixed now!  1.4.1 CSS hover interaction behaves as expected.  Bizarre, but I'm happy that things seem to be in working order again.

Thanks for the help!

**Comment by zuoxinyu** [comment]
It still occurs on v1.7.9 with node 7.9.0, chrome 58.0.3029.110, Windows 10 Fall Update(2017)
HTML code:
![reload_anime](https://user-images.githubusercontent.com/9346419/32312697-28724a9c-bfda-11e7-8077-c2a9595b4382.gif)

```HTML
    <header class="draggable">
        <div class="window-hints">
            <div id="close-hint">×</div>
            <div id="maxmize-hint">□</div>
            <div id="minimize-hint">-</div>
        </div>
    </header>
```
Style:
```CSS
        .draggable {
            -webkit-app-region: drag;
        }
        .window-hints {
            height: 100%;
        }
        .window-hints div {
            display: inline-block;
            height: 16px;
            width: 16px;
            border-radius: 50%;
            margin: 2px 8px;
            text-align: center;
            vertical-align: top;
        }
        .window-hints div{
            background-color: #e2e2e2;
        }
        .window-hints:hover #close-hint{
            background-color: red;
        }
```

**Comment by paulius005** [comment]
Same issue as above ^
