### ISSUE TITLE
Blurry text on a windows electron app

### ISSUE THREAD

**Issue by Spazer9** [electron/electron#8708]
I've noticed that text appears more blurry on electron than in regular Chrome.

Mind you i'm using the latest electron version 1.6.0.

This is a comparison between **Chrome (Top)** and Electron's **Chromium (Bottom)**

![](https://s3.amazonaws.com/snaps-bucket/2017/02/X7JLssF/2017-02-17_14-45-53.png)

Any ideas how to fix this?

**Comment by groundwater** [comment]
Hi @Spazer9, thank you for the bug report. What version and OS are you using?

In future, following the [Issue Template](https://github.com/electron/electron/blob/master/ISSUE_TEMPLATE.md) can help ensure a quicker diagnosis. Thanks.

**Comment by Spazer9** [comment]
Thanks Groundwater for the note - i'm testing on Windows 10 64bit

**Comment by zeke** [comment]
@Spazer9 are you seeing this on older versions of Electron?

**Comment by Spazer9** [comment]
@zeke Yup - just tried with 1.3 - same exact effect.

**Comment by nikola** [comment]
@Spazer9 Are you using an Intel IGPU on that machine? There are quite a few Intel-iGPU-related rendering bugs in Chrome, depending on iGPU model, GPU driver and Chromium build.

**Comment by Spazer9** [comment]
@nikola Thanks for the response - I'm using a gtx 980 and i7.

Fonts are generally blurrier and less crisp on Electron (tried many versions).

Here's another screenshot (left is chrome, right is electron)

![](https://s3.amazonaws.com/snaps-bucket/2017/02/YLFZaA5/2017-02-24_06-36-22.png)

**Comment by zeke** [comment]
@Spazer9 are you using multiple monitors? There's a PR in the works that may address the issue you're seeing: https://github.com/electron/electron/pull/8786

**Comment by zcbenz** [comment]
There are usually two reasons for blurry text on Windows:

1. Text drawn with `DirectWrite` does not show "clearly" on your display;
2. Your are using multiple displays with different DPIs.

For 1) we are not able to fix it because Chrome now only uses `DirectWrite` for text rendering, for 2) it has been solved at least in 1.6.x.

**Comment by 6a7070** [comment]
I use FireFox and notice that the fonts are more clear in FF than when the same webapp displays inside of an electron app. If the issue is DirectWrite, why does the font appear clear in Chrome, but not in electron? Can this be fixed.

**Comment by utd1878** [comment]
Has this been fixed?  I'm running the latest electron and when running on windows I still see the blurriness in the text.
<img width="189" alt="screen shot 2018-01-26 at 10 57 09 am" src="https://user-images.githubusercontent.com/5215011/35453518-ba1efeb4-0287-11e8-8a1b-a823cecb54e6.png">

**Comment by Slapbox** [comment]
This is definitely still an issue in Electron 2.0.5 on Windows 7 x64. No matter what I do, I get grayscale antialiasing. It is especially ugly in a webview. Normally Electron's grayscale antialiasing is of equal quality to subpixel as far as I can tell, but in webviews it's VERY blurry.

I mean, my first impression looking at the text is, "wow that is really blurry." It's so blurry I was sure at first that I was distorting the page in the webview somehow, but I'm not. Thoughts?

![image](https://user-images.githubusercontent.com/6835891/43925128-6bddd124-9bf4-11e8-9526-cfa0d47dd06b.png)

**Comment by heronils** [comment]
It is now in the [FAQ](https://github.com/electron/electron/blob/master/docs/faq.md#the-font-looks-blurry-what-is-this-and-what-can-i-do)

**Comment by highergroundstudio** [comment]
I used `app.disableHardwareAcceleration();` to fix this problem. Is this the best way? I had tried everything else and this is the only way I could get it to stop. Especially since the developer tools was doing the same blurriness. Using Electron 9.0.0

**Comment by GiovanH** [comment]
@groundwater Is additional information still needed on this?

**Comment by cmcsun** [comment]
6 years later and this issue still isnt fixed lol

**Comment by Blobson** [comment]
Turning OFF FXAA in Nvidia Control Panel fixes the issue.
Source: https://github.com/desktop/desktop/issues/17444#issuecomment-1736417091

**Comment by blueglyph** [comment]
Apparently, this bug is still not fixed. I recently installed VSCode and Deezer, both based on Electron, and the text was often blurry. It seems to happen when switching tasks.

Unfortunately, there's no way to get to the developers of those apps, so it seems users are bounced between Electron and apps, and the bug is ultimately never fixed. Shame.

**Comment by hisbvdis** [comment]
> Apparently, this bug is still not fixed. I recently installed VSCode and Deezer, both based on Electron, and the text was often blurry. It seems to happen when switching tasks.
> 
> Unfortunately, there's no way to get to the developers of those apps, so it seems users are bounced between Electron and apps, and the bug is ultimately never fixed. Shame.

@blueglyph 

There is a workaround in the VS Code:
1. Ctrl+Shift+P
2. Preferences: Configure Runtime Arguments
3. Try to add `"disable-lcd-text": true,`
4. Also you can try to add `"disable-hardware-acceleration": true,`

**Comment by blueglyph** [comment]
Another one, as mentioned above, is to disable FXAA, either for the app or for everything.

It would just be simpler to fix the problem in the framework itself, rather than fixing it for each app. :)
