### ISSUE TITLE
Click events not working properly on touch screen devices

### ISSUE THREAD

**Issue by vhopinto86** [electron/electron#8725]
* Electron version: 1.6.0
* Operating system: Windows 7, 8 and 10

Hello,

I have a web application that in some scenarios needs to send and receive data to user peripherals through serial port. 

For this scenario i created an Electron application that hosts my web application and does the communication between the peripherals and the web app.

Everything works great except on touch screen devices in which the mouse events are not working properly when i tap the screen.

### Expected behavior

All click events should work on a touch screen running the web app throught Electron. Everything works using a regular browser.

### Actual behavior

When i launch my web application through Electron, a sign in page is shown and the touch screen works properly here. 

After signing in, the web app redirects to another page and the touch screen has a strange behavior, the touchstart/touchend events are detected, the click/mousedown/mouseup events are not.

After tapping the screen multiples times, all mouse events start to work again until i navigate to another page. Then the same thing happens again.

### How to reproduce

Get the project at https://github.com/electron/electron-quick-start then change the start page to mainWindow.loadURL('https://github.com').

Run the app, go to Sign In page and enter your credentials. 

The touch screen stops working after you sign in. If you don't have a touch screen you can use Microsoft Windows Simulator to simulate touch events.

### What was tried

After several days searching for a solution, i already tried:
  - several touch screen related command line switches like app.commandLine.appendSwitch('touch-events', 'enabled');
  - control the navigation between pages of my web application on the Electron side, using mainWindow.loadURL() or creating new instances of BrowserWindow (both options work properly using a mouse)
  - disabling node integration
  
Can someone help me with this?

Thank you

**Comment by MarshallOfSound** [comment]
@vhopinto86 Do you happen to know if this issue occurs on the latest stable release, `1.4.15`?

**Comment by vhopinto86** [comment]
@MarshallOfSound I don't know, but i will try now.

**Comment by vhopinto86** [comment]
@MarshallOfSound I just tried and this issue also accurs on the last stable release.

**Comment by vhopinto86** [comment]
@MarshallOfSound I just tried and this issue also occurs on the last stable release.

**Comment by TimvdEijnden** [comment]
We've also had this issue with a webview containing a flash element.

**Comment by KagamiChan** [comment]
@TimvdEijnden not knowing if your issue is the same as above, but here's a workaround we're using for a webview flash element not responding to touch events:
``` javascript
// Workaround for touch screen
let transformedToMouseEvent = false, isMoved = false
const webContents = remote.getCurrentWebContents()
window.addEventListener('touchend', (e) => {
  transformedToMouseEvent = false
  setTimeout(() => {
    if (!transformedToMouseEvent) {
      console.warn("Blurring focusing element")
      document.activeElement.blur()
      e.target.focus()
      if (!isMoved) {
        const x = Math.round(e.changedTouches[0].clientX),
          y = Math.round(e.changedTouches[0].clientY)
        webContents.sendInputEvent({
          type: 'mouseMove',
          x: x,
          y: y,
        })
        webContents.sendInputEvent({
          type: 'mouseDown',
          x: x,
          y: y,
          button: 'left',
          clickCount: 1,
        })
        webContents.sendInputEvent({
          type: 'mouseUp',
          x: x,
          y: y,
          button: 'left',
          clickCount: 1,
        })
      }
    }
  }, 300)
})
window.addEventListener('touchstart', (e) => {
  isMoved = false
})
window.addEventListener('touchmove', (e) => {
  isMoved = true
})
window.addEventListener('mouseup', (e) => {
  transformedToMouseEvent = true
})
```
it will "translate" touch events into input ones, but however causes inifinit loops when using simulated touch

**Comment by vhopinto86** [comment]
The code that @TimvdEijnden posted doesn't work in my case.

**Comment by tiemevanveen** [comment]
We're facing the same issue, it's the last blocking issue before we can release the app we've migrated to electron. 

In our case, we've got a webview in the main webview. After a sign out users are not able to interact with the login form any more. Inspecting the executed javscript with a timeline shows no activity at all. The touches are being registered, but the event handlers on the form elements are not being called.

**Comment by kevinsawicki** [comment]
> Run the app, go to Sign In page and enter your credentials. The touch screen stops working after you sign in.

I can reproduce this on the Windows Simulator inside a Parallels Window 10 VM. @vhopinto86 are you seeing this issue only in the simulator or on an actual device as well?

**Comment by vhopinto86** [comment]
@kevinsawicki yes, i'm getting this issue on actual devices as well, a touch screen pc and a tablet.

**Comment by Matt3o12** [comment]
I also get this issue on a 34 inch touchscreen board after a few minutes (some webpages seem to provoke it) on windows 10. I load external addresses. The mouse and keyboard still work find as well as. I can also use the touchscreen for developer tools. The only way to fix this seems to restart the electron app. 

Are there any workarounds for this issue? Or are there any version where it is known to work?

**Comment by groundwater** [comment]
I have not been able to reproduce this yet on a Windows 10 Surface Pro 4.

I took a quick look at chromium bugs here https://bugs.chromium.org but didn't see anything jump out.

I'll see if we can bring in some more windows expertise here. In the mean time, if anyone can narrow down the cause that would help greatly!

**Comment by Matt3o12** [comment]
I have found a workaround for this bug:

There seems to be an issue with touch events. Sometimes they seem to get disabled for no apparent reason (maybe there is a bug in the driver or a bug in electron for some drivers). You can observe this behavior by listening to the events (touchend and mousedown). Normally, the touchend event is fired followed by a mousedown event. When this bug occurs, only the touchend event is fired (I have also listened to all other mouse and touchscreen related events -- the touch is not cancelled and no mouse event is fired).

A workaround is to always enabled touch events (the default behavior is automatic). Add this line to your main.js file [(Source)](https://discuss.atom.io/t/touch-events-and-scrolling/36575/3):

    app.commandLine.appendSwitch('touch-events', 'enabled');

Possible values are: automatic (default), enabled (forces touch events), disabled (no touch events -- the same behavior as described by this bug report).

**Comment by vhopinto86** [comment]
@Matt3o12 Unfortunately, as i said in the first post, that command line switch does not resolve this issue in my case, although it might be the solution for other people.

**Comment by brendanadnerb** [comment]
I am having a similar issue - app.commandLine.appendSwitch('touch-events', 'enabled'); does not solve it. As @Matt3o12 said, some webpages seem to provoke it, it's hard to say how. Touch events stop working or become very slow to respond. We are building for linux and windows, and it happens on both. I've found that reverting to electron 0.36.11 makes it go away - not sure yet at which version the problem starts.

**Comment by mvladic** [comment]
I am having the same issue (I tested with Electron 1.4.15 and 1.6.3.)!

**Comment by jschlemm** [comment]
I am also having the same issue on the latest electron

**Comment by Gethi** [comment]
I am also having the same issue. 

app.commandLine.appendSwitch('touch-events', 'enabled');
Doesn't solve it.

I can't downgrade my electron version because of some API methods I'm using.

**Comment by asoap** [comment]
I am also having a very similar issue.  Our problem has been determined to be a touch-event issue.  We have to turn on that switch in order for our touch screen to work.   

The issue however is that we have a flash game loaded in a webview.  If for example you touch the flash game 5 times.  You then have to touch outside of the webview 6 times in order for a click event to fire.  It's like you have to "undo" the touch event.  We've boiled our flash down to a very simple flash file.  If a mouse is connected to the machine, this issue doesn't happen.  

Also once this 5/6 or 11/12 (however times you tap) is completed our problem goes away.  This might be one of the strangest issues I've ever had to deal with.

**Comment by krokofant** [comment]
So what should we do from here? Trying to reproduce it in chromium and submit a bug upstream? What more information do we need?

**Comment by krokofant** [comment]
I've looked at a touch screen that I've deployed an electron application to. It detects touch-events and displays different things in a webview depending on the button clicked.

Now, while looking in the console I pressed buttons on the application that appeared frozen. It took ~15 seconds for the events to register (touch-start and touch-end) and the console showed that the application started changing the webview, yet nothing happened on the screen.

I've tried to work around this before by scheduling a restart of the application and this is one time when I caught the screen in a frozen state. Not sure to blame the touch screen or electron.

**Comment by kaktuspalme** [comment]
I have exactly the same Problem. It only happens when a website inside a webview does a "HTTP 301 Moved Permanently" redirect.
I set up a build system and compiled electron. The error happens after commit 6aec1e6 -> with the update to chrome49. Before everything works fine.
I didn't have the time yet to look further.

**Comment by scrnet** [comment]
any news ? We are having this issue with latest version!

**Comment by Untweet** [comment]
We have the same problem. We created a electron application on Windows 10 with touch screen. If we use the mouse, everything is fine, but the touch doesn't work. We detected the touch event when touch the screen, but did not detect the click event. But using chrome directly work fine. We've almost tried all the electron versions after 1.2.7, and did not solve it .

**Comment by bourgondien** [comment]
I ran into the same problem with Electron in combination with a touchscreen. After a while (seemingly random) the screen will become unresponsive. Touchend is still detected by the touchscreen, but click en mouseup are not. They are however detected when using the mouse.

A strange thing I found is that the screen does become responseive again when I am in developer tools and:
- select another tab there
- resize the developer pane
- clear the log console

I do not know how this is related, but maybe it does ring a bell for someone. Does the screen re-render at those moments?

**Comment by bourgondien** [comment]
In addition to my previous comment I found that it seems the (multi-)touchscreen is falsely registering  multi-touch events: the event.touches array becomes populated with ghost touch points and touchEnd will not clear the array. This is when using the screen with just one finger. 

The number of touches in the touches array will go up after a while, becoming 7 or more, all the time just using one finger to interact.

I am testing with a capacitive multi-touch monitor from IIyama. 

Tips on how to disable multi-touch (we don't need it in this case) are appreciated.

**Comment by mkonecny** [comment]
I believe we had this problem in Windows 10, and we were able to temporarily address it by clearing the Electron cache directory

c:\Users\<username>\AppData\Roaming\<electron-appname>

And deleting all files under

c:\Users\<username>\AppData\Local\Temp

Note that AppData is a hidden directory, so you need to enable seeing hidden files/folders first.

**Comment by riebschlager** [comment]
I'm having this identical issue. None of the solutions in this thread have worked for me.

Is there a post v1.0 version that still works?

**Comment by bente** [comment]
I have resorted to checking the event.touches array 20 secs after the last user interaction. It happens that the array then is still not 0 (which it should). If that is the case I do a hide() - show() of the electron application (it is hardly visible) and that seems to solve the problem in my case.

**Comment by riebschlager** [comment]
Hey @bente, are you performing this hide/show in an event callback? Like `touchend`?

**Comment by bourgondien** [comment]
Hi @riebschlager ,   See attached file. I am saving the number of touches in touchend, and then check them when the user goes Idle (I am using Idle.js for that). When they are not 0 I do a hide()/show() of the current window. Seems to be working.

[interaction-monitor-example.txt](https://github.com/electron/electron/files/1468396/interaction-monitor-example.txt)

**Comment by leonayx123** [comment]
I'm having this identical issue on win7.
@Matt3o12 posted doesn't work in my case.

electron verison now is 1.7.9.   Is there any great God who can help me?

**Comment by StevenLiSiwei** [comment]
Having the same issue here

**Comment by obermillerk** [comment]
Hi,
So we're working on an electron app in Windows 10 and we've been getting what I believe is this issue intermittently for months now. We would have to touch a certain number of times on each page before touch events would respond again (usually around 3).

Just recently, we integrated the Mottie Virtual Keyboard library into our app, and this led to the discovery that for some reason each key pressed on the keyboard would consistently add one touch to this number when navigating to the next page. ***This behavior only shows up in builds, not running from source.***

I'm not sure how I could go about debugging this myself, but I at least have something that creates consistent behavior for me, so I've made a clone of electron quick start that will show this behavior so that hopefully the electron devs can debug this.

The repo can be found [here](https://github.com/obermillerk/electron-touch-issue).

### Reproduction Instructions
```
git clone https://github.com/obermillerk/electron-touch-issue
cd electron-touch-issue
npm i
./node_modules/.bin/build
```

Installer will be located in `dist` folder in the root of the project.  Install the application, and run it.

Click the link to navigate to the page with the keyboard plugin.  Focus the input, and touch a single key on the virtual keyboard.

Click the link to navigate back to the other page. You will now have to touch once before touches respond. 

You can keep typing characters and the number of touches should compound, building up until you restart the app.

Note that I made this able to be opened in a web browser (such as chrome) and this behavior is not exhibited, so I can only assume that this is an electron issue.  Either that or it's an issue with the old version of V8 that electron uses.

**Comment by dfblackburn** [comment]
I am also seeing this issue and am also using the Mottie keyboard.

**Comment by StevenLiSiwei** [comment]
This one might relevant to windows 10 multi touch gestures on windows 10 after doing days of researching, and there is no way of disabling multi touch gestures on touch monitor on Windows 10 (except on touchpad). I will give a try downgrading to windows 7 (with multi gestures touch disabled) and see how it goes and get back to here.

**Comment by obermillerk** [comment]
I've just updated my demo.  I discovered that touch events are actually fired, but they do not get translated.

I added a button on the initial page that logs `click`, `mousedown`, `mouseup`, `touchstart`, `touchend`, `touchmove`, and `touchcancel` events.  You can tap this button after typing one key on the keyboard and see that `touchstart` and `touchend` events are fired with no mouse events, and then tap a second time and see that `touchstart` and `touchend` are quickly followed by `mousedown`, `mouseup`, and `click` events.

**Comment by dfblackburn** [comment]
I was experiencing this on WES7 multi touch, so it is not specific to Win10.

**Comment by vhopinto86** [comment]
I also had this issue on Windows 7 and 8.

**Comment by jbcpollak** [comment]
We have this problem on Ubuntu 16.04.

**Comment by brendanadnerb** [comment]
We have this happening on Linux as well. I've never seen it on Mac (our dev environment). Windows 10 seems to have similar issues, but slightly different (we dev for Windows and Linux).

**Comment by brendanadnerb** [comment]
again - for me, I think 0.36.11 was the cutoff where after that version we started seeing it, on both Windows and Ubuntu. I'm kinda mystified as to why - I think Chromium didn't even update until a couple more, if I remember.

**Comment by obermillerk** [comment]
I've developed a workaround similar to and inspired by @KagamiChan's original workaround.  I've modified it to assume that all touches will not be translated to clicks, and prevent this from happening if it would, instead relying solely upon creating clicks myself.  The advantage of assuming that the clicks won't be created is that there won't be that brief delay on the click so it will feel more responsive.

It uses `event.preventDefault()` on `touchend` events to prevent the Chromium engine from converting them to clicks while allowing for touch scrolling to be handled natively.  I also added support for multiple touches, as well as double clicks and beyond.  Additionally, calling `event.preventDefault()` from any `touchend` or `touchstart` listeners in your code will prevent the false click events from firing as well.

Ideally this code should be run as soon as possible in any page it's in, but it should be okay in most cases if it isn't the first thing that's run.

```
// List of active touches.
var activeTouches = {};
// Click counter
var numClicks = 0;
// Timer for reseting click counter, so it may be cleared.
var clickCountTimer = null;
// Reference to the last touch object received at a location;
var lastTouch = null;
// Distance away from initial touch that constitutes cancelation, or disqualifies from doubleclick.
const moveThreshold = 10;

const webContents = require('electron').remote.getCurrentWebContents();

var handlers = {};

// Handler for touchstart events. Tracks active touches.
handlers.touchstart = function(event) {
    // Store touches for later use.
    var touches = Array.from(event.changedTouches);
    touches.forEach((touch) => {
        touch.defaultPrevented = event.defaultPrevented;
        activeTouches[touch.identifier] = touch;
    });
}

// Handler for touchend events. Tells main process to generate mouse events.
handlers.touchend = function(event) {
    // Check if somebody tried to prevent touches from becoming clicks.
    let defaultPrevented = event.defaultPrevented;
    // Prevent touches from being translated to clicks, do it ourselves
    event.preventDefault();
    // Translate corresponding touches to mouse events.
    var touches = Array.from(event.changedTouches);
    touches.forEach((end) => {
        var start = activeTouches[end.identifier];
        // Check if defualt was prevented in touchstart also.
        defaultPrevented = defaultPrevented || start.defaultPrevented;
        delete activeTouches[end.identifier];

        // Don't fire click if the default action was prevented by user
        //   or if the touch was otherwise cancelled (cancel or too much movement)
        if (defaultPrevented !== true && start !== false) {
            const x = Math.round(end.clientX),
                y = Math.round(end.clientY);
            // Keep track of the number of clicks within 500ms of eachother closer than the moveThreshold
            // (for double clicks)
            if (numClicks == 0 || dist(lastTouch, end) <= moveThreshold) {
                numClicks++;
            } else { // numClicks > 0 && dist > moveThreshold
                clearTimeout(clickCountTimer);
                numClicks = 1;
            }
            lastTouch = end;
            if (numClicks == 1) {
                clickCountTimer = setTimeout(function() {
                    numClicks = 0;
                    lastTouch = null;
                    clickCountTimer = null;
                }, 500);
            }
            falsifyClick(x, y, numClicks);
        }
    });
}

// Capture touchstart, touchend events first thing when they happens.
document.addEventListener('touchstart', captureHandler, {
    capture: true,
    passive: false
});
document.addEventListener('touchend', captureHandler, {
    capture: true,
    passive: false
});

function captureHandler(event) {
    var stopPropagation = event.stopPropagation;
    var stopImmediatePropagation = event.stopImmediatePropagation;
    // Ensure that our handler is called for touchstart, even if propagation of the event is stopped.
    //   Keeps everything clean.
    event.stopPropagation = function() {
        stopPropagation.apply(event);
        handlers[event.type](event, true);
    }
    event.stopImmediatePropagation = function() {
        stopImmediatePropagation.apply(event);
        handlers[event.type](event, true);
    }
}

// Listen for bubbling touchstart events on the document.
document.addEventListener('touchstart', handlers.touchstart, {
    capture: false,
    passive: false
});

// Listen for bubbling touchend events on the document.
document.addEventListener('touchend', handlers.touchend, {
    capture: false,
    passive: false
});

// Cancel corresponding touches if touch was canceled.
document.addEventListener('touchcancel', function(event) {
    var touches = Array.from(event.changedTouches);
    touches.forEach((touch) => {
        activeTouches[touch.identifier] = false;
    });
},  {
    capture: true,
    passive: true
});
// Cancel corresponding touches if touch moved too much.
document.addEventListener('touchmove', function(event) {
    var touches = Array.from(event.changedTouches);
    touches.forEach((touch) => {
        var start = activeTouches[touch.identifier];
        if (start === false) {
            return;
        }

        if (dist(start, touch) > moveThreshold) {
            activeTouches[touch.identifier] = false;
        }
    });
},  {
    capture: true,
    passive: true
});

function falsifyClick(x, y, numClicks) {
    webContents.sendInputEvent({
        type: 'mouseMove',
        x: x,
        y: y
    });
    webContents.sendInputEvent({
        type: 'mouseDown',
        x: x,
        y: y,
        button: 'left',
        clickCount: numClicks
    });
    webContents.sendInputEvent({
        type: 'mouseUp',
        x: x,
        y: y,
        button: 'left',
        clickCount: numClicks
    });
}

// Calculates the distance between two touches.
function dist(touch1, touch2) {
    return Math.hypot(touch1.clientX - touch2.clientX, touch1.clientY - touch2.clientY);
}
```

**Comment by davismiculis** [comment]
Hello, having same touch screen issues on Windows 7 and Electron 1.8.3

Touch events just stop working if I start to click a lot on screen, on my touch device. No events are logging in console. Sometimes by randomly clicking a lot it unfreezes and starts working, but still buggy.

**Comment by mkazlauskas** [comment]
This issue is pretty serious for some users. We had to migrate to nw.js because of it.

**Comment by davismiculis** [comment]
Is there any temporary fix for this issue? I've tried all above mentioned code, it doesn't work. I'm trying to figre out how to disable touch events, and make them as mouse events at Electron or Windows 7 level.

**Comment by obermillerk** [comment]
@davismiculis The issue you're describing seems like a different issue, perhaps even just your hardware being unable to handle so many touches and getting way bogged down trying to catch up?  Do the events ever log after is unfreezes or do they just get swallowed? Also, when you say no events are logged, are you logging touch events or just click/mouse events?  A key characteristic of this bug seems to be that touch events appear, but they are not translated to mouse events for some reason, so if you're only looking for mouse events try seeing if the touch events are still working.

We also had a separate, seemingly unrelated issue where clicking too early before a page fully loads would prevent any touch events from registering, which seems like it is possibly similar to what you're describing.  This issue could be solved by unfocusing the window and refocusing it, after which touch events would work, however this is not desirable behavior and we never had any sort of automatic work around for this but it seemed to mostly go away as far as I can tell.

Also, as some people seem to suggest higher up in the thread that certain developer tools actions can fix touch issues, and I seem to recall that I've gotten different behavior from electron based on whether or not dev tools is open in the past, I would suggest attempting to replicate the issue without dev tools open and see if it's still persistent.

**Comment by cdubois** [comment]
@mkazlauskas Agreed this is serious, inconsistent, and very inconvenient.  The code posted to this thread by @obermillerk did resolve this issue for us.  It is a thorough piece of work; if we did such a workaround ourselves it would not have covered nearly as many cases.

For us, the touch events were often failing for multiple seconds/minutes after any page loads on Windows.  It feels like an eternity.  Once the page recovers from whatever, touch events begin to fine.  As ours was a Vue app, the full page reloads did not occur very often.

The patch from @obermillerk did the trick, at least until it is resolved in Electron proper.

**Comment by davismiculis** [comment]
@obermillerk this doesnt seem to be hardware issue, because opening IE or Chrome browser and trying to get the touch lag, I cant reproduce it. It only bugs out in an Electron app, everything else outside app works fine all the time.

I will try your blur/focus fix and report here.

**Comment by davismiculis** [comment]
@obermillerk focus/blur didnt work for me, here's what I tried
minimize:
```
mainWindow.blurWebView()
mainWindow.hide()
mainWindow.minimize()
```
after some time, maximize:
```
mainWindow.focusOnWebView()
mainWindow.show()
mainWindow.maximize()
```

**Comment by obermillerk** [comment]
@davismiculis unfortunate... I never tried doing it programmatically, I would just alt tab, but I assume the effects would be the same. I would ask again to try replicating with dev tools closed if you aren't already, and whether you're able to see touch events, but if my fix didn't work then likely you aren't getting touch events either, in which case you probably have a different issue.  There were several other posts I found when investigating this that referenced an electron command line switch that you can enable that force enables touch capabilities, it didn't help me but maybe that will help you seeing that your issue seems different.  Otherwise, I have no suggestions for you other than to look at other electron touch related issues or create your own, sorry.

**Comment by davismiculis** [comment]
@obermillerk nope, touch events arent logging, and alt+tabbing didnt help, I also tried this:
```

**Comment by obermillerk** [comment]
Unfortunately anything more is beyond my knowledge, but this seems to be a totally different issue so I would suggest going to other threads or perhaps making your own, somebody else may be able to help you more than I can.

**Comment by davismiculis** [comment]
Most simple code to reprduce, create empty electron app with this code:
```
let electron = require('electron')

let mainWindow

electron.app.on('ready', function () {
	mainWindow = new electron.BrowserWindow()
	mainWindow.loadURL('https://www.businessinsider.com')
})

electron.app.on('window-all-closed', function () {
	if (process.platform !== 'darwin') {
		electron.app.quit()
	}
}
```

And then using touch screen rapidly tap on BusinessInsider header navbar buttons, until touch becomes unresponsive.

**Comment by davismiculis** [comment]
Hi, is there any progress on this, is the bug aknowledged and/or recreated on other platforms, devices, anyone tried?

**Comment by davismiculis** [comment]
Hi, just wondering if anyone is fixing it?

**Comment by davismiculis** [comment]
Hi, to view videos, you need to login into Electron Slack channel.

Here is a video of Electron touch screen issue - https://files.slack.com/files-pri/T043R3J9D-FA9R8E56K/download/image_uploaded_from_ios.mov

Also noticed that two finger gestures, like pinch-to-zoom unfreezes touch issue - https://files.slack.com/files-pri/T043R3J9D-FA8LULW5R/download/image_uploaded_from_ios.mov

**Comment by akashnimare** [comment]
Can you folks reproduce this issue using the [muon](https://github.com/brave/muon) which is a forked version of electron -
https://github.com/brave/muon-quick

**Comment by davismiculis** [comment]
@akashnimare Trying at the moment. Do I just do this?
```json
  "devDependencies": {
    "electron-prebuilt": "brave/electron-prebuilt",
    "electron-builder": "brave/electron-builder",
    "electron-packager": "brave/electron-packager"
  }
```

**Comment by davismiculis** [comment]
Yes, using what I mentioned in previous comment, we now built our app using Brave fork of Electron and it doesnt have touch issues. Only difference is that the `webcontents.clearHistory()` method is missing now. But thats okay.

**Comment by ckerr** [comment]
Is this issue still happening in the Electron 2.0.x betas?

**Comment by akashnimare** [comment]
@ckerr I think @davismiculis used that version only (Electron 2.0.x).

**Comment by davismiculis** [comment]
@ckerr I tested it on Electron 1.7.x 1.8.x and 2.0 beta 7, touch froze on all these versions.

**Comment by feichao** [comment]
I have the same issue...

```
<body>
  <div class="webview-container">
    <webview class="webview" preload="./preload.js" nodeintegration src="src/webviews/welcome/index.html"></webview>
    <webview class="webview" preload="./preload.js" nodeintegration src="src/webviews/launcher/index.html"></webview>
    <webview class="webview" preload="./preload.js" nodeintegration src="src/webviews/hotspot/index.html"></webview>
  </div>
</body>
```

The touchstart/touchmove/touchend event fired in the three webviews not fired in the parent body, but the click/mousedown/mouseup/mousemove event fired both the webviews and the parent body.

And my APP Version is "...Chrome/61.0.3163.100 Electron/2.0.1 Safari/537.36...", I have tried Electron/1.3 and Electron/1.4 and Electron/2.0.2, completely annihilated...

Finally, I use the ipc communication with preload and nodeintegration to solve my problem. Maybe you can try it... @vhopinto86

**Comment by mdanics** [comment]
Any updates on this? Facing this issue in Electron 2.0.2

**Comment by markonyango** [comment]
What device are you using?

**Comment by mdanics** [comment]
@markonyango happens on dell xps when using touch screen mode

**Comment by clintLandrum** [comment]
@feichao Could you provide some more info/code examples on how you solved this?

**Comment by feichao** [comment]
Sorry, I misunderstand the question. Actually, mine is more like #6563. But I have tested this question on my device, everything is OK. My electron version is `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Electron/2.0.2 Safari/537.36`.

**Comment by mijdavis2** [comment]
Similar issue. First touch on many buttons don't trigger the click. Here's the weird kicker, a double click will trigger the click **twice**. 

For example, I have a button where it's click event triggers the save dialogue API: single-click => nothing; double click => two save dialogues pop up. This is on a Windows 10 tablet. Another kicker, it worked fine on an old Windows 8 tablet.

**Comment by zibra** [comment]
Same issue here. Is there any update?

**Comment by checkin247** [comment]
same issue with electron 2.0.8

**Comment by krokofant** [comment]
Not sure if this is already mentioned but I used pm2 to watch over the electron process and just restart it every two or four hours. It's not pretty but it works. Might abort someone's work though. On our project he issue occurred sporadically.

**Comment by checkin247** [comment]
had the same error with an app built with electron-forge on electron 2.0.8 
running the package with `electron .` worked fine
running app.exe the error occured after a few seconds
missing in depth knowledge I made a new build with [electron-build](https://github.com/electron-userland/electron-builder) using NSIS (instead electron-forge and windows.squirrel) what solved the problem with the click events using touch input device.
Hope this helps someone

**Comment by gliss** [comment]
I'm having similar issues where the touch would stop working on W10 machines. It happens randomly and with no common reasons. I can remotely connect to the device and click on buttons and it all works fine. To fix it I have to close the app and restart it. The other weird thing is is that even windows doesn't respond to touch ie swiping in from the side to switch between app.

Im a bit lost on where to go from here.

**Comment by 2c2c** [comment]
To those of you with this issue: If you hold right click, does your left click events then register? In my case it does, and I'd like to confirm I'm experiencing the same issue described in this thread.

Thanks

**Comment by andrewjbxandrew** [comment]
Is there any update to this issue? I have our Electron app running full screen on W10 with Elo touchscreens. If you don't touch the screen for a while (4 or 5 hours) then the app stops registering touch. (you can see the touch is working with 'halo' effect and hear a motherboard beep however) I can also sort of drag the touch and highlight text elements on the Electron screen, but touch doesn't work. Rebooting the app solved the problem right away. If I remote into the machine during the 'frozen' state, I can still use the mouse to navigate around the app. Need to figure out how to fix this! Anyone have any more ideas?

**Comment by checkin247** [comment]
@andrewjbxandrew 
I resolved it as stated [here](#issuecomment-417402052).
I believe the issue is related to the tool you use for building your application.

**Comment by carlokid** [comment]
Hi @checkin247
I am trying your suggestion to use electron-build with angular app. I was able to create a installer successfully. But upon application startup, it's just a black screen, without any error in console. It seems its not getting bundled modules. Do you have idea?

> @andrewjbxandrew
> I resolved it as stated [here](#issuecomment-417402052).
> I believe the issue is related to the tool you use for building your application.

**Comment by carlokid** [comment]
Nevermind. Finally got it working now.

So... for testing result. It is still not working. We removed the mouse on actual kiosk machine. At first it worked, but after some idle time, problem occur again, touch events not working.

**Comment by carlokid** [comment]
Just an update for me with exactly the same issue as explained by @bourgondien [here](https://github.com/electron/electron/issues/8725#issuecomment-338662449).

The fix from @obermillerk [here](https://github.com/electron/electron/issues/8725#issuecomment-350786200) actually did the trick but seems not properly handling scroll events yet.

Hope that electron team would apply fix soon.

**Comment by carlokid** [comment]
I got the exact the same issue as explained by @bourgondien [here](https://github.com/electron/electron/issues/8725#issuecomment-338662449).
The fix from @obermillerk [here](https://github.com/electron/electron/issues/8725#issuecomment-350786200) actually did the trick but seems not properly handling scroll events yet.

Hope that electron team would apply fix soon.

**Comment by ronaknewtonsit** [comment]
@carlokid  I have posted the [solution here](https://newtons.gitbook.io/knowledge/electron/multiple-rapid-touch-webview). Can you please try it?

**Comment by carlokid** [comment]
> @carlokid I have posted the [solution here](https://newtons.gitbook.io/knowledge/electron/multiple-rapid-touch-webview). Can you please try it?

@ronaknewtonsit It is not the same issue as I'm not using a webview. The issue is explained thoroughly by [here](https://github.com/electron/electron/issues/8725#issuecomment-338662449)

**Comment by carlokid** [comment]
This is 2 years ago but still no fix :(

**Comment by pbmzero** [comment]
I read this thread several times over a few weeks after encountering the same issue. I did testing on a verity of different touch screens and windows-based operating systems ran into a lot of problems with remote content in a <webview>.  If you take a look at the [webview-tag documentation](https://electronjs.org/docs/api/webview-tag) with a note as follows: 

> We currently recommend to not use the webview tag and to consider alternatives, like iframe, Electron's BrowserView, or an architecture that avoids embedded content altogether.

This advice seems to conflict with electron docs for [security docs](https://electronjs.org/docs/tutorial/security)

> Under no circumstances should you load and execute remote code with Node.js integration enabled. Instead, use only local files (packaged together with your application) to execute Node.js code. To display remote content, use the <webview> tag and make sure to disable the nodeIntegration.

That said i have to do away with <webview> tag, just like  @mitchhh 's video i could easily cause the touch to fail with just some doubleclicking on a few hyperlinks.  Currently i'm instead opening remote content in a separate BrowserWindow with webSecurity turned and node integration turned off and the touch works.    Not clear on what how secure this is. I had not tried the <iFrame> approach yet. 

Also my caret disappears from input boxes after aggressive touching as per issue #13261 in versions above 4.x  (works ok in 1.8.8) and webContents.sendInputEvent() will not work with <webview> in versions 3.x (works ok 1.8.8)

**Comment by imZEH** [comment]
Hello Guys,

Did this issue still happen on the latest version of the electron ?

**Comment by kohtaro24** [comment]
I have this problem with electron 4.0.1.

**Comment by KonovalovaKV** [comment]
This error is reproduced regardless of the platform and version of the electron. It is very sad. This eliminates the possibility of using touch devices.
At the same time, there is no such problem in chromium, as well as nwjs. This is electron error. Error is already 2 years old, no one reacts.

In a recent task (#17552), the problem is clearly described.

**Comment by KonovalovaKV** [comment]
Any news?

**Comment by pbmzero** [comment]
Guys, I "fixed" this by removing all the <webview> tags in my apps back in January. No issues since on various electron versions / touch hardware / windows OS versions

**Comment by gliss** [comment]
> Guys, I "fixed" this by removing all the webview tags in my apps back in January. No issues since on various electron versions / touch hardware / windows OS versions

Could you elaborate a bit more?

**Comment by pbmzero** [comment]
> > Guys, I "fixed" this by removing all the webview tags in my apps back in January. No issues since on various electron versions / touch hardware / windows OS versions
> 
> Could you elaborate a bit more?

Sure, so my app(s) previously included webview-tag [https://electronjs.org/docs/api/webview-tag] primarily because i was following Electron's security best practices document which recommends it. If you interact with a webview tag through a touch screen you will cause touch to stop working entirely. It could be in as few as 3 touches.  This is best demonstrated in an earlier comment by [`mitchh`](https://github.com/electron/electron/issues/8725#issuecomment-382316338) where in his video he shows a few rapid succession touches (specifically during a navigation event) would lock touch for the application until completely reset. At which point a number of other side effects occur including  input boxes being unselectable [https://github.com/electron/electron/issues/13261]( #13261 ) and the windows accessibility features suddenly becoming disabled so soft keyboards cannot detect focus on the input box.. yet the mouse works fine.   Once the webview-tag was completely gone i've had no touch problems since so that tag seems highly unstable.

**Comment by KonovalovaKV** [comment]
> > > Guys, I "fixed" this by removing all the webview tags in my apps back in January. No issues since on various electron versions / touch hardware / windows OS versions
> > 
> > 
> > Could you elaborate a bit more?
> 
> Sure, so my app(s) previously included webview-tag [https://electronjs.org/docs/api/webview-tag] primarily because i was following Electron's security best practices document which recommends it. If you interact with a webview tag through a touch screen you will cause touch to stop working entirely in your electron app. It could be in as few as 3 touches. This is best demonstrated in an earlier comment by [`mitchh`](https://github.com/electron/electron/issues/8725#issuecomment-382316338) where in his video he shows a few rapid succession touches (specifically during a navigation event) would lock touch for the application until completely closed and reopened. At which point, a number of other side effects occur including input boxes being unselectable [https://github.com/electron/electron/issues/13261](#13261) and the windows accessibility features suddenly becoming disabled ( so soft keyboards cannot detect focus on the input box..). Once the webview-tag was completely gone i've had no touch problems since so that tag seems highly unstable.

What was the webview tag replaced?

**Comment by gliss** [comment]
Unfortunately I don't use the webview tag so must be something else.

**Comment by carlokid** [comment]
Hi all, would like to reiterate the fix I found also here in this thread. Note that I am not using webview or iframe. Just directly loading the application through index.html.

Fix here - https://github.com/electron/electron/issues/8725#issuecomment-433611031

**Comment by gliss** [comment]
> > Unfortunately I don't use the webview tag so must be something else.
> 
> Do you use iFrames tags by any chance? I did not get a chance to test to see if they had the same issue as webview tags, but they could.

No, just like carlokid I load a local html file. I'm also using the additional script to convert touch events to clicks in an angularjs app.

**Comment by pbmzero** [comment]
> > > Unfortunately I don't use the webview tag so must be something else.
> > 
> > 
> > Do you use iFrames tags by any chance? I did not get a chance to test to see if they had the same issue as webview tags, but they could.
> 
> No, just like carlokid I load a local html file. I'm also using the additional script to convert touch events to clicks in an angularjs app.



> Hi all, would like to reiterate the fix I found also here in this thread. Note that I am not using webview or iframe. Just directly loading the application through index.html.
> 
> Fix here - [#8725 (comment)](https://github.com/electron/electron/issues/8725#issuecomment-433611031)
> 
> I copy the fix on a touch.js file and include it under scripts of angular.json (for angular app)

I had #8725 in my app for 6 months and still was locking up all the same but i was still using that webview-tag at that period.  I removed the code for #8725 at the time i had removed content from within that tag. I only develop touchscreen applications and not a single touch issue over the last 6 months and we use several brands of touch screens.  Can you please post a minimal code example with this issue so I can test and modify? I would also like to understand why that's the case. It can be solved without any click emulation code.

**Comment by u4aew** [comment]
Hi, the problem disappeared in 5.0.6?

**Comment by Eman0d** [comment]
I found a way to detect the problem described here : "https://github.com/electron/electron/issues/8725#issuecomment-338662449" ,and restart the electron app whenever it is detected as a recovery.

The attached code hooks the window message 'WM_POINTERDOWN' [which indicates a touch down on app screen] to save the time of the each touch on app screen , it also listens to 'Click' event to save the time of each click , if the time between the last touch and last click event exceeds 30 seconds ,then problem is detected , I then restart my electron app.

I hope this helps!

[renderer.txt](https://github.com/electron/electron/files/3674972/renderer.txt)
[main.txt](https://github.com/electron/electron/files/3674983/main.txt)

**Comment by Eman0d** [comment]
I found a way to detect the problem described here : https://github.com/electron/electron/issues/8725#issuecomment-338662449  and restart the electron app whenever it is detected as a recovery.

The attached code hooks the window message 'WM_POINTERDOWN' [which indicates a touch down on app screen] to save the time of the each touch on app screen , it also listens to 'Click' event to save the time of each click , if the time between the last touch and last click event exceeds 30 seconds ,then problem is detected , I then restart my electron app.

I hope this helps!

[renderer.txt](https://github.com/electron/electron/files/3674972/renderer.txt)
[main.txt](https://github.com/electron/electron/files/3674983/main.txt)

**Comment by u4aew** [comment]
> I found a way to detect the problem described here : [#8725 (comment)](https://github.com/electron/electron/issues/8725#issuecomment-338662449) and restart the electron app whenever it is detected as a recovery.
> 
> The attached code hooks the window message 'WM_POINTERDOWN' [which indicates a touch down on app screen] to save the time of the each touch on app screen , it also listens to 'Click' event to save the time of each click , if the time between the last touch and last click event exceeds 30 seconds ,then problem is detected , I then restart my electron app.
> 
> I hope this helps!
> 
> [renderer.txt](https://github.com/electron/electron/files/3674972/renderer.txt)
> [main.txt](https://github.com/electron/electron/files/3674983/main.txt)

version  electron ?

**Comment by Eman0d** [comment]
> version electron ?

@u4aew I reproduced the issue using different versions of electron , v4.2.10 , v6.0.9 and other versions.

**Comment by bribrah** [comment]
I have this problem on latest electron release

**Comment by bribrah** [comment]
bumpppp

**Comment by FibreFoX** [comment]
As @Eman0d pointed out, this probably should not only be tagged to v2, as this issue can be found on later versions too.

**Comment by jbcpollak** [comment]
we are experiencing basically exactly the same situation as @chap-wong on Electron 9.1.1 and Ubuntu 18.04

**Comment by anselmhou** [comment]
Anybody knows/tried on the latest version of the electron?  Is this issue still persist?

**Comment by zkc168** [comment]
> 我在 Ubuntu 18.04 上运行的最新电子版本上也有同样的问题。
> 我们有一个在电子上运行的自助服务终端应用程序。刚开始应用在触摸屏上运行良好，但长时间闲置后，触摸屏启动失败，我们仍然不知道触发该错误的确切原因。
> 
> 当bug发生时，我们仍然可以通过触摸屏幕来移动光标，但所有元素（包括链接）都变得不可触摸。但是，当我们插入鼠标时，鼠标可以点击应用程序，但触摸屏仍然无法正常工作，直到我们**按alt+tab**来回切换窗口，然后触摸屏才开始工作。
> 
> 我希望这可以帮助进一步解决这个问题。



> 我在 Ubuntu 18.04 上运行的最新电子版本上也有同样的问题。
> 我们有一个在电子上运行的自助服务终端应用程序。刚开始应用在触摸屏上运行良好，但长时间闲置后，触摸屏启动失败，我们仍然不知道触发该错误的确切原因。
> 
> 当bug发生时，我们仍然可以通过触摸屏幕来移动光标，但所有元素（包括链接）都变得不可触摸。但是，当我们插入鼠标时，鼠标可以点击应用程序，但触摸屏仍然无法正常工作，直到我们**按alt+tab**来回切换窗口，然后触摸屏才开始工作。
> 
> 我希望这可以帮助进一步解决这个问题。



> I also have the same issue on latest electron version running on Ubuntu 18.04.
> We have an kiosk app running on electron. At the beginning the app works fine on touch screen, but after long idle time, the touch screen start fail to work, we still don't know the exact reason to trigger such bug.
> 
> When the bug occur, we can still move the cursor by touch the screen, but all elements (including links) become untouchable. However, when we plugin the mouse in, the mouse can click on the app, but the touch screen still not working properly, until we **press alt+tab** to switch the window back and forth, then the touch screen start working as beginning.
> 
> I hope this can help to further tackle down the issue.

How do you get around this problem

**Comment by carlokid** [comment]
Reiterating the solution to here: 
https://github.com/electron/electron/issues/8725#issuecomment-433611031

**Comment by alter-sachin** [comment]
hey everyone, i am planning to create a high definition video streaming kiosk where the user goes through a list of videos on the touch screen kiosk.
Imagine Netflix on a big touchscreen television where touch us the primary mode of input.
I am worried about choosing the right technology stack.
Hardware side : Are raspberry Pi's able to handle HD video playing via electron ? What companion computer would you recommend to connect to the touchscreen display.

Software : This issue makes me think electron might not be right for touch screen displays. Any other recommendations here ?


I understand this is an interesting place for me to ask this, but all of you seem like very well equipped to atleast guide me to a good direction.

**Comment by janvlug** [comment]
Maybe this issue is causing [Online keyboard stops working after selecting file to send](https://gitlab.com/undef1/signal-desktop-builder/-/issues/6) on Signal Desktop on the Librem 5 Linux phone. The Librem 5 has an arm64 architecture. If this is indeed the same issue, then a "platform/linux" label might have to be added to this issue.

**Comment by FibreFoX** [comment]
"bump" (github-action-bot told me this is a "good" idea ... stupid bot)

**Comment by FibreFoX** [comment]
Is this issue "abandoned"? This "stale"-bot is always hitting this, but this issue seems to be ignored by the devs.

**Comment by Xenofex** [comment]
Touch events still not working on Ubuntu 20.04 LTS. On the same machine, Chromium browser does not have touch events support out-of-the-box, but can be enabled via the `--touch-events` switch. However Electron does not provide an way to pass this switch, at least from my search.

**Comment by Dayasagar543** [comment]
hey is the issue resolved

**Comment by FibreFoX** [comment]
What is the current state of this? Or just getting ignored?

**Comment by foxxy432** [comment]
It is ignored by Microsoft because of incompatibilities BUT you can use my fork: https://github.com/lnxx-kernel/electron_touch

**Comment by dicklwm** [comment]
https://github.com/dicklwm/electron-touch-bug-8725
I have found an evasive solution to this problem.

**Comment by yashrajsapra** [comment]
Displaying a popup cannot be a part of the product. Do we have a permanent solution for this instead of temporary fixes?

**Comment by onedotover** [comment]
This is still an issue in the latest version of electron. Repro steps are pretty easy. Just add javascript like below to the app and then touch the screen rapidly. The count should go from 0=>1=>0 or even 0=>1=>2=>1=>0 if you tap one finger and then land another finger on the app.

What you find is the counter will not fire the touchend event and then it's effectively "stuck" because the app thinks the user's finger is still on the screen.

```
    let touches = 0;
    document.addEventListener(
      'touchstart',
      function () {
        touches++;
        console.log('Touch Start', touches);
      }
    );
    document.addEventListener(
      'touchend',
      function () {
        touches--;
        console.log('Touch End', touches);
      }
    );
```

**Comment by jiwonkim19** [comment]
Bump. Still running into this issue now in February 2025. We have over a hundred Windows 10 kiosks deployed and just recently ran into this bug at a location for the first time. So it is not a consistent bug. Will try the hacks mentioned above and report back.

**Comment by jiwonkim19** [comment]
Bump. Still running into this issue now in February 2025. We have over a hundred Windows 10 kiosks deployed and just recently ran into this bug at a location for the first time. So it is not a consistent bug. Will try the hacks mentioned above and report back.
