### ISSUE TITLE
webContents.print not working on windows since v1.6.1

### ISSUE THREAD

**Issue by barbalex** [electron/electron#8828]
seems to be same problem as here: https://github.com/electron/electron/issues/4906

It happens on windows 10 with electron version 1.6.1.
When I downgrade to 1.4.15 it works.

**Comment by barbalex** [comment]
According to #4906 "pdf.dll" would be missing and replacing it would solve the problem.

I tried to search for "pdf.dll" but can't find it in my project folder where electron v. 1.4.15 is installed.
I also would not know where to place it.

**Comment by yahyaKacem** [comment]
Having the same problem with windows 10 and 7 too, even though it work fine on Mac os x 10 sierra.
tried with electron v1.6.1 and v1.6.2.

**Comment by bsclifton** [comment]
this may or may not help- for our fork of Electron (Muon), @darkdh created this patch to solve the problem https://github.com/brave/muon/pull/166

**Comment by Tup3x** [comment]
Yeah, I have this issue too on Electron 1.6.2 (Windows 10, 64-bit). It's stuck at spooling. Neither webContents.print (nor window.print(); outside main) works but webContents.printToPDF does work.

**Comment by rreimann** [comment]
Downgrading to 1.4.15 fixes printing entire documents but still fails for me while trying to print page ranges that omit the first page - see https://github.com/electron/electron/issues/8489#issuecomment-286115118 for details.

**Comment by TimvdEijnden** [comment]
We've released a new version of our app last week with this issue 😢 . A user just contacted us about it. I hope it's easy fix that will be in 1.6.x soon!

**Comment by redhotbeani** [comment]
We have this issue also in Windows 7, 32 bit with Electron 1.6.2

**Comment by TimvdEijnden** [comment]
I'd love to create a PR but I have no idea where to start. @kevinsawicki can you point me in the right direction on how to fix this?

**Comment by TimvdEijnden** [comment]
I was hoping this would be fixed in the next 1.6.x version. @zcbenz maybe you can help me getting this solved?

**Comment by kevinsawicki** [comment]
> I'd love to create a PR but I have no idea where to start. @kevinsawicki can you point me in the right direction on how to fix this?

Apologies for not replying sooner, I've pushed up a fix in #9111 if you get a chance to build/test it and confirm it fixes things for you, thanks for the help.

**Comment by TimvdEijnden** [comment]
I've been trying to build your branch on windows 10 with VS Community 2015 but without success. But there are other confirmations, we'll try the 1.6.6 pre-release.

**Comment by jydarche** [comment]
Hi, I can confirm that the problem is fixed in the version 1.6.6. Thanks!

**Comment by ishwarrimal** [comment]
I am using 1.7.6 and still facing the same issue. It gets stuck at spooling. It is working properly on my dev machine but when we released it in production then all our users complained about printing not working. It gets stuck at spooling in their machine and nothing gets printed. It does not show any size of the file as well. Please let me know if there is any fix for this.

**Comment by ishwarrimal** [comment]
It seems that this issue is not happening because of print function directly but it is due to some npm dependency module.  It started working for me after "npm update" and then rebuild electron. I wasted 15 days in this issue but fix for me was just updating the npm dependencies using npm update.

**Comment by hustzju** [comment]
> It seems that this issue is not happening because of print function directly but it is due to some npm dependency module. It started working for me after "npm update" and then rebuild electron. I wasted 15 days in this issue but fix for me was just updating the npm dependencies using npm update.

I encounter the same issue. The app  works fine and prints OK on  most users' computers, but  the spooling problem  happens on a few users' PC. Even stranger, it works on development  environment, and doesn't work on  .exe install  environment.
This problem  has wasted me many days, could you give me some suggesttions? I will really appreciate it
