### ISSUE TITLE
React devtools not working as described in docs

### ISSUE THREAD

**Issue by johnthedebs** [electron/electron#915]
### Summary

I'm trying to use react-devtools with atom-shell as described [here](https://github.com/atom/atom-shell/blob/master/docs/tutorial/devtools-extension.md) in the docs, but the React tab doesn't show up in the Developer Tools panel as expected.

I put the line `require("remote").require("browser-window").addDevToolsExtension("../react-devtools");
` in the html file being loaded into the browser window which gives no console output, but does give a file not found error if I switch to an incorrect path.

I've also tried entering the line manually from the Developer Tools console, in which case it returns the string "React Developer Tools" but doesn't appear to do anything else.

### Versions

atom-shell 0.19.5
react: 0.12
react-devtools: 0.12

**Comment by deepak1556** [comment]
React v0.12 has deprecated React.__internals https://github.com/facebook/react/releases/tag/v0.12.0 . So loading of the extension's devtools_page by atom-shell will fail at this condition `https://github.com/facebook/react-devtools/blob/master/injected/ReactHost.js#L42` which is initialised by a globalhook contentscript https://github.com/facebook/react-devtools/blob/master/injected/GlobalHook.js . I tried adding the contentscript to main.html https://github.com/deepak1556/react-devtools/blob/atom_shell_test/main.html#L4 and extension loaded successfully. Except the treeview wasnt constructed..
![react-devtools-atom-shell](https://cloud.githubusercontent.com/assets/964386/5680580/0a615068-9835-11e4-86df-eb74c846aac1.jpg)

**Comment by zcbenz** [comment]
@deepak1556 Thanks for looking into this, I think we have to support the `content_scripts` to load latest react devtools extension.

**Comment by dlmanning** [comment]
Is this on the roadmap?

**Comment by steelbrain** [comment]
Bump.

**Comment by LongLiveCHIEF** [comment]
It seems all the issues regarding this issue reference each other and then close. It's the infinite issue of doom.

**Comment by bruce** [comment]
Also, this is a wider issue; it's also a problem with the Ember Inspector, as noted in (merged) #1644.

**Comment by mrzmyr** [comment]
Bump.

**Comment by faurehu** [comment]
I'm calling the same line indicated in the docs: 
`require("remote").require("browser-window").addDevToolsExtension("../react-devtools");`

It throws the following error:
`Error: ENOENT: no such file or directory, open '../react-devtools/manifest.json'`

This seems to be because it keeps looking for a `manifest.json` file. The devtools doesn't need to provide this because it's not really a CRX package.

I'm on Electron v0.31.1, React v0.13.3 and react-devtool 0.13.1

**Comment by swashcap** [comment]
:+1:

**Comment by swashcap** [comment]
If you install React Devtools in `./devtools/react-devtools` and then run:

```js
require('remote').require('browser-window').addDevToolsExtension('./devtools/react-devtools/shells/chrome');
```

…it finds the `manifest.json` file. The docs should be updated. **However**, the dev tools don’t appear to load.

😔

**Comment by dlmanning** [comment]
Anyone checked to see if [React's beta dev tools](https://github.com/facebook/react-devtools) work? I'll test them tomorrow if no one else gets a chance.

**Comment by faurehu** [comment]
I directed it to the `manifest.json` file and it printed `"New React Developer Tools"`. The tools are not there so it's an issue similar to yours.

**Comment by dlmanning** [comment]
Yep, no luck loading the beta dev tools either

**Comment by etiktin** [comment]
@deepak1556, @zcbenz it seems that pretty much all framework extensions (AngularJS Batarang, React Developer Tools and Ember Inspector) aren't working. Can you explain what is needed in order to add support for them, maybe some of us can help solve this?

**Comment by dlmanning** [comment]
ditto, would be happy to help if someone could just point out the direction.

**Comment by zcbenz** [comment]
@etiktin The extensions are handled under `atom/browser/lib/chrome-extension.coffee`, we need to read the `content_scripts` and apply them in the renderer.

But only supporting `content_scripts` is probably not enough, latest react-devtools is also using `chrome.runtime.connect` and other Chrome APIs to communicate with the content scripts.

**Comment by faurehu** [comment]
@dlmanning if you link your PR early I'd follow

**Comment by jprichardson** [comment]
I wish I had seen this issue before I went down the rabbit hole (React dev tools) for a couple of hours. Would you be willing to at least update the documentation reflecting that this does not work as expected just yet? Thank you.

**Comment by kevinsimper** [comment]
@jprichardson I added the note here https://github.com/atom/electron/pull/3313

**Comment by dbpolito** [comment]
I also tried to install https://github.com/vuejs/vue-devtools , which is basically the same as react-devtools and i got the very same result...

**Comment by dperetti** [comment]
This is really depressing.

**Comment by paulcbetts** [comment]
To be honest, the easiest way to get this working is to just submit a PR to react-devtools to detect Electron inside its extension and have it do Different Things (i.e. it should be easy because you can do whatever you want)

**Comment by H3Chief** [comment]
> To be honest, the easiest way to get this working is to just submit a PR to react-devtools to detect Electron inside its extension and have it do Different Things

There's the easy way, and then there's the right way.  If I were a react-devtools maintainer, I wouldn't accept that PR. Think that through to the endgame, and then the react-devtools codebase would be watered down with stuff for tons of different platforms, tools, environments, etc...

You'd also likely wind up with this same problem the other way around... where you wind up having to patch react-devtools because some api inside of Electron changes.

Maybe a better route to go would actually be to create some sort of standalone plugin for Electron that enables 3rd party devtools?

**Comment by paulcbetts** [comment]
> You'd also likely wind up with this same problem the other way around... where you wind up having to patch react-devtools because some api inside of Electron changes.

This is just as true for Chrome's API

> Think that through to the endgame, and then the react-devtools codebase would be watered down with stuff for tons of different platforms, tools, environments, etc...

I mean, I see what you're saying here, but I don't think that many environments support Chrome DevTools but aren't Chrome - basically just us and nw.js (and I guess CEF)

**Comment by DiThi** [comment]
Will fixing this the correct way also make amCoffee work?

**Comment by mcanthony** [comment]
I am confused, how is it that apparently all framework related devtools extensions fail under Electron but not under NW.JS, which as far as I know should have the same CEF/Devtools extensions API implementation. Patching React Devtools seems not to be a viable option, for the reasons others have stated previously, but also because the same patch would seem necessary for all the other problematic/failing Devtools extensions.

Let us indulge this route anyway: What "Other Things" should the patched React Devtools extension do differently in the context that it detects the operating environment is Electron/CEF and not a browser? Did I overlook some nuggets of wisdom in these devtools issue threads... @zcbenz  "The extensions are handled under atom/browser/lib/chrome-extension.coffee, we need to read the content_scripts and apply them in the renderer." - this statement was the closest thing I could find to a supposed fix, however I can't wrap my head around what is suggested. Support for content_scripts API must be emulated and manually "applied in the renderer"?

What is NW.JS doing or not doing which is enables it to work? It would seem the fact NW.JS merges Node into a unified context vs. Electron using a separate process should not effect CEF's apps/extensions APIs end of things. If it works in NW.JS my guess would be that Electron lacks one of more API's which NW.JS doesn't. Not surprising as NW.JS is in excellent cadence with CEF/Blink updates. Now if we only knew exactly what the missing API(s) are, then maybe we would be a step closer to a final solution.

**Comment by zcbenz** [comment]
@mcanthony Recent versions of React DevTools Extension require some new `chrome.*` APIs, which are not implemented in Chromium's content module by default.

I don't think NW.js supports devtools extension.

**Comment by darrrk** [comment]
:+1:

**Comment by 9o** [comment]
I cry tears.

**Comment by dperetti** [comment]
It looks like the future for being able to use React devtools with Electron is [here](https://github.com/facebook/react-devtools/tree/b18ec33387da1f315082564acb34015c772cf4b6/shells/plain) .

**Comment by sunjay** [comment]
+1

**Comment by jsnar** [comment]
NW.js has support for devtool extension for months. Recently React devtools is supported too: http://nwjs.io/blog/v0.13.0-beta7/ 
I believe they have better Chrome features support and newest Chromium version.

**Comment by vladfr** [comment]
@dperetti have you tried the pure html version, does it work?

**Comment by dperetti** [comment]
I didn't have time to try in Electron but I'm 100% sure it can work since I've been able to run their example in... Safari.
Their example uses an iframe though. That prevented me to be able to get it to work easily in my current project.
I think ideally, one should open the pure html dev tools in a different Electron window, which would communicate then with the other windows in a more "Electron" way.

**Comment by steve10287** [comment]
Any update on this? I cannot get this to work: 

`require('remote').require('browser-window').addDevToolsExtension('./react-devtools/shells/chrome')`

**Comment by vladfr** [comment]
I've been trying to get this to work with electron with no luck. I can get the above command to work, but the React tab doesn't show up. I've tried to start from the example in /shells/plain/ but to no avail, it's so contrived that I can't understand it. Anyone has any insight?

**Comment by xhocquet** [comment]
Read up, there were breaking changes in React that have not been resolved. Also waiting for this, running into some nasty React bugs and I can't find out what listeners are on my modules!

**Comment by inklesspen** [comment]
I spent some time poking around with this today, and after much effort, figured out how to manually add the content_script from the react devtools to my app. this permitted the react devtools to detect React in my app, but trying to connect to it failed because `chrome.runtime.getURL` and `chrome.runtime.connect` are not implemented. (Just for completeness' sake, I note that devtools also use `chrome.runtime.onConnect` and `chrome.tabs.executeScript`.)

**Comment by frankhale** [comment]
Not sure if this is widely known or not but there seems to be a fork of the React Devtools that does work with Electron.

https://github.com/firejune/electron-react-devtools
https://www.npmjs.com/package/electron-react-devtools

**Comment by davej** [comment]
@frankhale Awesome, were you able to get it working? It didn't work for me.

**Comment by frankhale** [comment]
I haven't tried it yet but definitely will either today or in the next few days.

**Comment by albertoclarit** [comment]
Not working for me...

**Comment by philostler** [comment]
Gave it a try earlier. Didn't work for me neither

**Comment by davej** [comment]
@albertoclarit @philostler Created issue here: https://github.com/firejune/electron-react-devtools/issues/1

**Comment by philostler** [comment]
I see this is fixed in the latest Electron release. Has anyone else tested and got this working? I can get React DevTools loaded in but I just get "Connecting to React..." 😞

**Comment by inklesspen** [comment]
@philostler When I use https://github.com/chentsulin/electron-react-boilerplate (and update the package.json to use electron 1.2.1), I can get the React Devtools working by following the instructions.

![screen shot 2016-06-04 at 10 04 44 am](https://cloud.githubusercontent.com/assets/11397/15800330/d0783548-2a3b-11e6-95dc-2136dab07551.png)

**Comment by philostler** [comment]
@inklesspen Thanks, confirmed also, but still not working in my own app. NP must be another issue

**Comment by albertoclarit** [comment]
Electron 1.2.1 React DevTools is now working on my App...

**Comment by bachmay** [comment]
AngularJS Batarang is still not working

![screenshot 2016-06-10 17 18 21](https://cloud.githubusercontent.com/assets/6717537/15979007/8635d01e-2f2f-11e6-8ddb-eed70815fab9.png)

**Comment by mnquintana** [comment]
@bachmay Please open a new issue – this issue is only for the React dev tools not working. Thanks!
