### ISSUE TITLE
Picking a value suggested by a <datalist> for an <input> is not reflected by latter's `value` property

### ISSUE THREAD

**Issue by amn** [electron/electron#9860]
Electron version: 1.7.3 beta
Operating system: Windows 7 x86_64 Professional

Clicking the pyramid icon on an input control associated with a data list and picking a value from the list, then evaluating `value` property of the input control, the value is expected to match the text chosen from the data list, which the input control is now showing.

Instead, the text returned by `value` property is an empty string, or at least the string that was manually typed into the input control prior.

Only manual editing of value of the input control, as you would with an ordinary text input without a n associated datalist, causes the `value` property to yield the same text that the input control is showing.

Using following markup to reproduce by loading up default Electron distribution and typing `document.location = ...; /* path to file containing below text */` in Developer Tools console:

	<!DOCTYPE html>
	<html>
		<body>
			<input list="foobar">
			<datalist id="foobar">
				<option value="apple">
				<option value="orange">
				<option value="banana">
			</datalist>
		</body>
	</html>

**Comment by StillOnMyWay** [comment]
Thanks for opening this. Still no response from the electron team.

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/pull/10510

**Comment by StillOnMyWay** [comment]
@codebytere Does this really count as closed? @sofianguy added the version 1.7.x label to this issue, but the release that it was included in was 1.8.2@beta-3. I'm currently on 1.7.11 and the issue is not fixed.

**Comment by gabalicious** [comment]
@electron @codebytere This issue shouldn't be marked as fixed.  Can we please reopen this?

**Comment by MarshallOfSound** [comment]
@gabalicious @StillOnMyWay We can not reasonably back port every bug fix and every feature to older versions of Electron.  `1.8.x` is now a stable release line and if you require this fix you should have to that stream.
